### ISSUE TITLE
Documenting community components

### ISSUE THREAD

**Issue by matt-oakes** [react-native-community/discussions-and-proposals#101]
### Introduction
Now we are moving components out of the core of React Native, we need to think about where the documentation for them will live.

### The Core of It
Currently, all of the core components are documented at [facebook.github.io/react-native](https://facebook.github.io/react-native/). This makes sense as they are official components and are part of the core. Now they are being deprecated and moved out of the core we need to think if it makes sense to keep the documentation there or to move it out.

I see a few different options:

#### Leave them in the official documentation
**Pro**: Makes it easy for newcomers to find "official" components which they can use.
**Con**: Where do we draw the line on what to include? `react-native-video` has never been part of the core, but is now in the same organisation as the migrated components. Should it then be included on the official website?

#### Remove them from the official documentation and document each in their README
**Pro**: No need to update the website every time the components change.
**Con**: New users might not know where to find components and therefore see React Native as very  "feature incomplete" compared to frameworks which have a more "batteries-included" approach.

#### Remove them from the official documentation and create a new community documentation website
**Pro**: Keeps the official documentation light and focused only on the core but also gives certain components a more "official" feel than just being another Github repo.
**Con**: Still spreads the documentation out and makes it harder to find which components exist and we will need to maintain a whole new website.

### Discussion points
* Which approach makes the most sense?
* Are there other options?
* Where do we draw the line on "official community" modules?

**Comment by cpojer** [comment]
Thanks for creating this issue!

My preference would be:
* Remove from RN website
* Put documentation into a README, if it fits
* If the project warrants its own documentation website, create that
* Create a docs page on the RN website that lists community modules, which for now would be limited to linking modules within `react-native-community`

Does that answer your questions?

**Comment by matt-oakes** [comment]
Yes, that makes sense to me too.

I think we might need to consider how exactly this looks on the website to make sure it's still discoverable and easy to find how to do things in React Native. For example, searching for "status bar" on the main website should clearly point towards the documentation for the new `@react-native-community/statusbar` README.

This will only matter once we have officially removed the module from the core, however, there should be a plan in place which makes the change clear to existing and new users where all of the modules have gone to.

**Comment by cpojer** [comment]
Closing since I don't think we need to discuss this further for now.
