### ISSUE TITLE
How does diffing props work?

### ISSUE THREAD

**Issue by expressiveco** [react-native-community/discussions-and-proposals#102]
### Introduction

How does diffing props work for react native? What is the related source code for it?
It might be similar to updateDomProperties(https://holmeshe.me/understanding-react-js-source-code-virtual-dom-diff-VIII/)

### The Core of It

Especially, i try to understand react native WebView (https://github.com/react-native-community/react-native-webview) source property. Changing some fictive prop of source forces refreshing of webview for the same uri.
``` js
source={{uri:"http://...", forceReload:this.state.forceReload}}
```
How is this possible?

**Comment by cpojer** [comment]
Hello,

this repo is not for questions about React Native but for the future development and direction of the project. Please ask this on Stackoverflow.
