### ISSUE TITLE
Is there any way to ship the ReactNative project(Base Project) and extends into multiple apps

### ISSUE THREAD

**Issue by gowthamans268** [react-native-community/discussions-and-proposals#108]
I am creating a ReactNative app project(Base Project) and it is working fine, I want to ship that project and want to extend that into multiple app.

I want to generate multiple app(.apk, .ipa) out of the base project with different dashboard (Landing page after login) and images(resources)

Is there any way to ship the project and add new components, Assets(Images) to it without transferring the entire code(Base Project).

I don't want to share the raw code to all the child projects expecting some thing like WebPack, Minified files or any extenstion plugins could help this.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
