### ISSUE TITLE
add option to selectable <Text/> context menu

### ISSUE THREAD

**Issue by ammoradi** [react-native-community/discussions-and-proposals#112]
### Introduction

the ability to add some options to selected text's context menu both on Android and IOS.

### The Core of It

as mentioned [**here**](https://stackoverflow.com/questions/48883406/react-native-add-option-to-text-context-menu), I want to add custom options to the selected text's context menu ( or remove some options. for example, remove 'copy' option ) and new options should have listeners and handlers for touch.
all related issues closed on react-native's repo and all questions in StackOverflow remained unanswered. then it seems should be discussed here.

### Discussion points

as I noticed, this issue won't be solved officially at this moment. but **giving a manual/temporary solution** will be good.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

**Comment by sibelius** [comment]
maybe this https://github.com/Astrocoders/react-native-selectable-text
