### ISSUE TITLE
Allow access to iOS Instance Properties with Network requests

### ISSUE THREAD

**Issue by bondparkerbond** [react-native-community/discussions-and-proposals#113]
### Introduction

On iOS in React Native, immediately after successfully connecting to a WiFi network, if 4G is also on, it is possible that network requests sent via fetch get sent over 4G instead of WiFi for several seconds (between 1 and 40 seconds depending on the device and network in my experience). If the calls are meant to be communicating with a local Wireless Device (such as a wireless router, etc.), then those API calls that get sent over 4G to the internet are lost. Note that Reachability/NetInfo are saying that we are connected to a WiFi network and are not sufficient to prevent this from happening. To prevent this, I would like to be able to set an instance property that iOS exposes for network requests allowsCellularAccess to NO to ensure a request is never sent over 4G.

### The Core of It

On iOS in React Native, fetch and XMLHttpRequest api calls get sent through the RCT Networking library, which delegates to the native URLSession for API calls. However, while things like [cookies](https://github.com/facebook/react-native/issues/19958) can be modified and configured, other functionality like the instance property [allowsCellularAccess](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1409406-allowscellularaccess?language=objc) (default value: yes), are not configurable on either a session/app wide scope or on a more granular level with individual fetch api calls. Note that the per session configuration could be handled using NSURLSessionConfiguration set in [RCTHTTPRequestHandler.mm](https://github.com/facebook/react-native/blob/master/Libraries/Network/RCTHTTPRequestHandler.mm). Alternatively, this functionality could be configured for each api call; possibly by passing in an additional header or somehow overriding the global(window?) fetch behavior when making an api call to allow more fine grained control on a per fetch call basis with [NSMutableURLRequest](https://developer.apple.com/documentation/foundation/nsmutableurlrequest?language=objc).

### Discussion points

-At minimum, I would like a way to set the value of allowsCellularAccess on either an app/session wide or per fetch call basis.

One such place this could be set would be in RCTHTTPRequestHandler.mm to add a     `configuration.allowsCellularAccess = NO;` to the defaultSessionConfiguration at line 67:
```
    NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
    [configuration setAllowsCellularAccess:NO];
    [configuration setHTTPShouldSetCookies:YES];
```

Note that allowsCellularAccess would have to default to YES and be configurable somewhere(Info.plist, some other place?) to read in an override value (if provided) so it could be changed. If someone knows where this would best be configured I'd be happy to open a PR for it. I would also be open to other ways to set this value.

-It may be useful to expose other properties inside either NSURLSessionConfiguration and/or NSMutableURLRequest.

-While this Issue is focused on iOS specifically, there may be similar functionality appropriate to expose on Android to help keep Platform parity where appropriate. However, due to the fact that Android interfaces via OKHTTP that may not be practical. I know of at least one way to forceWifi usage on Android already with react-native-android-wifi so such functionality is not as critical in my opinion.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

Or, if you prefer to go ahead with a first PR to do what you proposed

> One such place this could be set would be in RCTHTTPRequestHandler.mm to add a configuration.allowsCellularAccess = NO; to the defaultSessionConfiguration at line 67: [...ETC]

I think it would help a lot to move the conversation forward with the FB devs actually working on that side of the project. Tbh you could literally just open the PR with the new config element (maybe as a draft pr), and then via feedback select the best approach to give a way to 

> that allowsCellularAccess would have to default to YES and be configurable somewhere(Info.plist, some other place?) to read in an override value (if provided) so it could be changed.

**Comment by bondparkerbond** [comment]
Thank you for the feedback @kelset. I took your advice and created a [Draft PR](https://github.com/facebook/react-native/pull/24242). Could you recommend someone from the React Native team to have a look at it?
