### ISSUE TITLE
Supporting push notifications on Android

### ISSUE THREAD

**Issue by gzzo** [react-native-community/discussions-and-proposals#114]
### Introduction

PushNotificationIOS works perfectly on iOS.  React Native should support push notifications on Android as well.

### The Core of It

It looks like the go-to library for Android support has been [react-native-push-notification](https://github.com/zo0r/react-native-push-notification). However, it looks like that repository isn't maintained anymore and may have been abandoned.

I think it's reasonable to expect developers to want push notification support on both platforms mostly out-of-the-box without having to resort to third parties. There's several third parties with freemium react-native support (Firebase, OneSignal, Pusher).

### Discussion points

Options:
 1. Adopt react-native-push-notification into react-native-community
 2. Create a PushNotificationAndroid API
 3. Add Android support into PushNotificationIOS and rename the API to PushNotification

**Comment by cpojer** [comment]
We are currently extracting this functionality from React Native into https://github.com/react-native-community/react-native-push-notification-ios

Would you be able to lead the effort to bring the Android version into the react-native-community and possibly building one library to handle push notifications for both platforms?

**Comment by sibelius** [comment]
you should check react-native-firebase for this

**Comment by gzzo** [comment]
@sibelius I mentioned that in the issue description. I don't think RN should rely on third parties with freemium models for Android push notifications.

@cpojer So is the preferred option from my description the third one, to have a unified API, `PushNotification`?

**Comment by sibelius** [comment]
firebase is de facto solution for android push

GCM is deprecated, everything now is FCM, you can use it for free forever

Google does not have any other option

**Comment by gzzo** [comment]
Thanks, I didn't know that. Looks like GCM will be deprecated 4/11/2019.

That means that the unified PushNotification API will only need to support FCM.

**Comment by rhdeck** [comment]
I contributed the FCM support PR for react-native-push-notification and I
use it in production.    Glad to belp a RNC initiative for that support.

**Comment by rafaellincoln** [comment]
@gzzo Feel free to open a PR on [push-notification-ios](https://github.com/react-native-community/react-native-push-notification-ios)

**Comment by Salakar** [comment]
👋 `react-native-firebase` author here. There was a proposal already discussed to address this:

-> [[Proposal](https://gist.github.com/Salakar/795a4918586c42cdbea28688db3dbc52)]

Given the efforts in `react-native-firebase` on-going right now (v6) this made sense when we got together to discuss so as to avoid duplicating work. The proposal got delayed in posting for various reasons.

In terms of `react-native-firebase` it's not a case of Firebase or nothing. It has an extensive local notifications API that 'technically' has no requirements on FCM itself, as well as FCM support of course. On the current version (v5.x.x branch), these are all sat together and not possible to only use parts, v6 however (master branch - wip) everything is its own NPM package.

I'm starting work migrating the `messaging` package (FCM) and the `notifications` package (local notifs + remote receivers) within the next month to their own packages. My ideal vision for notifications is a mono repo with multiple packages, packages that address local notifications, remote notifications and different providers (APN & FCM first party, all others extra).

Let me know your thoughts on the proposal, most likely needs changing now that work has already started on iOS anyway.
