### ISSUE TITLE
Guidelines for community packages

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/discussions-and-proposals#115]
### Introduction

Hey Everyone! Today I planned to re-implement several of deprecated modules via new ones created within react-native-comunity. I soon came to realisation that currently each repo within community is different from one another in various aspects and hence wanted to discuss possibility of unifying them in order to provide consistent experience.

### The Core of It

- Some packages lost their typescript definitions once they were extracted from main rn project, since `@types/react-native` covered pretty much whole codebase.

- `.podspec` files for iOS are sometimes located either in root of the repository or inside `ios` folder.

- Some packages have ci process set up in place, others don't

- Packages have different eslint configs, some try to use react-native-community preset, but add extra rules or overwrites

- README files are very different in terms of headline order / having or not having demos, their language style etc...

- Folder organisation is different, some use `lib` for main code, some use `src`. Some repos have examples, others don't.

### Discussion points
Should we come up with an effort to deduct common guidelines for community repos and strategy of how to implement them, or would this harm development / speed of each package?

**Comment by kelset** [comment]
We have literally a whole repo where we are trying to get all the maintainers of RNComm on board and share and discuss and write guidelines -> https://github.com/react-native-community/meta

Would love to have your feedback in the issue section over there!
