### ISSUE TITLE
Store JS bundle loaded from dev server in a custom path

### ISSUE THREAD

**Issue by hasretsariyer** [react-native-community/discussions-and-proposals#119]
I have integrated react-native with an existing android app. In dev mode, I want to load bundle conditionally from server. Below function works for me:

    public void startReactApplication(String bundleUrl, String moduleName) {
        SharedPreferences preferences = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        preferences.edit().putString("debug_http_host", bundleUrl).apply();

        ReactRootView mReactRootView = new ReactRootView(this);
        ReactInstanceManagerBuilder builder = ReactInstanceManager.builder();

        ReactInstanceManager mReactInstanceManager = builder
              .setApplication(getApplication())
              .setCurrentActivity(this)
              .setBundleAssetName("index.android.bundle")
              .setJSMainModulePath("index")
              .addPackages(getPackages())
              .setUseDeveloperSupport(BuildConfig.DEBUG)
              .setInitialLifecycleState(LifecycleState.RESUMED)
              .build();

        mReactRootView.startReactApplication(mReactInstanceManager, moduleName, null);
        setContentView(mReactRootView);   
    }

I expect this code to work in offline mode. So, I need store multiple bundle files. But the value of  `mJSBundleTempFile` in [DevSupportManagerImpl](https://github.com/facebook/react-native/blob/8d5ac8de766b9e435cbfa9bfa6b8a2b75b0e2a19/ReactAndroid/src/main/java/com/facebook/react/devsupport/DevSupportManagerImpl.java) class is hardcoded. I cannot override this value. I need to customize  this value.

Is this a reasonable request? I will create a pull request for this task.

**Comment by cpojer** [comment]
I'm not sure if this change makes sense. If you can find a way to send a pull request that adds some functionality without adding a lot of complexity or trade-offs, I'm happy to land it, though.
