### ISSUE TITLE
Unblock ui from hard coded 60fps limit in iOS

### ISSUE THREAD

**Issue by IljaDaderko** [react-native-community/discussions-and-proposals#123]
### Introduction
Judging by https://github.com/facebook/react-native/blob/master/Libraries/NativeAnimation/Drivers/RCTAnimationDriver.h#L13 iOS is currently limited to 60fps as maximum frame rate, I'm not entirely sure why?

Why are we limiting rn to this when there are 120Hz ios devices on the market and more 60Hz+ devices in Android?

Is it possible to remove this hard coded limit?

### The Core of It
It all started when I found this issue https://github.com/facebook/react-native/issues/14505 and started discussion on reddit https://www.reddit.com/r/reactnative/comments/bhwls0/does_reactnative_support_60_fps

I think 60fps is more than enough for smooth UI's but since more and more devices support higher refresh rates, should we consider removing this limit?

### Discussion points

1. Does Android have similar limitation?
2. Is this a simple change i.e. we change 60 to 120 as the value, or will it be more complex?
3. Will there be any performance hits from increasing this value?
4. Do we need hardcoded limit at all, i.e. can we remove it?

**Comment by jacobp100** [comment]
I think this constant is only used for aligning animations when looping. The animations appear to be driven by CADisplayLink, which will be 120fps.

I think while this could be fixed, the current worst case is that that animations might at most a single frame out on 120fps

**Comment by IljaDaderko** [comment]
@jacobp100 gotcha, might close this in few days then unless someone confirms otherwise 👍
