### ISSUE TITLE
New Permissions API for both platforms

### ISSUE THREAD

**Issue by karanpratapsingh** [react-native-community/discussions-and-proposals#124]
### Introduction

I would like to propose a permissions API within the react native core itself that works on both platforms similarly to expo.

Currently, React Native only has out of the box support for Android Permissions and not iOS, and in my opinion, something as crucial as Permissions should ship with React Native itself.

Proposal:
- React Native should include universal permissions module
- the module should function like the package react-native-permissions
- eg.
   ```js

     import { Permissions } from 'react-naitive';

     Permissions.check(type: string);
     Permissions.request(type: string);
  ```

 - Types may be like: photos, camera, location.

### Reason:

 This issue may seem stupid as there is already an external package to get this functionality but that's not my point, I personally think that react native should have out of the box, basic permissions module. At least for basic permission that are available on both platforms.

A special thanks as always to all the contributors and developers pushing the boundaries of react native :D

**Comment by cpojer** [comment]
Hey! Thanks for creating an issue. Normally on this issue tracker we expect issues to be fully fleshed out and have a concrete proposal. Can you edit your post to add a lot more context, proposals and discussion points? Thank you.

**Comment by karanpratapsingh** [comment]
@cpojer okay, I will update and add as much I can think of :D

**Comment by kelset** [comment]
I think that this should not be in the main codebase; not all apps require permissions and as we saw with the Geolocation module because of Apple's review requirements having something like https://github.com/yonahforst/react-native-permissions in the main codebase would force every developer to undergo this:

https://github.com/yonahforst/react-native-permissions#app-store-submission-disclaimer

And it was one of the main reasons why it was decided to have Geolocation undergo the "Lean Core" treatment.

**Comment by karanpratapsingh** [comment]
@kelset oh okay, thank you for clarification, though I think it can be implemented in a better way than react-native-permissions.
Thanks for your reply :D

**Comment by kelset** [comment]
>  I think it can be implemented in a better way

I'd love to hear more about it! Do you think that your implementation could "solve" that issue with App Store?

**Comment by karanpratapsingh** [comment]
> > I think it can be implemented in a better way
> 
> I'd love to hear more about it! Do you think that your implementation could "solve" that issue with App Store?

I think it can be split into react-native-permissions/<permission type> 
for example. react-native permissions/location
or we could make it modular like:

import * as Permissions from 'react-native-permissions'

and use like:

Permissions.location.get(...) or request(...)

Though It would require a complete rewrite

**Comment by kelset** [comment]
> this would solve that issue of getting rejected from the appstore

I'm not sure about this, AFAIK the issue is that if there is code "interacting" with those endpoints anywhere in the bundle you'd still have to add those extra lines 🤔

**Comment by brentvatne** [comment]
@karanpratapsingh - you might be interested in this PR on react-native-permissions: https://github.com/yonahforst/react-native-permissions/pull/291
