### ISSUE TITLE
Carplay and Android Auto support

### ISSUE THREAD

**Issue by WilbertE** [react-native-community/discussions-and-proposals#128]
# Feature Request

Carplay and Android Auto are still very young and limited in what they can do. But they are growing and probably will be in a lot of cars in a couple of years. React Native should support Carplay and Android Auto (is it possible in the future?)

## Why it is needed
It is needed because cars will become more and more 'self driving' and the entertainment in the cars will become more important. 

## Note
Is this even possible (in the future)?

**Comment by ericlewis** [comment]
@WilbertE from what I know about CarPlay at least, you can make navigation apps *or* answer Siri requests. The navigation apps are view controllers that live inside of your main application, but have pretty strict requirements and use templates for displaying things. I am not sure that CarPlay would be useful to use with react-native due to the UI limitations. Siri can be interacted with via custom native modules already.

**Comment by kelset** [comment]
👋 there

two things:
- there are no plans to add new platforms in the core library, the long term idea is actually to have the core being super generic and each "targetted" platform to be its own "repo" (think `react-native-android`, etc) (there are a few other issues in this very repo, so I suggest to look for more details about this there)
- There is already a carplay repo, in case you didn't know https://github.com/birkir/react-native-carplay

I'm going to close this, as it's not something really "actionable" - but if you have any other thoughts to share on the subject I'd love to hear them :)

**Comment by ericlewis** [comment]
@kelset that repo is *not* react-native integrated with CarPlay. It is a normal iPhone app made to look like CarPlay.

**Comment by bouaoud** [comment]
Hello the Team,

Any updates about this subject? could you tell us if any actions from facebook or react native community are ins progress to setup android car and carplay?

thanks

**Comment by kelset** [comment]
No changes since my message last year.

**Comment by bouaoud** [comment]
thanks @kelset

**Comment by jono-fig** [comment]
will need some bindings for the new android auto's ecosystem 
https://android-developers.googleblog.com/2020/10/introducing-android-for-cars-app-library.html
