### ISSUE TITLE
Modal Component - hardcoded adjustResize windowSoftInputMode on Android

### ISSUE THREAD

**Issue by alimek** [react-native-community/discussions-and-proposals#136]
### Introduction

Faced problem on Android that I had `<Modal />` component with transparent background and  there was child component which covers 100% width and 80% (from bottom) height for content area.

Inside the content I have input. When input is focused keyboard appears and RN screen is automatically resized to `totalHeight - keyboardHeight` because of that commit: [404b7cc069471cc8e0277d398751305665f0d3e1](https://github.com/facebook/react-native/commit/404b7cc069471cc8e0277d398751305665f0d3e1?fbclid=IwAR1OpZXUHPgMZ6k6NN9wvhM079HOMHxSNKrRmmMzCvCqCCmqoSAihZ5gMAk#diff-6453d554bf967fe816a1aa3735c9fe62).

Problem is when keyboard is going down and user can see for short period of time what is behind the `<Modal />` until screen resized again to initial height. 

### The Core of It

We can not change behaviour of RN `Modal` component how it is configured with `windowSoftInputMode` on Android. It is just hardcoded.

### Discussion points

Tried to debug it and can't find any option to change that behaviour to change to `adjustPan` or any other option to render keyboard on top on my modal instead of resizing whole screen. 

Can someone point me to direction why this is expected behaviour for Android and why we shouldn't have option to adjust it for our needs?

cc: @andreicoman11  and @astreet

**Comment by kelset** [comment]
This seems to me as a specific question, and not a broad discussion about react native itself. Please use StackOverflow instead - if instead you are "requesting" a feature, I'd recommend that you open a PR with the implementation of this so that it can be discussed further in the right scope.
