### ISSUE TITLE
 [Proposal] An additional way of styling components

### ISSUE THREAD

**Issue by ecreeth** [react-native-community/discussions-and-proposals#137]
### Introduction

I currently love the way to give styles to the components in **React Native**, but sometimes I think it can be even better than it already is.

Libraries like [styled components](https://www.styled-components.com/) have helped us for a long time to manage styles in a more organized and flexible way when sharing styles between components.

I think that flexibility and organization can be transferred to **React Native** by improving the **StyleSheet** API.

### The Core of It

These are the two proposed ways to add a little more power to the **StyleSheet** API

1. #### With styled components

![image](https://user-images.githubusercontent.com/20761166/60036085-5d7b8d00-967c-11e9-996d-ac12dabb794d.png)

-  With default props

![image](https://user-images.githubusercontent.com/20761166/60048473-3469f500-969a-11e9-8f04-e10c180a50e5.png)

### Discussion points

I would like to know if this can serve more people.

##### This is not intended to eliminate the way in which, until now, we give styles to the components. This is pretended to be optional

cc @cpojer

**Comment by pvinis** [comment]
If I can offer my opinion, personally I don't like the styled way, and since there are a few libs that do that already and with lean core, I don't see how embedding it would help.

I kinda like the theme way, but again I would have to be a second way while keeping the original, since the original can work in ways like having your whole UI style app-wide or having it per whatever you like, and we can use it more freely.

I'm not going against this suggestion though, don't get me wrong. I'm sure we can find a nice upgrade to stylesheet :D

**Comment by ecreeth** [comment]
@pvinis Thanks for your opinion! This would be a second way of giving styles to the components, so that the people can choose the way in which they feel more comfortable.

**Comment by MoOx** [comment]
Same as @pvinis, I don't like the styled way, and I think it's really not a good thing to call component by their name via a string, especially now that JS ecosystem is looking at typed system (ts, reasonml etc). 
Anyway having multiples APIs for the same thing that doesn't really offers any killer feature doesn't worth it imo.
Btw, having a "style" api that handle default props looks definitely wrong.

for my concern: I like the stylesheet api & don't want to see that changed. It very low level & allow various abstraction on top of it, which is good enough to make everyone happy.

**Comment by acoates-ms** [comment]
Why does this need to be part of core?  Letting styling continue to evolve externally seems preferable.  That way when new opinions on how styling should be done come along there are not breaking changes or legacy code to deal with in core.  The only reason to do this in core would be if there is something that can only be done in core -- then we should look at how to enable that.

**Comment by brodybits** [comment]
> since there are a few libs that do that already and with lean core

Is this documented anywhere?

> Letting styling continue to evolve externally seems preferable.

Agreed if we can document some recommendations.

I think the stricter styling rules of React Native compared to standard HTML5 is a major pain point right now.

**Comment by TheSavior** [comment]
I think that we are unlikely to structurally change StyleSheet as it is today. It would require significant value to be worth those breaking changes.

The one area we are open to changes in StyleSheet are ways to better support more platforms, such as Microsoft’s PlatformColor api, and ways to consolidate differences with the styleX api for stylesheets on web that was shown at React Conf as part of how we are building the new Facebook.com.

I think that ideas or approaches for those areas would be part of a separate proposal, so I’m going to close this one.

**Comment by slorber** [comment]
@TheSavior any link to PlatformColor or styleX? interested by anything cross-platform ;)

**Comment by TheSavior** [comment]
Platform color proposal: https://github.com/react-native-community/discussions-and-proposals/issues/126#issuecomment-565913027

**Comment by brodybits** [comment]
> StyleX: https://youtu.be/9JZHodNR184

https://twitter.com/wongmjane/status/1187411809667436550

I guess that would not yet be ready for open source?

**Comment by TheSavior** [comment]
We want to see it converge more with React Native’s StyleSheet before open sourcing it

**Comment by slorber** [comment]
Thanks, actually watched the talk a while ago but didn't remember it had a name ;)
