### ISSUE TITLE
compile core js-bundle into JSC.

### ISSUE THREAD

**Issue by zcgit** [react-native-community/discussions-and-proposals#139]
### Introduction

compile js-bundle as std::string into JSC, so we can save loading time.

### The Core of It

I've learned a lot about how to reduce launching app time, and a lot of them are talking about splitting bundles, but sometimes it's hard to split several modules, such as my app needs react-native core and aws - amplify libs at least.

### Discussion points

So, could we make the react-native core or other libs we specified compiling into JS machine?

**Comment by kelset** [comment]
This doesn't seem to be a broad discussion that should live on this repo, but a precise feature request. I would recommend that you open a PR against core with the proposed changed so that it can be discussed further.
