### ISSUE TITLE
Is is possible config ignore list which packages will not auto add PackageList on Android?

### ISSUE THREAD

**Issue by canyara** [react-native-community/discussions-and-proposals#143]
RN-codepush is not support 0.60.0 and now I can not pass the server address param.
Now generated PackageList.java looks like this:
`new CodePush(${androidDeploymentKey}, getApplicationContext(), BuildConfig.DEBUG)`

If there is such ignore auto package config, I can manually add these package which need special parameters.

**Comment by kelset** [comment]
👋
this is not the right repository for this kind of issue - I recommend that you open an issue in the codepush repository instead
