### ISSUE TITLE
Navigating Between Screens

### ISSUE THREAD

**Issue by grahammendick** [react-native-community/discussions-and-proposals#145]
### Introduction
Jotting down some thoughts on navigating in React Native as [@osdnk suggested](https://github.com/facebook/react-native-website/pull/1086#issuecomment-511023355). The aim is to move towards some new text for the ["Navigating Between Screens” page](https://facebook.github.io/react-native/docs/navigation) that’s fair to all navigation libraries, both old and new.

### The Core of It
The first two promises on the front page of the React Native website are:

- The apps you are building with React Native aren't mobile web apps because React Native uses the same fundamental UI building blocks as regular iOS and Android apps
- React Native uses the same design as React, letting you compose a rich mobile UI using declarative components

Documenting the pros and cons of a navigation library should be done with these promises in mind 

### Discussion points
For a navigation library to keep the first promise it must use the same fundamental navigation building blocks as regular iOS and Android apps. React Navigation breaks this promise. Although it uses `UIViewControllers`, thanks to `react-native-screens`, it doesn’t use the `UINavigationBar`, for example. The `UINavigationBar` is a fundamental navigation building block. One of its many jobs is displaying titles, large or small, and animating them as screens are popped and pushed.

To keep the second promise, a navigation library must provide declarative components for constructing its UI. React Native Navigation breaks this promise because it doesn’t have any components at all (apart from `SharedElement`). All of its UI elements, like headers and buttons are configured through static options and global function calls. React Navigation also relies on static options because, without portals, it owns the UI where the headers and buttons live.

React Native already comes with a `Modal` component that uses the underlying native API on both platforms. So why then do React Navigation and React Native Navigation come with their own Modal APIs that break both the promises?

The [Navigation router](https://grahammendick.github.io/navigation/documentation/native/hello-world.html) is the only navigation library that keeps both the promises of React Native. It uses the underlying native APIs on Android and iOS and you compose all its UI using components. That’s why, although it’s a new library, it deserves a mention in the documentation.

**Comment by brentvatne** [comment]
@grahammendick - fwiw, there is some work in progress on react-native-screens to also support UINavigationController/Bar in a way that is compatible with a subset of the existing stack navigator API

**Comment by grahammendick** [comment]
@brentvatne  That sounds exciting. Are you also planning on supporting the `UINavigationBar` so you can use the title animation built into iOS?

**Comment by kelset** [comment]
I am not sure I'm following - what's the subject to be discussed here? That this navigation router should be mentioned in the docs? 🤔

**Comment by brentvatne** [comment]
@grahammendick - yup!

**Comment by grahammendick** [comment]
@brentvatne nice, that's huge news

**Comment by grahammendick** [comment]
@kelset The aim is find an even-handed way to talk about navigation libraries in the new "Navigating Between Scenes" documentation.

**Comment by kelset** [comment]
Ok. So it is not really a proposal about react native. It's literally just about a documentation page - I'll read through your links but I have really an hard time understanding why this should be kept open here and not, let's say, as an issue in the react-native-website docs 😕

**Comment by grahammendick** [comment]
It started life as a [PR on the react-native-website](https://github.com/facebook/react-native-website/pull/1086). @osdnk recommended we move it here

**Comment by kelset** [comment]
Yeah - and after reading the whole conversation I'm ever more convinced that this repository is not the right place (I'll speak with @osdnk). It's not about anything technical per se (ex. detailing a new approach towards stack navigator) nor anything else that we want to cover in this repo - but simply about listing libraries in a fair manner in a documentation page.

What I'd recommend is to, following all the inputs you got in the PR (about ex. things to evaluate when talking about any given navigation library, and all the things pointed out by [Satya](https://github.com/facebook/react-native-website/pull/1086#pullrequestreview-260419046)) to open an issue in the react-native-website that could be used as source material for when that documentation page will be re-written, since this rewrite will happen at some point according to Michał's comment. Something along the lines of "Compendium of React Native navigation libraries".

**Comment by osdnk** [comment]
Hello and terribly sorry for that. I think I was right pointing that this PR is not a good place for discussion, but it appears that this place neither. Let's move to website issues! My bad!

**Comment by osdnk** [comment]
btw, @grahammendick, your lib looks impressive. I appreciate it! 
Also, I'm under impression of your native code. I wonder if you considered writing it in a bit more 'modular' way. Here we have a big repo which might be slitted into smaller ones. Then I could imagine reusing part of your work in React Navigation.

**Comment by grahammendick** [comment]
Thanks @osdnk . The Navigation router is split into three packages:the JavaScript layer (`navigation`), the React layer (`navigation-react`), and the React Native layer (`navigation-react-native`). This modular design is why the Navigation router can run your React Native code on the web. You remove the `navigation-react-native` package and replace it with `navigation-react-mobile`.

Or were you just talking about the native code inside the `navigation-react-native` package? This layer is very thin already. Which bit do you think you could reuse in React Navigation?

**Comment by kelset** [comment]
(closing because of reason above, feel free to keep your conversation going)
