### ISSUE TITLE
Has anyone implemented in-app Updates library?? having trouble implementing into native.

### ISSUE THREAD

**Issue by liljosi** [react-native-community/discussions-and-proposals#148]
# No Template

👉 Please follow one of the issue templates provided by the repo - if you are seeing this message, it means you haven't.

If you don't follow the issue template, we may immediately close it.

**Comment by pvinis** [comment]
You mean like codepush? Maybe an explanation would be helpful.

**Comment by liljosi** [comment]
> You mean like codepush? Maybe an explanation would be helpful.

It's the new library that google added to play-core. It's called in-app Updates. Basically when you open the app it automatically requests info about if an update is needed for the app, opens UI for the user and you have two options, immediate update or flexible, the flexible option the user can still use the app while the update is being downloaded. The problem here is that i'm not sure it's compatible with react native yet. Don't know, was looking for some advice.

**Comment by kelset** [comment]
This conversation seems to not be fit for the D&P repo, it seems to be more appropriate on StackOverflow
