### ISSUE TITLE
[Proposal] an android implementation for 'actionsheet'

### ISSUE THREAD

**Issue by vinnyA3** [react-native-community/discussions-and-proposals#149]
### Introduction

RN solution for `actionsheet` on android.

### The Core of It

RN provides an API to interact with iOS's **actionsheet** ([react native iOSActionsheet](https://facebook.github.io/react-native/docs/actionsheetios)).  Even though the name **actionsheet**  is iOS specific, it would be nice to include an implementation like this for android (using [BottomSheetDialog](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialog.html)).  I would argue that both **actionsheet** and **bottomSheetDialog** are one in the same--as far as functionality goes.

[**P.S**]
I wanted to create an issue for discussion before I created a proposal / implementation; I hope this is okay!

### Discussion points

* Implement **actionsheet** functionality on android using [BottomSheetDialog](https://developer.android.com/reference/android/support/design/widget/BottomSheetDialog.html)

**Comment by AndreiCalazans** [comment]
Yes, that's a good idea. And it has already been done. https://github.com/expo/react-native-action-sheet/pull/105

Lean Core's plan is to remove IOSActionSheet from the core React Native repo. As you can see here https://github.com/facebook/react-native/issues/23313#issuecomment-468877275
https://github.com/facebook/react-native/issues/23313

**Comment by kelset** [comment]
Thanks @AndreiCalazans for the context, closing this as it's not really a broad discussion about react-native itself.

It seems to me that the current solution would be to use expo's implementation until the Lean Core repo is created.
