### ISSUE TITLE
Supporting font weight on Android

### ISSUE THREAD

**Issue by PierreCapo** [react-native-community/discussions-and-proposals#150]
### Introduction

Having the ability to use the font weight API on Android like on iOS.

### The Core of It

Right now there is an inconsistency between iOS and Android for setting font weights (except for bold):
- On iOS, you can use `fontWeight: "black"`;
- On Android, you need to do `fontFamily: "MyFontFamily-Black"`;

I believe this inconsistency should be fixed and the font weight API is more natural especially for a lot of developers coming from the web's ecosystem.

### Discussion points

- Do you agree that this behaviour of having font-weight enabled on Android is something wanted?
- Should we tackle that by working on the native side, and implementing a getFontFamily function in [ReactBaseTextNode.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactBaseTextShadowNode.java) file? 
- Or should we work on the JavaScript side and change the font family according to the font weight for Android?

Our react-native team can work and dedicate time to open a PR on that issue.
Thanks in advance

**Comment by kelset** [comment]
Given that this is a precise feature, and not a bigger discussion, I'd suggest that you move forward in working on the implementation 🤗

> Our react-native team can work and dedicate time to open a PR and that issue.

It would be great to keep this conversation going in the PR :)

**Comment by kelset** [comment]
(closing this as the natural follow up should be in the PR)
