### ISSUE TITLE
Support for use_frameworks! - works?

### ISSUE THREAD

**Issue by annakocheshkova** [react-native-community/discussions-and-proposals#156]
Hello there react-native community! Greetings from App Center :slightly_smiling_face:.

I am not sure what is the best place for my question but you all (@thymikee especially) helped us so much during react-native 0.60 transition so I thought I'd post my issue here.

We have a question concerning "Better support for use_frameworks!" in your 0.61 release. Does that include our case or still not quite?
We have a dynamic AppCenter framework linked to the static AppCenterReactNative one, and based on my latest tests, it still doesn't work with `use_frameworks!`. 

I was having the impression that it is partially fixed in your new release, is that so? We haven't found any more documentation on this. Thanks!

Here's the related issue in the main repo: https://github.com/facebook/react-native/issues/26588

**Comment by rickhanlonii** [comment]
Hey @annakocheshkova, thanks for reaching out!

Let's continue the discussion on your original post, this repo is typically reserved for long form discussions and proposals about the core framework 👍
