### ISSUE TITLE
Expo DevTools is running at http://localhost:19002 Opening DevTools in the browser... (press shift-d to disable) Error: spawn cmd ENOENT     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)     at onErrorNT (internal/child_process.js:415:16)     at process._tickCallback (internal/process/next_tick.js:63:19) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! @ start: `expo start` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the @ start script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.  npm ERR! A complete log of this run can be found in: npm ERR!     C:\Users\Bhaskar\AppData\Roaming\npm-cache\_logs\2019-09-27T16_04_38_327Z-debug.log PS C:\Users\Bhaskar\Desktop\SDproject\01\HelloProject>

### ISSUE THREAD

**Issue by BhaskarAcharya19** [react-native-community/discussions-and-proposals#157]

**Comment by BhaskarAcharya19** [comment]
I have getting trouble in running the program. Any one can help me out about this problem.

**Comment by rickhanlonii** [comment]
Hey @BhaskarAcharya19, thanks for submitting! 

Unfortunately this repo is for discussions of React Native core architecture, it is not a help forum. Going to close this but please feel free to post your question on StackOverflow for help!

**Comment by Nitesh121** [comment]
Opening DevTools in the browser... (press shift-d to disable)
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `expo start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nitesh\AppData\Roaming\npm-cache\_logs\2019-10-19T04_56_08_999Z-debug.log
