### ISSUE TITLE
Can Date be included in JSC?

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [react-native-community/discussions-and-proposals#158]
### Introduction

Can we have Date in JSC ?
### The Core of It

I wanted to get datetime string. But JSC new Date() returns NaN.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
