### ISSUE TITLE
react-nativ-camera -- Accessing the java files functionalities

### ISSUE THREAD

**Issue by shreyakamoji96** [react-native-community/discussions-and-proposals#159]
Hiii
Using react-native-camera library module, can we get the live frames of the camera preview in JS. As the camera is opened each frame should be captured at the JS side in the form of byte array or base64 ??

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question about react-native-camera - so I would suggest opening an issue there or ask on [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
