### ISSUE TITLE
react-native components norm/standerd 

### ISSUE THREAD

**Issue by tonmanayo** [react-native-community/discussions-and-proposals#16]
So I am still fairly new, and one of the most frustrating things I have had to deal with so far is: When using community components there is no standard.

For example, checking if a user has permissions on the react-native-camera component compared to the react-native-contacts component.

For one there is a react-native android way to check permissions and then there is no lib for IOS, but its just expected that IOS doesn't need to be checked and will be automatically prompted.
Would be great to be able to check things the same way on both platforms

**Comment by kelset** [comment]
👋 Tony,
thanks for the feedback. I don't think this discussion belongs in this repo mostly for one reason: there is no "best practise" around this kind of things.

React Native tries to act like a glue towards the two native platforms, but needs to adapt to whatever approach the native base decides to follow - and, sadly, for some scenarios like the permission example you describe, it's up to the Android team to decide their approach. Similarly for iOS things.

That said, notice also that React is a young approach to code: the best practises are still defined and changed from time to time. The React team, as far as I can remember, is [trying now to create](https://twitter.com/sophiebits/status/1027066902156210177?s=09) some documentation of their own best practises and approaches.

I hope this helps a bit :)

**Comment by tonmanayo** [comment]
@kelset thanks for the reply, I do understand that react-native is a fairly new framework, but I still do think there could be a guideline when creating new components for the framework. Example... creating a component like the Camera or Contacts, both IOS and Android will need permissions from the user to use these components. 

Anyways sorry for posting it in the wrong place, where should I be having this discussion?
