### ISSUE TITLE
Getting a rgb value of each pixel in an image or getting pixels based on the coordinates given 

### ISSUE THREAD

**Issue by shreyakamoji96** [react-native-community/discussions-and-proposals#161]
Hii,
Is there any way to get the RGB value of each pixel in an image or getting pixel value based on coordinates given ?? So that I can convert only that part of the image to some other color or change that particular pixel value

**Comment by rickhanlonii** [comment]
Hey @shreyakamoji96, thanks for submitting you question!

Unfortunately, this repo is not a help forum. We recommend posting help questions to [StackOverflow](https://stackoverflow.com/questions/tagged/react-native).
