### ISSUE TITLE
Drag Items From Flatlist and Drop In The Box

### ISSUE THREAD

**Issue by wifirevaithi** [react-native-community/discussions-and-proposals#164]
Hi, I Need To Implement A Activity Like,A Square In The Top and In The Bottom There Is A Flatlist Contains Image and text,user Can Drag The Flatlist Item And place In The Square.I Didn't How Can I Drag A Flat List Item From That List..Please Help I'm New To react native

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
