### ISSUE TITLE
Leaflet support for React Native

### ISSUE THREAD

**Issue by hussainahmad** [react-native-community/discussions-and-proposals#167]
### Introduction

As we all know Google is charging for the google Map, so many companies switched from google map to alternative like Leaflet . [Leaflet](https://leafletjs.com/) is the leading open-source JavaScript library for mobile-friendly interactive maps.  I found there is [react-native-maps](https://github.com/react-native-community/react-native-maps/) which is good but it required google configuration, which if  you use leaflet not required. 

### The Core of It

there is [React Leaflet](https://react-leaflet.js.org/) to use map in React JS but this we can't use in React native according to [this](https://github.com/PaulLeCam/react-leaflet/issues/26)

### Discussion points

I found there is [react-native-webview-leaflet](https://github.com/reggie3/react-native-webview-leaflet) to support leaflet in react native. I thanks to @reggie3 for this library. but there is a minimal support in this. I think it will be great for React native Community if leaftlet support this.

**Comment by cpojer** [comment]
Hello @hussainahmad. This is not the right place for this discussion – please discuss it directly on the leaflet repository. This repository is only used for discussing React Native itself.

**Comment by hussainahmad** [comment]
thanks
