### ISSUE TITLE
is there already an JSI for android v8 now?

### ISSUE THREAD

**Issue by ping996** [react-native-community/discussions-and-proposals#168]
does the JSI are only for JSC now? is there already an JSI for android v8 latest version now?

**Comment by Kudo** [comment]
@ping996 JSI is just an abstract interface and not restricted to any VM implementations.
Currently, JSC, Hermes and react-native-v8 implement JSI, so it should be okay for you to run JSI on RNV8.

**Comment by ping996** [comment]
does the react-native-v8 is available for every one?

**Comment by ping996** [comment]
I have found your project of rn-v8, has it used in some project or just only your experiment?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

(that said, you can also refer to https://github.com/Kudo/react-native-js-benchmark for more info on this)
