### ISSUE TITLE
Report the regular expression exception after i exactly  did according to the official website on my windows

### ISSUE THREAD

**Issue by yl754980640** [react-native-community/discussions-and-proposals#170]
Report the regular expression exception after i exactly  did according to the official website on my windows：“Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class”；
      The problem was solved in the following way“https://blog.csdn.net/weixin_44369568/article/details/102917156”

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
