### ISSUE TITLE
Issue related with the deleting of node_modules folder 

### ISSUE THREAD

**Issue by rajneesh44** [react-native-community/discussions-and-proposals#179]
If I have many dependencies in my react-native project and getting an unresolvable error and if remove the ```node_modules``` folder, and install it again, will it automatically install all the dependencies and required packages or I have to again download them, individually?
Help Please?
I am new to react-native.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
