### ISSUE TITLE
Consolidate CLI Options to Run App in Release Mode

### ISSUE THREAD

**Issue by kevinvangelder** [react-native-community/discussions-and-proposals#185]
### The Core of It
To run the app in release mode: 
iOS: `react-native run-ios --configuration Release`
Android: `react-native run-android --variant=Release`

### Discussion points
React Native is all about reducing the friction surrounding developing apps for multiple platforms, yet every time I need to run the app on my simulator/emulator in release mode I have to look it up because they're different and not easy to remember. It would be great if they both could use the same arguments.

### Impact
Minor, developer convenience

**Comment by TheSavior** [comment]
I don't think this is quite a general framework level proposal and is more a bug / feature request for the CLI. In fact, I've made this specific request previously! :) 

I'd recommend chiming in on the issue over there. https://github.com/react-native-community/cli/issues/179

It looks like they agree and just need someone to send a PR!
