### ISSUE TITLE
When would the new RN 62 version be a release?

### ISSUE THREAD

**Issue by sarykemmoun** [react-native-community/discussions-and-proposals#194]
Hello.
I've upgraded my react native app to v0.62.0-rc.1 but now I realize that it's only a pre-release version.
I don't want to deliver a pre-release version so I wonder if to downgrade to 61.5 or to wait for 62.
How can I know when would 62 be the latest release?

Thanks.

**Comment by TheSavior** [comment]
You can follow along the progress of the 0.62 release in the issue at [`react-native-community/releases`](https://github.com/react-native-community/releases/issues/157).
