### ISSUE TITLE
Critical video by TechLead

### ISSUE THREAD

**Issue by brodybits** [react-native-community/discussions-and-proposals#198]
https://www.youtube.com/watch?v=NxJCSI7a8wk

Unfortunately I really do not know how to respond to this video. It does link to some major issues from major companies such as Shopify, AirBnB, and Dropbox. Any ideas?

**Comment by cpojer** [comment]
This YouTube channel is focused on generating views to upsell interview training programs. I wouldn’t read too much into it beyond “React Native is excellent” generating fewer views than the title that was chosen.

The information about Facebook’s usage of React Native is factually incorrect. While Marketplace and Dating are some of the biggest products using RN, there are more than 750 screens in both Facebook for Android and iOS as well as several standalone apps primarily built using RN.

**Comment by brodybits** [comment]
Thanks @cpojer for the information about the Facebook screens and standalone apps. Is this documented anywhere?

I did find the nice React Native showcase in <https://facebook.github.io/react-native/showcase> 🚀

**Comment by cpojer** [comment]
Hey @brodybits,

we haven't updated the showcase in many years and are planning on doing so soon!

I can say the team and adoption at Facebook have both been growing at a healthy pace. There is no new information right now about Facebook's use of RN beyond my comment above.

**Comment by joshhogg** [comment]
Just throw this in here, showing Shopify still fully supports RN:

https://engineering.shopify.com/blogs/engineering/react-native-future-mobile-shopify
