### ISSUE TITLE
Documentation Translate for React Native

### ISSUE THREAD

**Issue by ezranbayantemur** [react-native-community/discussions-and-proposals#203]
Hello everyone, best regards from Turkey!

I wish to contribute React Native documents as a Turkish language support. But I don't know how to do it. ReactJS document has language support and that's been really helpful. 

Someone has an idea how can I support?

Plus, would you help this with your language?

**Comment by kelset** [comment]
👋 there!
Thanks for your offering - the documentation lives in a dedicated repo -> https://github.com/facebook/react-native-website

It's backed by Docusaurus so I'm not sure if translations/multilanguage are supported. I would recommend that you open an issue in that repo (https://github.com/facebook/react-native-website/issues) and ask there how to proceed as this is not the right place :)

**Comment by ezranbayantemur** [comment]
@kelset Okay I will look forward to it, thank you so much!
