### ISSUE TITLE
Accessibility for visually impaired developers

### ISSUE THREAD

**Issue by Manodiestra** [react-native-community/discussions-and-proposals#208]
# Accessibility for visually impaired developers

### The Core of It

The react native framework is difficult to debug for visually impaired developers. 

### Discussion points

As a visually impaired developer, I rely on customizable tools to be able to see outputs such as errors and warnings. I use a terminal emulator with large font and contrasting colors. When developing in react native, errors are not always displayed in the terminal where the server is being run.
At times I must read what is on the mobile screen. The fonts are small, and the color choices are terrible. For example, the white font on a bright yellow background with small font for Warnings is COMPLETELY illegible for me. I'm sure this is uncomfortable for anyone who can see well, too. Please use a dark font on a light background, or light font on a dark background. I have searched my project directories and online for a solution to change the colors for the warning messages, but haven't been able to find a solution.
I love using react native, but if you are going to limit some messages to only populating on a mobile screen and not in the terminal for the development server, please make it accessible. However, in my opinion, it would be better to just have the errors populate in the terminal where the server is run.
Thank you for your consideration on this topic. Not everyone who has a development job has 20/20 vision. Most visually impaired people like working for a living, rather than living on government welfare.

**Comment by thymikee** [comment]
I a lot of what you have troubles with is something that @rickhanlonii is working on currently, as a part of LogBox and Metro improvements.

**Comment by lucasbento** [comment]
Hey @Manodiestra, would you be willing to discuss this further perhaps through a call? I would love to improve the experience around this.

**Comment by Manodiestra** [comment]
Sorry for the late reply. Yeah, I would love to help out any way I can. You
can give me a call any time at 435 777 3975. Note that my phone selectively
screens calls for spam without telling me until after the fact, so if you
don't get through send me a text.

**Comment by lucasbento** [comment]
@Manodiestra can you send me an email at lucas.silva9w@gmail.com? then we can work something out regarding the call.

If it's easier you can provide your email and I'll get in touch!

**Comment by fabriziobertoglio1987** [comment]
I also prefer to see the log errors in the terminal. The big different I noticed is between  the latest react-native versions and the older ones. Old versions of react-native do not display those logs in the terminal, but you can run commands like `yarn react-native log-android` or `yarn react-native log-ios` to display those errors in a separate terminal window/tab. Additionally I wrote my own bash script to fiter adb errors. I called it `adbgrep`

```
adb logcat | grep -P $1
```
I can log error message in android with `adbgrep "TESTING::"`. 

```java
import android.util.log

String my_var = String.valueOf(variable);
Log.w("TESTING:: my_var: ", my_var);
```
