### ISSUE TITLE
support default appKey in AppRegistry.runApplication

### ISSUE THREAD

**Issue by isee15** [react-native-community/discussions-and-proposals#211]
### Introduction

My app received dynamic parameter to open React Component。
With old version app， the component key maybe not exist。
So we need provide a default component key to show a React Componet， give some tips for app user。

### The Core of It

runApplication(appKey: string, appParameters: any): void {
    if (appKey !== 'LogBox') {
      const msg =
        'Running "' + appKey + '" with ' + JSON.stringify(appParameters);
      infoLog(msg);
      BugReporting.addSource(
        'AppRegistry.runApplication' + runCount++,
        () => msg,
      );
    }
    invariant(
      runnables[appKey] && runnables[appKey].run,
      `"${appKey}" has not been registered. This can happen if:\n` +
        '* Metro (the local dev server) is run from the wrong folder. ' +
        'Check if Metro is running, stop it and restart it in the current project.\n' +
        "* A module failed to load due to an error and `AppRegistry.registerComponent` wasn't called.",
    );

    SceneTracker.setActiveScene({name: appKey});
    runnables[appKey].run(appParameters);
  },

### Discussion points

when 
runnables[appKey] && runnables[appKey].run 
is false，

give a default appKey to runApplication

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
