### ISSUE TITLE
Multilingual screen-reader

### ISSUE THREAD

**Issue by Schedulaar** [react-native-community/discussions-and-proposals#212]
### Introduction

Screen readers like TalkBack and VoiceOver help visually impaired people to work with their smartphones. We build an app (https://github.com/integreat/integreat-react-native-app) for newcomers, like migrants and refugees. Therefore we have a high demand on internalization features: On some screens we display UI elements in the device's system language (like menu buttons, navigation, etc.) and content elements in some other content language.

Currently it's not possible to tell the screen reader in which language to read out single components, it mostly falls back to the device's system language or tries to detect the language automatically (which often happens to be wrong for similar words).

### The Core of It

It would be nice if we could tell the screen reader which locale a `Text` is written for by setting an accessibility property.

### Discussion points

Android introduced `LocaleSpan` to do exactly that (https://developer.android.com/reference/android/text/style/LocaleSpan). I am unsure about anything comparable in iOS.

**Comment by TheSavior** [comment]
As this isn't really a question of "should we do this" and more of a "how do we do this", let's keep the discussion on the issue in the React Native repo for this: https://github.com/facebook/react-native/issues/28328

**Comment by kseverinsen** [comment]
[facebook/react-native#28328](https://github.com/facebook/react-native/issues/28328) seems to be closed.
The issue is not resolved, so are there any updates on changing locale for VoiceOver?
