### ISSUE TITLE
Add ellipsizeMode to TextInput

### ISSUE THREAD

**Issue by ruimfernandes** [react-native-community/discussions-and-proposals#214]
### Introduction

Hi everyone!
I'm struggling with `TextInput` text truncation and I want to suggest the implementation of `ellipsizeMode` to `TextInput` just like `Text` has - https://reactnative.dev/docs/text#ellipsizemode. 

### The Core of It

`TextInput` truncates the text when it's too big but there's no options available to customize that text's truncation. I would like to be able to truncate the text on the left side, just like i have on the screenshot below.

![textInput](https://user-images.githubusercontent.com/18558899/77660980-ee67f780-6f71-11ea-917e-08460287b296.png)

Another awesome thing would be the possibility of setting the truncate behaviour on focus (at the moment it only trims the text on the left side but would be awesome if we could also set the 3 dots on the left side while typing)

### Discussion points

- Add `ellipsizeMode` to `TextInput`
- Be able to set the truncate behaviour while `TextInput` is focused

**Comment by TheSavior** [comment]
This is a very specific feature request and should live in the regular React Native repo instead. Could you open an issue there? 

We use this repo for bigger sweeping architectural or community changes.

**Comment by ruimfernandes** [comment]
@TheSavior their issues page forwards me to this repo for stuff related to Discussions and Proposals - https://github.com/facebook/react-native/issues/new/choose

Should I create it as bug? Doesn't seem correct 🤔

**Comment by jimjacob29** [comment]
any solutions available for this @ruimfernandes

**Comment by ruimfernandes** [comment]
Not that I'm aware @jimjacob29

**Comment by skizzo** [comment]
Such a basic feature and no solution in sight :(

**Comment by Kommandat** [comment]
Bump, it would also be great to get the `numberOfLines` prop working on iOS as well

**Comment by thomasdiben** [comment]
Up, would love to see that add indeed 🤓
