### ISSUE TITLE
React Native : Android build issue while upgrading project from 0.59.9 to 0.62.1

### ISSUE THREAD

**Issue by aashish-pixere** [react-native-community/discussions-and-proposals#216]
I am facing issue regarding android build creation when I converted my app from react native version 0.59.9 to  0.62.1.

Error report below : 

 Invariant Violation “Project name” hast not been registered. This can happen if: 
*Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and `AppRegistry.registerComponent` wasn’t called. 

![Screenshot_1586847153](https://user-images.githubusercontent.com/22632227/79194701-a50d1880-7e4a-11ea-8045-b3f805cee9e1.png)

====================================== 
My code in index.js file:
———————————

  import start from './App';
start();

=====================================
My code in App.js file : 
——————————

const start = () => {
    registerScreens();
    Navigation.events().registerAppLaunchedListener(() => {
        Navigation.setRoot({
            root: {
                component: {
                    id: FirstScreen,
                    name: FirstScreen,
                    options: {
                        layout: {
                            orientation: ['portrait']
                        }
                    }
                },
            },

        });
    });
}

export default start;

=============================================

React native configuration below :
————————————————

System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 26.57 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.11.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3, 29.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom, android-28 | Google Play Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_222 - /usr/bin/javac
    Python: 2.7.10 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.1 => 0.62.1 
  npmGlobalPackages:

- Please let me know what going wrong in this and how can i access to App.js file in react native version 0.62.1 without AppRegister method like as i was doing in react native version 0.59.9

**Comment by thymikee** [comment]
Hey! This repo is for discussions around how to improve React Native. For upgrade support, please visit this repo: https://github.com/react-native-community/upgrade-support
