### ISSUE TITLE
Support yarn workspaces with hoisting

### ISSUE THREAD

**Issue by ivosabev** [react-native-community/discussions-and-proposals#22]
Currently we need to use `nohoist` is there any plan to introduce support for hoisting?

**Comment by kelset** [comment]
👋 I don't think this discussion belongs in this repo - you are asking for a precise technical feature to be implemented, I believe it fits better in [https://discuss.reactjs.org/](https://discuss.reactjs.org/)

**Comment by ivosabev** [comment]
I suspect it is more than a technical issue, as it will require some changing of the inner workings fo the metro builder, correct me if I am wrong?
