### ISSUE TITLE
React native access to USSD

### ISSUE THREAD

**Issue by lylest** [react-native-community/discussions-and-proposals#221]
Hello hi there
I decided to open this issue as the recommendation may be a proposal seeing if we can build a module that can access USSD operations 
This is because i have spent days searching on this issue because i wanted to build app that can access USSD but i failed to find a convenient answer to my problem
but i believe i am bot the only one who has faced this problem may be it is the time we can actually solve this

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

**Comment by lylest** [comment]
Why are you closing it
