### ISSUE TITLE
Image from pixel array (base64, UInt8ClampedArray, ...)

### ISSUE THREAD

**Issue by mrousavy** [react-native-community/discussions-and-proposals#222]
### Introduction

Hi! Recent UI/UX design trends lead to implementing unique loading indications for resources. One of which is the [blurhash algorithm](https://blurha.sh). It is an algorithm, that encodes an Image to a short blurhash string (something around 25 chars, depending on size) ideally on the server side, which can then be decoded on the client side to display a blurred image while the actual image is still downloading. The website gives a better understanding than I do, check it out!

### The Core of It

The problem here is, the `decode` function returns a raw pixel data array of the blurred image it should represent (`UInt8ClampedArray`). Using this pixel array, one should be able to display it as an Image source. On the web this is achieved using canvas, on Node.JS applications you can use node-canvas. But on react native there is no way to initialize an Image using a raw pixel data array. (At least none that I'm aware of)

### Discussion points

It might be debatable how many use cases there are for this, but I could think of a few besides from the blurhash algorithm.
* Custom downloading: When you want to download an image from your backend yourself instead of using an image URL.
* Pixel manipulation: when you want to paint pixels another color yourself
* Image processing libraries like AI: some libraries I have found work with raw pixel arrays aswell, some don't.

**Comment by radko93** [comment]
I think the way it should be resolved is that you should use native components for this, there are Swift or Kotlin implementation which you could use. Decoding and then passing image data over bridge is not perfect.

**Comment by mrousavy** [comment]
@radko93 Is it possible to extend the base `<Image>` component without creating a separate component for this?

**Comment by TheSavior** [comment]
I think this is out of scope for the built in Image component. I recommend this functionality be built as a 3rd party library.
