### ISSUE TITLE
UIManager.showPopupMenu change background Color

### ISSUE THREAD

**Issue by skgonh08** [react-native-community/discussions-and-proposals#224]
Hi,
Can we change the background color of UIManager.showPopupMenu popup menu? I'm building an app which has dark theme. By default, the popup appears with a white background.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
