### ISSUE TITLE
Add support for deno

### ISSUE THREAD

**Issue by xyz0405** [react-native-community/discussions-and-proposals#225]
### Discussion points

Is your feature request related to a problem?
As deno is going to have its 1.0 release at May 13 (https://github.com/denoland/deno/issues/2473#issue-453631188), will React Native add support for deno?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. There is currently no plan to support deno in any form, that I am aware of. Myabe you could try opening a PR against the main repo to introduce a basic support to it and see what the team thinks?
