### ISSUE TITLE
Stop transform some es2015+ syntax that supports natively since RN@0.60.x

### ISSUE THREAD

**Issue by retyui** [react-native-community/discussions-and-proposals#228]
### Introduction

Currenly [metro-react-native-babel-preset](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js) transform all ES2015+ syntax into ES5. 

**Before**
```js
const a = {...{a:1}};

let sum = 0; 

for(const a of [1,2,3]){ 
	sum = sum + a; 
}
```

**After**
```js
  function ownKeys(object, enumerableOnly) { /* lots of code */ }
  function _objectSpread(target) { /* lots of code */ }

  var a = _objectSpread({}, {
    a: 1
  });

  var sum = 0;

  for (var _i = 0, _arr = [1, 2, 3]; _i < _arr.length; _i++) {
    var _a = _arr[_i];
    sum = sum + _a;
  }

  _reactNative.Alert.alert('Check: spread & for of', JSON.stringify({
    a: a,
    sum: sum
  }, null, 2));
```
To test use [http://localhost:8081/index.bundle?platform=android&dev=true&minify=false](http://localhost:8081/index.bundle?platform=android&dev=true&minify=false)

### The Core of It

Create a new RN project:
```sh
react-native init testEs6
```

Add the next code to `index.js`

```js

import {Alert} from 'react-native';

eval('a = {...{a:1}};');
eval("sum = 0; for(const a of [1,2,3]){ sum = sum + a; }");

Alert.alert('Check: spread & for of',JSON.stringify({a,sum},null,2));
```

And finally, just run it on a device to test:

![image](https://user-images.githubusercontent.com/4661784/81588351-0c25da80-93c1-11ea-98f8-c587b9e2f935.png)

### Discussion points

As you see above eval of ES2015+ syntax work without errors

Do we still have to transform this syntax into ES5?

Or can we create a "modern" preset and apply it for RN@0.60.x and above projects?

```js
// metro-react-native-babel-preset
const getPreset = () => {
  const {version} = require('react-native/package.json');

  if(version > "0.60.x"){ // abstract check 
    return morednPreset;
  }

  return legacyPreset;
}
```

**Comment by newyankeecodeshop** [comment]
There was some progress made on this with https://github.com/facebook/metro/pull/515 but that has stalled due to an issue with some internal Facebook projects. Hopefully things can get on track for this feature soon. I share your desire to stop including so many unnecessary plugins.

**Comment by kelset** [comment]
I think it's an interesting shoutout - not sure if this is the place to discuss it though - as correctly pointed out by @newyankeecodeshop it seems to fit more in the Metro repository.

**Comment by newyankeecodeshop** [comment]
See https://github.com/facebook/metro/pull/597 for an alternative implementation for this.

**Comment by kelset** [comment]
let's close this in favour of that metro PR
