### ISSUE TITLE
Use Expo CLI in the Quick Start section of the docs

### ISSUE THREAD

**Issue by fson** [react-native-community/discussions-and-proposals#23]
## Summary

We propose changing the Quick Start docs to use the `expo-cli` package instead of `create-react-native-app`.

- **Expo CLI is a tool based on CRNA, made by the same team**
- **It has all the same features, plus some additional benefits (see below)**
- **Like CRNA, Expo CLI does not require an Expo user account**
- **The `create-react-native-app` command will continue to work**

## Background

Currently the Quick Start section of docs shows how to get started using Create React Native App (CRNA). In the past few months, I and my colleagues at Expo have been working on Expo CLI, which aims to bring CRNA to the next level. Expo CLI builds on and extends CRNA.
Expo CLI follows the same philosophy as CRNA (from https://github.com/react-community/create-react-native-app/blob/master/README.md#philosophy):

- **Minimal "Time to Hello World"**: Create React Native App should reduce the setup time it takes to try building a mobile app to the absolute minimum, ideally on par with React web development (especially as seen with Create React App).
- **Develop on Your Device**: It should be easy to develop on a physical device when you want to test how your app feels and responds to inputs.
- **One Build Tool**: If you just want to get started with React Native, you shouldn't need to install Xcode, Android Studio, NDKs, or mess with environment variables.
- **No Lock-In**: You can always "eject" to your own build setup if you need to write custom native code or modify how your app is built.

In addition to everything offered by CRNA, Expo CLI also has these additional features:

- **Web-based user interface**: in addition to the CLI, there's a GUI where you can view logs, launch the app on your devices or simulators, and publish updates.
- **Standalone app builds**: you can build IPA and APK packages for deploying to App Store and Play Store without using Xcode or Android Studio.
- **Publishing**: you can push updates to your deployed apps and optionally publish your app to Expo.io.
- **Tunnel**: your physical device doesn’t need to be in the same wi-fi as your computer to be able to develop using it.
- **Optional user accounts**: logging in allows listing all your projects in development in the Expo app without having to scan any QR codes and enables additional features like standalone builds. However, just like CRNA, Expo CLI can also be used without a user account.

All apps originally created using CRNA also work with Expo CLI and like before, will be able to use Expo APIs in addition to core React Native APIs.

## Why
- **Just one tool to learn:** previously developers would start with CRNA and then switch to exp or XDE for additional features like standalone builds. Expo CLI is as easy to get started with as CRNA, but also supports everything previously offered by these separate tools.
- **Less confusing options**: CRNA apps have always been loaded using the Expo app and able to use the Expo APIs in addition to the core React Native APIs. Users are sometimes [confused](https://github.com/react-community/create-react-native-app/issues/153) about the differences between plain React Native, CRNA and Expo apps created with tools like exp or XDE. Installing the `expo-cli` package will make it clearer the additional functionality is provided by Expo.
- **Developer experience:** as described above, Expo CLI is ahead of CRNA in terms of features and developer experience, and we’re continuously improving it.
- **Maintenance**: having these two projects as separate codebases requires more maintenance and CRNA has previously falled behind because of this. A single codebase helps us keep it up to date and fix issues as fast as possible.
## How

**What will happen to the `create-react-native-app` package?**
The `create-react-native-app` tool is used to create new CRNA projects. The old way to create a project was:

    $ npm install -g create-react-native-app
    $ create-react-native-app my-app
    $ cd my-app/
    $ npm start

After the migration, new projects will be created with `expo init`:

    $ npm install -g expo-cli
    $ expo init my-app
    $ cd my-app/
    $ npm start

Additionally, to ease the migration and to ensure that all existing resources and examples using CRNA will keep working in the future, we’ll make `create-react-native` delegate to Expo CLI by default (unless invoked with the `--scripts-version` or `--reason` flags):

    $ create-react-native-app my-app
    This command requires Expo CLI.
    Do you want to install it globally [Y/n]?
    Installing the package 'expo-cli'...
    ? Choose a template: (Use arrow keys)
    ❯ blank
      The Blank project template includes the minimum dependencies to run and an
      empty root component. 
      tabs
      The Tab Navigation project template includes several example screens. 

**What will happen to existing projects and the `react-native-scripts` package?**
When upgrading from `react-native-scripts`, users will need to change the scripts in `package.json` to use `expo` instead of `react-native-scripts`.  The scripts were previously created like this by default:

      "scripts": {
        "start": "react-native-scripts start",
        "eject": "react-native-scripts eject",
        "android": "react-native-scripts android",
        "ios": "react-native-scripts ios",
        "test": "jest"
      }

This needs to be changed to:

      "scripts": {
        "start": "expo start",
        "eject": "expo eject",
        "android": "expo start --android",
        "ios": "expo start --ios",
        "test": "jest"
      }

After this the `react-native-scripts` can be removed from `devDependencies`. Running any of the scripts will install `expo-cli`, unless it’s already installed.

To ease the migration for existing users, we will publish an updated version of `react-native-scripts` that delegates commands like `start`, `ios` , `android`, and `eject` to corresponding `expo` commands automatically, so they’ll keep working even when the `scripts` in `package.json` has not been changed. It will also show a warning that explains how to update the scripts to use Expo CLI.

**Comment by brentvatne** [comment]
> Maintenance: having these two projects as separate codebases requires more maintenance and CRNA has previously falled behind because of this. A single codebase helps us keep it up to date and fix issues as fast as possible.

:+1: to this - maintaining separate tools that do the same thing is not something that anyone wants to work on.

I like the plan to make CRNA delegate to expo-cli, this will be important to ensure that lots of tutorials out there aren't broken. We might need to update the CRNA docs as well to briefly explain what the relationship is between that project and expo-cli, perhaps also link to this issue for additional context.

**Comment by hramos** [comment]
Thanks for writing this up! I'm OK with making this change.

**Comment by grabbou** [comment]
Thanks for the write-up. I am really happy to see this proposal - from the very first moment `create-react-native-app` has been announced, I felt like using Expo CLI was the way to go. I guess it's just that it wasn't ready yet and I sense that some of the features implemented there got ported to Expo CLI after all.

One question:

> The create-react-native-app command will continue to work

Is there plan to eventually deprecate `crna` and default to using Expo?

**Comment by satya164** [comment]
It will be awesome! I've been using the Expo CLI and love it. The web UI is so cool.

**Comment by axemclion** [comment]
This is awesome, I think we should do it. I am not sure if anyone else is opposed to this proposal, so lets do it !!

**Comment by kelset** [comment]
Yeah I agree with this, I think that would be great 😍

:shipit:

**Comment by fson** [comment]
@grabbou:
> Is there plan to eventually deprecate crna and default to using Expo CLI?

After the proposal has been implemented, the docs will point to Expo CLI so it will be the default. For backwards compatibility, the CRNA command will be a thin wrapper that delegates commands to Expo CLI.

**Comment by kelset** [comment]
Side question - currently we have a [CRNA label](https://github.com/facebook/react-native/labels/%3Aatom_symbol%3ACRNA) on the main repo, what should we do with it? Change it to something more generic and point the users to the Expo CLI repo for issues with it?

**Comment by fson** [comment]
@kelset that sounds reasonable.

**Comment by kelset** [comment]
I think there is not risk of "vendor lock-in/monopolisation", there is always the option of `react-native init` something; and CRNA already uses expo beneath the surface, the conversation here is more about reducing the redundancy around the CRNA tool. (and moreover the CRNA is not the only "boilerplate generator" available, see Ignite, etc..)

> are constantly hounded with 'why doesn't this work in expo / why do I have to eject issues'

I totally understand your issue here, I've seen it in many places. That said:
1) tbh most of those issues you should (IMHO) just close and redirect to the correct repo (which is what will happen when we move to the Expo CLI)
1) at RNEU the Expo team announced a few changes ongoing on how Expo architecture that should help with a more painless eject experience (namely, fragmentation of the Expo modules) (if I've understood correctly)

Hope these help reduce your concerns :)

**Comment by Salakar** [comment]
@kelset it does, thanks for the response. 👍 

That's fair, again like I say, not complaining just querying :) would still be good to ensure the eject part of it is documented - wasn't sure if those were the correct docs for `expo-cli` - seems like an almost identical CLI with some small differences.

Happy to submit a PR to do so if there's anywhere I can and if it helps.

**Comment by brentvatne** [comment]
@Salakar - we're about to take it out of beta, blog post sitting in draft until @fson finishes updating all of our docs and some other resources to refer to expo-cli. You can learn more about the differences between exp and expo-cli here: https://blog.expo.io/announcing-expo-dev-tools-beta-c252cbeccb36 - basically expo-cli replaces it and another tool called XDE

**Comment by Salakar** [comment]
Ah cool, thanks for the link @brentvatne - looks great 👌

**Comment by mathieudutour** [comment]
What's the way forward for alternative `react-native-script` like https://github.com/mathieudutour/create-react-native-app-typescript? I understand that it will still use the old `create-react-native-app` init script when provided with a `scripts-version` and that's a good temporary measure but I don't think that a good solution long term.

Is there any plan to open `expo-cli` to provide an arbitrary template?

**Comment by satya164** [comment]
I'm wondering what's the advantage of a custom script over using another tool made for boilerplates like yeoman.

**Comment by kelset** [comment]
Moreover you can still pass templates to the standard CLI, right? 🤔

**Comment by mathieudutour** [comment]
> I'm wondering what's the advantage of a custom script over using another tool made for boilerplates like yeoman

It's more about the custom template than the custom script. Sure yeoman could work but before there was a nice workflow for custom scripts: fork the main one, do your changes and you can still get the upstream changes if you want to so the workload of maintaining one is not too high.

Now you will need to look at the blank template which I'm not even sure where it is and keep track of the changes by yourself. I think that's just the death of custom scripts (which are really just templates)

> you can still pass templates to the standard CLI

Sure but it won't be maintained anymore and the "original" script doesn't exist so obviously is not going to be maintained

**Comment by kelset** [comment]
> obviously is not going to be maintained

maybe you misunderstood which CLI I am referring to, because `react-native` CLI is actually being extract to be **more** closely maintained soooo 🤷‍♂️

**Comment by mathieudutour** [comment]
I'm talking about `create-react-native-app`. It's now just a stub for `expo-cli` in the "normal" use case so the code path for custom script is probably not going to be maintained anymore

**Comment by mathieudutour** [comment]
To be clear, I'm not against moving to expo-cli, the work done there is really great. I'm just asking for a migration for existing custom-script as I believe the move to expo-cli will just kill them in the medium/long term.

There are already 2 templates baked in expo. I'm sure it wouldn't be too hard to document where they are so that they can be forked and to add an option to the CLI to choose an arbitrary template. Happy to send a PR if that's something you would consider

**Comment by fson** [comment]
@mathieudutour this is a reasonable question. Thanks for bringing it up. I think it would be great for Expo CLI to support custom templates. I've opened an issue at https://github.com/expo/expo-cli/issues/65.

Right now the builtin templates such as https://github.com/expo/new-project-template are each bundled into a tarball and served from a CDN. I think it would be good to simplify that process so that a package can be installed from an npm package. We should also make `expo init` install dependencies (right now node_modules is bundled in the tarball). So this requires some work.

Right now the Expo CLI templates only include the code for an app (similar to the `template` folder), there's no separate `init` script like in CRNA. It seems that this would be sufficient for `create-react-native-app-ts`, for example (since the main changes from the default templates are to code in `App.js` to make it use TypeScript and some additional packager options added to `app.json` to make it use tsc.) If I'm wrong, please comment in the issue I linked to, it's important that we can support things like TypeScript.

In the meantime, you can continue to use `create-react-native-app --scripts-versions <custom-script>` as before.

**Comment by jamonholmgren** [comment]
Just a sidenote that [Ignite CLI](https://github.com/infinitered/ignite) supports custom boilerplate templates, including Expo-powered ones. We've found it to be a pretty useful feature since Ignite CLI 2.0 was released.

**Comment by brentvatne** [comment]
this is done now so I'll close the issue

**Comment by kelset** [comment]
@brentvatne do you mean that the new CLI is out? Are the RN docs been updated yet? LMK so I can update the label on the main repo 👍

**Comment by brentvatne** [comment]
yup, it's out and the docs have been updated: ![](http://url.brentvatne.ca/M57Mym.png)

**Comment by kelset** [comment]
Awesome, label updated!

**Comment by borgogelli** [comment]
What is the react-native-cli npm package ? Is it deprecated too ?

**Comment by brentvatne** [comment]
@borgogelli - no, it's in the documentation under the "Building projects with Native Code" tab

**Comment by phearakthefoundry** [comment]
`when I try command : expo init test and then it show like bellow 
? Choose a template: expo-template-blank
Using Yarn to install packages. You can pass --npm to use npm instead.
Extracting project files...
Customizing project...
Initialized a git repository.
Installing dependencies...
> yarn install
yarn install v1.22.0
info No lockfile found.
[1/4] Resolving packages...
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > fbjs-scripts > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native > metro-babel-register > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning react-native-web > deep-assign@3.0.0: Check out `lodash.merge` or `merge-options` instead.
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "win32" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 99.06s.

Your project is ready at C:\Users\phean\test

To get started, you can type:

  cd test
  yarn start
`
