### ISSUE TITLE
ReactNative WebView content height calculation working fine on iOS but on Android it gives more height than the actual content

### ISSUE THREAD

**Issue by sreekanth-14** [react-native-community/discussions-and-proposals#230]
I am using web view to load my rich text editor html content in react native. The problem is I need to render multiple webviews one after the other vertically. And webview need a explicit height to load content. So, after searching for some time I found https://medium.com/@fxwio/set-webview-height-to-the-height-of-html-content-react-native-2d696128c181 and it helped me to identify height based on content. The content height on iOS is working fine. But on Android if the actual content height is "1756" it calculates as "8884". Please help me out of this.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the [react native webview repo](https://github.com/react-native-community/react-native-webview).
