### ISSUE TITLE
Move safe area view to react-native-community

### ISSUE THREAD

**Issue by jacobp100** [react-native-community/discussions-and-proposals#231]
### Introduction

I've just moved out `SafeAreaView` from `react-native`, added the ability to add custom padding, and specify the edges to apply to.

It still uses the same native code ObjC, so will be faster than `react-native-safe-area-context` & co.

It's currently homed [here](https://github.com/jacobp100/safe-area-view) - but it's unpublished as of yet!

Before publishing, I wanted to get your thoughts on adding it under react-native-community.

### The Core of It

`SafeAreaView` isn't scheduled for removal as part of lean core - but it looks like it wasn't added to the list of what to keep/remove at all, so it might have just been missed.

Having this package means we can add more functionality like adding padding (which wasn't possible in RN due to breaking changes)

### Discussion points

Does this belong in react-native-community?

**Comment by thymikee** [comment]
cc @satya164 @janicduplessis @brentvatne

**Comment by satya164** [comment]
Maybe merge it with `react-native-safe-area-context` instead? `react-native-safe-area-context` is also native ObjC.

**Comment by jacobp100** [comment]
We could replace `SafeAreaView` in `react-native-safe-area-context` with this native-only view - it'll avoid the lag from the bridge which can make switching from landscape to portrait. It would be a breaking change because setting padding on the view would be additive rather than replacing the inset padding.

I know some of the maintainers of the package are already pinged - what are your thoughts?

**Comment by jacobp100** [comment]
I've got a draft PR here - https://github.com/th3rdwave/react-native-safe-area-context/pull/78

**Comment by brentvatne** [comment]
thanks for doing that @jacobp100! this is will be very valuable to the community

**Comment by brentvatne** [comment]
I'm going to close this issue because the changes have been merged into https://github.com/th3rdwave/react-native-safe-area-context and the library is perfectly fine where it is currently located!
