### ISSUE TITLE
supporting concurrent mode in react-native

### ISSUE THREAD

**Issue by hosseinmd** [react-native-community/discussions-and-proposals#232]
### Introduction
React is in progress to release concurrent mode in the next version. As soon as possible.

### Discussion points
React-native needs to be ready for this.
Is there any progress in supporting Concurrent mode?

**Comment by TheSavior** [comment]
See https://github.com/react-native-community/discussions-and-proposals/issues/4. Fabric is the work to support concurrent mode in React Native.
