### ISSUE TITLE
Warning "Require cycles are allowed, but can result in uninitialized values".

### ISSUE THREAD

**Issue by m-inan** [react-native-community/discussions-and-proposals#236]
### Introduction
I am getting the warning when I use an internal structure with the Context API.

### Details

I have a simple form build. And I use `Context Api` to hold the form data. First of all, I add the 'Provider' to the 'Form' and then the 'Inputs' Component. There is a `Username` component in` Inputs`. I import context data from `username` with` import { useForm } from '../index'`. However, I get a warning message as I showed it on the console afterwards. I get the same warning in packages like `rn-fetch-blob` and` react-native-maps`.

#### Example Code Structre
```typescript
// index.tsx
import React, { createContext, useContext } from 'react';

const Context = createContext();
export const useForm = () => useContext(Context)
 
interface Props {};

export const Form: React.FC<Props> = () => {
  return (
    <Context.Provider>
      <Inputs />	
    </Context.Provider>
  )
}
```

```typescript
// Inputs.tsx
import React, { Fragment } from 'react';
import { Username } from './Username';

interface Props {}

export const Inputs: React.FC<Props> = () => {
  return <Fragment>
    <Username />
  </Fragment>
}
```

```typescript
// Username.tsx
import React from 'react';
import { useForm } from '../index'

interface Props {};

export const Username: React.FC<Props> = () => {
  const { usename } = useForm();

  return <Fragment>
    <TextInput value={username} />
  </Fragment>
}
```

#### Output Terminal

```shell
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: src/Profile/Form/index.tsx -> src/Profile/Form/Inputs/index.ts -> src//Profile/Form/Inputs/Username.tsx -> src/Profile/Form/index.tsx
```

> Rn Fetch Blob package warning
```shell
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/rn-fetch-blob/index.js -> node_modules/rn-fetch-blob/polyfill/index.js -> node_modules/rn-fetch-blob/polyfill/Blob.js -> node_modules/rn-fetch-blob/index.js
```
> React Native Maps
```shell
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: node_modules/react-native-maps/lib/components/MapView.js -> node_modules/react-native-maps/lib/components/MapPolygon.js -> node_modules/react-native-maps/lib/components/MapView.js
```

### Discussion points

Is this usage incorrect? How can I make a similar structure more properly for the form. Or how can I hide this warning message if this usage is correct.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

In particular, the cycle warning shows you the cycle you are creating between files, so I would recommend that you refactor your files and imports in order to remove them. As explained by the message, having them, "can result in uninitialized values" -> this may potentially lead to bad behaviours/crashes maybe?

Also, if the map and fetch blob packages send that warning too I would recommend reporting that in those libraries issue section and/or do directly PRs to fix them
