### ISSUE TITLE
Can I make a chat icon similar to facebook message ?

### ISSUE THREAD

**Issue by penebrain** [react-native-community/discussions-and-proposals#239]
![IMAGE 2020-05-26 16:33:18](https://user-images.githubusercontent.com/56078935/82878841-a31c9600-9f6e-11ea-8744-d496470e187d.jpg)
I want to create a hover window like Facebook message,How can I do

**Comment by thymikee** [comment]
Hey @penebrain. This project is for discussions and proposals to React Native, not a help forum. Please visit https://reactnative.dev/help.html
