### ISSUE TITLE
Custom ScrollToIndex Animations in Flatlist/VirtualizedList

### ISSUE THREAD

**Issue by Kida007** [react-native-community/discussions-and-proposals#24]
so I was trying to build a **Flat Roulette** using FlatList.  something like this 
![simulator screen shot - iphone 6 - 2018-09-02 at 01 39 30](https://user-images.githubusercontent.com/22558035/44955407-5c505800-aed0-11e8-82e4-731a3351d48d.png)

it is working as per the logic , but the scroll animation is too subtle and fast .  i want to use my own Animation with custom Easing , duration etc .  but cant find a way or even a workaround . 
shouldn't there be something to define own  Scroll Animation.

**Comment by Kida007** [comment]
tried doing the same earlier, Bot closed it for me because I didn't follow their template ( How To Reproduce etc). Then tried it on discussions and proposal and got closed. am I missing something here :)

**Comment by axe-fb** [comment]
I think you should open this in the main repo with the template. Which template did you follow to that the bot closed the isse ?

**Comment by Kida007** [comment]
I didn't follow any since it was a feature request, not a bug and I found providing 'How to Reproduce' and 'Environment Info' Redundant. Also, react-native guided me here after closing.

**Comment by aleclarson** [comment]
[This](https://react-native.canny.io/feature-requests) looks like the right place.

I even found a similar request: [see here](https://react-native.canny.io/feature-requests/p/add-speed-attribute-to-scrollto)

**Comment by Kida007** [comment]
Thanks @aleclarson  for resources .

**Comment by axe-fb** [comment]
We are not actively looking at the site for new features - we may not have the bandwidth to work on the feature. However, @Kida007  - if you have a proposal on how to fix it, and a PR, we would gladly accept it.
