### ISSUE TITLE
Multi ScrollView Problem On Android Only... One ScrollView Affecting The Other!

### ISSUE THREAD

**Issue by Jagatpalv** [react-native-community/discussions-and-proposals#242]
I have been facing a weird issue with ScrollViews on Android. It is fine on iOS.

When I use two ScrollView components in a single parent component, one ScrollView seems to affect the other one. Take the following as an example:

```
<View style={{height:300}}>
<ScrollView>
<View>Some long scrollable content... </View>
</ScrollView>
</View>

<View style={{height:300}}>
<ScrollView>
<View>Some long scrollable content...</View>
</ScrollView>
</View>

```
When there is just one ScrollView in the component, it is all working just fine. However, after putting two ScrollView components both get messed up. Sometimes when I scroll the bottom one the upper one also starts scrolling. And only the bottom one seems to function properly the upper one is glitchy.

I first faced this while creating my App. I was able to replicate this in a new empty react-native app.

This issue has created a roadblock for me as I cannot design the app any further because my design greatly depends on the possibility of both scroll views functioning properly.

Any help/fix will be greatly appreciated. Thanks!

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue, following the template, on the main [react native repo](https://github.com/facebook/react-native).
