### ISSUE TITLE
Init Process Takes Long Time

### ISSUE THREAD

**Issue by srht** [react-native-community/discussions-and-proposals#243]
I run the npx react-native init AwesomeProject command to init a new project. But it takes very long time to install the dependencies. Is it normal for every project initiation for react native or sould i do something else?

**Comment by srht** [comment]
| Installing dependencies still continuing...

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
