### ISSUE TITLE
How to add background to different parts of FlatList

### ISSUE THREAD

**Issue by SmirnovM91** [react-native-community/discussions-and-proposals#244]
Do you have any ideas?

![image](https://user-images.githubusercontent.com/32675072/83358310-787a7500-a394-11ea-9031-e6a07e0acd3e.png)

orig pic
![image](https://user-images.githubusercontent.com/32675072/83358347-b11a4e80-a394-11ea-8912-af692f8da469.png)

P.S. I need a ListHeaderComponent

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
