### ISSUE TITLE
Wanted: [FlatList] Scroll continuously in both directions

### ISSUE THREAD

**Issue by xlcrr** [react-native-community/discussions-and-proposals#246]
I have an array of limited data

```[0, 1, 2, .... 10]```

and I would like to show

```[ ... 10, 0, 1, ....]```

allowing the user to scroll continuously left and right.

One attempt has been made at this [here](https://github.com/prateek3255/react-native-infinite-looping-scroll/)

However, it is buggy when used in horizontal scrolling as the keys are duplicated.

FlatList already has `inverted` property to scroll backwards... so this should be possible?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
