### ISSUE TITLE
Style support for Native UI components for eg: EditText and UITextField.

### ISSUE THREAD

**Issue by benjaminlogan420** [react-native-community/discussions-and-proposals#251]
### Introduction

Support for using the style that is passed as a property to the native UI component.

### Details

As of now, I don't think we have this ease. If we want to set a font-family to our EditText or UITextField, we need to define that as a property on our native UI component. If we compare native UI Component of textfield with the one of react-native, i.e. TextInput, we see a difference in the style property. TextInput picks the font styling from the style property but our native UI component doesn't do that. Though it picks height, width and so on, but with font styling it doesn't.

### Discussion points

1.) Font-styling should be interpreted directly to the EditText or UITextField, setting font properties explicitly doesn't sound great.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

Or you could open a PR directly modifying the behaviour in the way you are describing it - that would help a lot with understanding the tradeoffs of your idea.
