### ISSUE TITLE
Pass component's own props to event handler functions for native components

### ISSUE THREAD

**Issue by CostachescuCristinel** [react-native-community/discussions-and-proposals#259]
### Introduction
I would like to discuss the idea of passing component's own props to the event handler functions, on native components.
To be noted that I am not sure whether this proposal would be fit for React Native, or the core React project, forgive me if it doesn't belong here.

### Details
One of the major flaws that I see in developing react native projects, is that it's very hard to "inject" data into event handler functions. This easily forces devs into binding functions in render just so they are able to access some data:
`<TouchableOpacity onPress={()=>{ handlePress(greeting, rank, name); }}>`
Even worse, some may be tempted to use global variables or class fields to pass data.
Everyone should already know the issues of using these solutions (unnecessary re-renders, stalled state, ect.).
Nevertheless, we still need to access data computed at render time in order to handle some events, and do so without using global variables or class fields.

A class component could mitigate the issue, allowing to compute some data in the event handler function itslef. But we can all agree that this method has 2 main issues:
- the overhead of a `class component`, way overkill if you just need some data computed at render time
- some data may be shared by other components rendered in the return tree, forcing the creation of helper functions, to avoid duplicating logic and/or data - which in turn causes clutter.

My proposal aims to avoid these issues, by proposing for React Native to pass component's own props to any of the event handler functions.
This behavior should only be implemented for native components/events - that is, custom components are free to handle events as they see fit.
The props would be availabe to the event handler function as an additional parameter to the parameters list of an event handler function.

Consider the following example:

```
function handlePress(event, ownProps){
	// ownProps is the proposed change - an object which contains all of
	// component's own props. In this case, for example, it contains:
	/* ownProps = {
		greeting: "Hello there",
		rank: "General",
		name: "Kenobi",
		onPress: <function handlePress>
	} */
	
	const { greeting, rank, name } = ownProps;

	console.log(`${greeting}, ${rank} ${name}`);
}

function CustomButton(props){
	const name = props.name || "Kenobi";

	return <TouchableOpacity
		greeting="Hello there"
		rank={props.rank || "General"}
		name={name}
		onPress={handlePress}
	>
		<Text>Greet {name}</Text>
	</TouchableOpacity>;
}
```

### Discussion points
The **pros**:
- This proposal allows to easily compute and share data from the render function to the event handler functions
- There is no need to switch to a class component to access component's props
- No need to use state to ensure updated computed data is used for every component in the returned render tree

Any **cons** ?
I don't have knowledge of the possible impact that this may have on the core logic in React / React Native. I can suppose that passing through component's own props creates some additional work behind the scenes, which could possibly impact performance. However, computed props will be already available and computed during each component's render, which should not create additional overhead to process those.

What do you guys think about this proposal? Did I not catch any flaws in it?

**Comment by TheSavior** [comment]
I think this is more of a question or proposal for React than React Native. Consider opening an issue in the React RFCs repo to get feedback.
