### ISSUE TITLE
how to get element key in onPress without binding in React Native?

### ISSUE THREAD

**Issue by arslan2012** [react-native-community/discussions-and-proposals#26]
We already know that the AirBnB style guide discourages using .bind() inside the render function ([source](https://github.com/airbnb/javascript/tree/master/react)). As explained [here](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-bind.md):

>A bind call or arrow function in a JSX prop will create a brand new function on every single render. This is bad for performance, as it will result in the garbage collector being invoked way more than is necessary.

this is what we used to do, passing the param into bind

```javascript
renderSingleItem = ({item}) => <TouchableOpacity onPress={func.bind(this, item.id)}>
return <FlatList data={data} renderItem={this.renderSingleItem}/>
```

and this seems to be the only way since the param of onPress in React Native doesn't contain target object like ReactJS do. 

ReactJS:

```javascript
typeof event.taget === 'object'
```

React Native:

```javascript
typeof event.taget === 'number'
```

Is there a better approach for this?

**Comment by satya164** [comment]
Hey, this repo is for discussions and proposals regarding changes in React Native. It's not intended for questions. Please post your questions on StackOverflow under the React Native tag instead.

**Comment by jamonholmgren** [comment]
We probably need an issue template that asks whether it's a larger proposal (like extracting WebView) or a smaller issue or bug.
