### ISSUE TITLE
Totorial and or Example

### ISSUE THREAD

**Issue by GanongLS** [react-native-community/discussions-and-proposals#260]
### Introduction

I do really like how react native documentation being build, but for some area like animated the example that can be accessed from snack expo are limited. I still new in programming so i have real hard way for learning. thankfully some react native component has real nice example but not all, please consider giving more example that can be show in snack expo. 

Tutorial and Example

**Comment by pvinis** [comment]
The docs live in their own repo here https://github.com/facebook/react-native-website.

Documentation improvements using PRs and improvement ideas using issues are always welcome. Making an issue there would be the best next step, ideally being specific about adding snacks and/or Animated doc improvement ideas etc.

Thank you :)
