### ISSUE TITLE
what about New architectur now 2020/08/03

### ISSUE THREAD

**Issue by ganshiqingyuan** [react-native-community/discussions-and-proposals#261]
I want to write our app use react-native..and I want the New architectur to make our app better .  when can i use it?

**Comment by kelset** [comment]
the new architecture will land in stages and it will take a lot of time before it will be fully completed and out in the OSS.

The first stage of JSI is already out, and TurboModules will come next at some point in the second half of 2020 (I hope). You can keep up with the status in the dedicated issue https://github.com/react-native-community/discussions-and-proposals/issues/40
