### ISSUE TITLE
Support Image.capInsets on Android

### ISSUE THREAD

**Issue by defrex** [react-native-community/discussions-and-proposals#264]
### Introduction

The `capInsets` prop on `Image` is great, and supports all kinds of flexible box styling.

It's currently supported on iOS but not Android, even though Android has an analogous feature called a "9-patch".

### Details

This is especially unfortunate because there is no great way to add custom shadows on Android. 9-patches are a way to solve this.

One caveat is that the 9-patch spec on Android encodes the `capInsets` values into the image with right and bottom 1-pixel lines.

### Discussion points

- Is there a way to abstract the `.9.png` format so the lines aren't required, making the 2 platform APIs compatible?
- If not, could an android-only `ninePatch` prop be added to `Image` to indicate the format?

**Comment by kelset** [comment]
This seems a precise feature request, so I would recommend you opening a PR with the stub implementation so that it can be discussed further.
