### ISSUE TITLE
xiaomi problems with some Apps (android)

### ISSUE THREAD

**Issue by OusamaDridi** [react-native-community/discussions-and-proposals#266]
### Introduction

I developed an application with the  react native language. all goes well the application runs without any problem. if I install the application on xiamo it runs for the first time then it spits and does not work anymore and displays this error message: java.lang.illegalargumentexception: could not convert class android.os.UserHandle
there is someone who can help me?!

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
