### ISSUE TITLE
Wasting time by maintaining a feature parallel

### ISSUE THREAD

**Issue by hosseinmd** [react-native-community/discussions-and-proposals#267]
React-native has few features that don't need to be in react-native because a 3rd-party library is like:

Animated: react-native-reanimated has more powerful features than react-native, I think we don't need react-native Animated.
Modal: modal should move to react-native-modal.
DrawerAndroid: every navigation library or  UI components library has a Drawer.

**Comment by kelset** [comment]
Hi Hossein,
thanks for your feedback. I understand what you are saying, and in fact there has been already a first wave last year of modules that were detached from the main repo.

That said, it's not an easy nor straightforward process and there are ongoing conversation on what should be in the main repo, how it should structured, etc.
