### ISSUE TITLE
Add multi color support for ActivityIndicator

### ISSUE THREAD

**Issue by aloknecessary** [react-native-community/discussions-and-proposals#268]
### Introduction

Request to add multiple colors to activity indicator

### Details

Right now we can only show one color using existing activityindicator component, it will be more fun if we add multicolor support just like RefreshControl component accepting array of colors

### Discussion points

Modify ActivityIndicator to have multi color support

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you open a PR that adds the feature you are describing directly to the main repo so that it can be discussed in details there.

**Comment by jeswinsimon** [comment]
Also, looks like it already does https://reactnative.dev/docs/activityindicator.
