### ISSUE TITLE
resize and or compress jpg stored on device

### ISSUE THREAD

**Issue by alainib** [react-native-community/discussions-and-proposals#27]
Hello.
I work on an app who make pictures from camera and upload them to an API.
Currently i use "react-native-image-crop-picker" package from npm who work very well for resizing and compressing but lost the EXIF data.

Or i need EXIF , i opened a issue on "react-native-image-crop-picker" github but no response after few weeks.

Is there a way to compress and or resize image stored on device with react ? i tryed js lib like "piexifjs" but didn't found how to make it work :(

any advice are welcomed. thanks

**Comment by jamonholmgren** [comment]
Hey @alainib, thanks for your issue. This repo is for larger discussions and proposals regarding changes in React Native core. I would suggest that you seek help on Stackoverflow under the [React Native tag](https://stackoverflow.com/questions/tagged/react-native), on [Reactiflux](https://www.reactiflux.com/), or the [Infinite Red Community](https://community.infinite.red).
