### ISSUE TITLE
Request for Dark Theme with theme toggle for developers 

### ISSUE THREAD

**Issue by lopeselio** [react-native-community/discussions-and-proposals#270]
This is just a small feature request. Would do a world good.

### Introduction

I'd like to suggest implementing a Dark theme toggle switch, the same way Redux website https://redux.js.org/ and Redux Toolkit website https://redux-toolkit.js.org/ have that small toggle switch at the right upper corner of the top navbar.

### Details

It really hurts your eyes when you read other Redux documents with dark theme and suddenly React Native website is bright white, especially while integrating redux.

### Discussion points

Would do a lot good for the community

**Comment by thymikee** [comment]
Can you move this issue to https://github.com/facebook/react-native-website? That's where website development happen. I'm sure they'll be happy to consider this change :)
