### ISSUE TITLE
is it possible to use react native project in native ios and android project (ios and java)? 

### ISSUE THREAD

**Issue by onurcskun** [react-native-community/discussions-and-proposals#272]
react native in swift or java;

I want to create create a react native project that open webview(react-native-webview). After that, I want to use it in native ios or android projects.

i already have experienced bridging native(swift and java) modules to react native both android and ios modules. Is it possible to make it reverse :)

**Comment by Krizzu** [comment]
Yes, it is, [it's described in React Native docs](https://reactnative.dev/docs/integration-with-existing-apps). Closing as this repo is for discussions and proposals only.
