### ISSUE TITLE
Replace SafeAreaView with a better alternative, integrate functionality into StyleSheet

### ISSUE THREAD

**Issue by CostachescuCristinel** [react-native-community/discussions-and-proposals#275]
### Introduction
_This suggestion comes after following the discussion of this bug report:
https://github.com/facebook/react-native/issues/22211_

It seems to me that the approach of providing a component to do what `SafeAreaView` does, is not the right one. Although it's quite easy to use (on the supported platform and OS versions), it hides details from the developer and it makes it harder to customise the experience while taking into account, or ignoring, the unsafe areas. And it forces the developer to create platform and OS specific code (wasn't react native supposed to help eliminate these differences?...).

### Details

 In particular, `SafeAreaView` has the following downsides:
- It is an iOS 11+ only component: iOS < 11 also has a status bar, there simply is no reason `SafeAreaView` could not provide `paddingTop` for iOS 10 and lower
- It is an iOS only component: Android has a status bar too, and it has on screen navigation buttons in a similar fashion to iOS's home bar. There is no reason for SafeAreaView to only work on iOS.
- The 'unsafe' areas cannot be overridden: being unable to override the unsafe paddings to draw in the unsafe areas is a big issue when implementing fullscreen content presentation, or screen-wide animations (content clipping, unrealiable calculations for animation boundaries, need for absolute positioned components or conditional renders, ect.)
- Adds another level of wrapping around the content: totally unnecessary, since you would (most likely) already have some container `View` for your component/screen that you are already handling styling for.

### Discussion points
I would like to propose a solution to the issues described above: add this functionality to the `StyleSheet` API.
It seems to me like this is the perfect spot to add the functionality provided by `SafeAreaView`, while also providing greater benefits than the `SafeAreaView` component provides at the moment.

Consider the following implementation suggestion:
1. `StyleSheet.unsafeAreas = { top, bottom, left, right }`
an object containing the measurements of the areas considered unsafe. The developer can decide to use these for any purpose. Particularly useful in the case of animations, which could exactly calculate content size and boundaries.
2. `StyleSheet.unsafeAreasPadding = { paddingTop, paddingBottom, paddingLeft, paddingRight }`
a convenience object that provides ready-to-use paddings in any component's `style` prop.
`<View style={StyleSheet.unsafeAreasPadding}> ... </View>`
is the direct replacement of the current `SafeAreaView` component, with the added bonus that these paddings could be used on an `Animated.View` as well, and could be overridden as needed for any purpose.
3. `StyleSheet.addUnsafeAreasChangeListener(({ top, bottom, left, right}) => { })`
A method that subscribes listener functions for changes in unsafe areas, such as, when the screen orientation changes, or on Android, when enabling/disabling the onscreen navigation buttons (some devices support this, most custom roms also provide this).

If the `StyleSheet` API does not seem the proper spot for you, it could be implemented separately, the same way the `Appearance` API is.

I hope you'll consider this solution, I am really looking forward for your thoughts on it.
Oh, and, please don't forget to add iOS < 11 and Android support :)

**Comment by kelset** [comment]
I think that there was a similar conversation a while back (@brentvatne @janicduplessis correct me if I'm wrong), and basically there was even an attempt at fixing SafeAreaView within the main React native repo - but it was too complicated (or something like that) so that PR ended up becoming this repo: https://github.com/th3rdwave/react-native-safe-area-context.

I think that it's not as well known as it should be, probably it'd be worth redirecting folks to that library? 🤔

**Comment by CostachescuCristinel** [comment]
While `react-native-safe-area-context` does a good job, I would still prefer a way to access those measurements directly. A simple API or style object through StyleSheet is easier (and nicer) to handle than an ad-hoc component.

**Comment by acoates-ms** [comment]
A style object in stylesheet will not handle various scenarios such as multiple screen devices, picture in picture, Splitscreen not to mention desktop platfroms such as react-native-macos and react-native-windows.  The context API is much more complete as a future proof direction.

**Comment by brentvatne** [comment]
another related issue: https://github.com/react-native-community/discussions-and-proposals/issues/256

> I would still prefer a way to access those measurements directly. A simple API or style object through StyleSheet is easier (and nicer) to handle than an ad-hoc component.

this is exactly what hooks are good for:

```js
import { useSafeAreaInsets } from 'react-native-safe-area-context';

function HookComponent() {
  const insets = useSafeAreaInsets();

  return <View style={{ paddingBottom: Math.max(insets.bottom, 16) }} />;
}
```

> If the StyleSheet API does not seem the proper spot for you, it could be implemented separately, the same way the Appearance API is.

I think your proposals are entirely covered by the existing react-native-safe-area-context API, I think that is what you are looking for.

> Oh, and, please don't forget to add iOS < 11 and Android support :)

this is also already supported in react-native-safe-area-context

<hr />

I'll close this issue because I think it is resolved. I do think we should consider removing `SafeAreaView` from core because react-native-safe-area-context is a much more complete solution.
