### ISSUE TITLE
Why doesn't React Native offer native support for changing the color or visibility of the "NavigationBar" for android?

### ISSUE THREAD

**Issue by 3GOMESz** [react-native-community/discussions-and-proposals#279]
I mean, we already have the element "StatusBar" and we can define its color, on android this element takes care of the top part outside the application, changing the appearance of the bar where the time is, the battery level and notifications.

```
<View> 
    <StatusBar backgroundColor="#COLOR HEX HERE" barStyle="STATUSBAR STYLE STRING HERE" />
    ...
    ...
</View>
```

But there is no "NavigationBar" element yet. It would be interesting if it existed and was initialized with a hex string and if the element is visible or not, like the "StatusBar" does.

### Example for using a possible addition of the element "NavigationBar" in the future:
```
<View> 
    <StatusBar backgroundColor="#COLOR HEX HERE" barStyle="STATUSBAR STYLE STRING HERE" />
    <NavigationBar backgroundColor="#COLOR HEX HERE" barStyle="NAVIGATIONBAR STYLE STRING HERE" />
    ...
    ...
</View>
```
![brbrbrbr](https://user-images.githubusercontent.com/28831375/94481113-a25e6f80-01ad-11eb-839f-423dfaff9cfa.png)

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you open a PR that adds the feature you are describing directly to the main repo so that it can be discussed in details there.
