### ISSUE TITLE
Selectable Text control missing functionality

### ISSUE THREAD

**Issue by kmkrtich** [react-native-community/discussions-and-proposals#281]
Text control with selectable attribute doesn't support any flag for getting selected text or checking whether text is selected

<Text selectable={true} />

The main issue that I'm having is how to close tooltip menu (Copy|Paste|Select All) whenever we click outside of text control.
It keeps open all the time until I choose any action from the tooltip menu.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
