### ISSUE TITLE
I am looking at the react native code and trying to understand how are you capturing Device details

### ISSUE THREAD

**Issue by rajatshetty** [react-native-community/discussions-and-proposals#282]
Hello Team,

I am looking out for some help on getting the device details.

I am developing a package in node which can help people to get device information.

For ex: If someone has developed a mobile application using angular/jquery or any other SPA technology this package should help them and give device information 

Device information like
1) What is the version of OS that is  getting used
2) What the Device name
3) What is the device model

Irrespective of someone is using react/angular/ionic/phonegapp someone should be able to get the device information using this package.

I want to get some inspiration from react native.

Thanks!

**Comment by thymikee** [comment]
Hey @rajatshetty, check out this package: https://github.com/react-native-community/react-native-device-info.
