### ISSUE TITLE
Proposal - add *.hprof to .gitignore file

### ISSUE THREAD

**Issue by msmfsd** [react-native-community/discussions-and-proposals#285]
### Introduction

Add *.hprof to react-native's .gitignore file.

### Details

When doing a android build (`cd android && ./gradlew bundleRelease`) as recommended on `https://reactnative.dev/docs/signed-apk-android` a very large `.hprof` file is sometimes generated in the `android` folder. Because these files are not needed in repos and large (over 500MB) I propose putting `*.hprof` in the root .gitignore file under the other `# Android/IntelliJ` ignores.

### Discussion points

- avoid large java heap files being commited to users repos.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. I think you should directly go the PR route for this change in the template folder within the [react native repo](https://github.com/facebook/react-native).

That way it can be discussed & reviewed by the FB team

**Comment by msmfsd** [comment]
NP @kelset I can do that 👍

**Comment by msmfsd** [comment]
@kelset actually I notice the latest version of `react-native` has had a big update to the gitignore and `*.hprof` has already been added - so no need for a PR.
