### ISSUE TITLE
Why companies dropped react-native

### ISSUE THREAD

**Issue by hosseinmd** [react-native-community/discussions-and-proposals#286]
The biggest criticism is the large size of the application. Is there a plan to reduce the size?
I think if react-native do that maybe startup time reduce too.

I read this article of Facebook.
https://engineering.fb.com/data-infrastructure/messenger/
It was a little disappointing because, I never imagined react-native could be dropped by Facebook, but they all right, react-native is not small and so fast.
React Native could be something like a flutter(just about size and performance), but no progress on it.
React-Native is not helpless, there is a great community we could do it just needed a plan. Don't think about features, features is enough, Now is not the time for features, there is a big problem that should be solved.
I like react-native-reanimated team, they start to rewriting reanimated again with c++ few months ago and now they have done it. react-native needed to do something.
Thanks for reading.

react-native smaller and faster.

**Comment by TheSavior** [comment]
Facebook still uses React Native heavily, messenger never did. https://twitter.com/dan_abramov/status/1234801507805138945?s=21

Tens of thousands of companies use React Native today, and we are continuously improving it. Thanks for your excitement to see React Native improve!

**Comment by hosseinmd** [comment]
> Tens of thousands of companies use React Native today.
You're right, but that is because of another reason. But react-native still has that problems.

**Comment by kelset** [comment]
We are all aware that [React Native is not perfect](https://github.com/react-native-community/discussions-and-proposals/issues/134).
