### ISSUE TITLE
Put Callback value to WritableMap

### ISSUE THREAD

**Issue by shukerullah** [react-native-community/discussions-and-proposals#289]
Thank you guys for great work on react-native for Android.

### Introduction

I believe following could be considered as a proposal. Currently it is impossible to put Callback value into WritableMap. We can then send multiple and optional callbacks from JS to native. Let me know what do you guys think of this. I can add a Pull Request, let me know if this make sense to you. Thanks.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. I think you should directly go the PR route for this change within the [react native repo](https://github.com/facebook/react-native).

That way it can be discussed & reviewed by the FB team.
