### ISSUE TITLE
React Native 0.64 Release Date

### ISSUE THREAD

**Issue by chongchungyin** [react-native-community/discussions-and-proposals#290]
Hi guys,

RN 0.63 has been released for a while. I noticed with the great work from @grabbou we can now enable hermes for iOS and it will be part of the next release. 

Anyone has any insight what is the plan of next RN release?

**Comment by Naturalclar** [comment]
@chongchungyin Release is being discussed in the following issue. https://github.com/react-native-community/releases/issues/207
