### ISSUE TITLE
JavaOnlyMap and ReadableNativeMap harmonization about key presence

### ISSUE THREAD

**Issue by MichaelBorde** [react-native-community/discussions-and-proposals#292]
### Introduction
`JavaOnlyMap` implementation behaves differently than `ReadableNativeMap` implementation about key presence.

### Details

If you try to get a missing key in a `ReadableNativeMap`, It throws a `NoSuchKeyException` whereas It just returns `null` for `JavaOnlyMap` implementation.

Though my code is tested when I convert data sent over bridge, I came accross a bug on a real device.

I know I made a false assumption about key presence and there is a method to check if map includes a key but I felt confident because of my unit tests.

### Discussion points

I think `JavaOnlyMap` implementation should throw a `NoSuchKeyException` if key is missing when trying to get a value.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. I think you should directly go the PR route for this change within the [react native repo](https://github.com/facebook/react-native).

That way it can be discussed & reviewed by the FB team.
