### ISSUE TITLE
No justifySelf in react native??!!! 

### ISSUE THREAD

**Issue by imspikey** [react-native-community/discussions-and-proposals#294]
Why is justifySelf  not yet implemented in react native

I know there are workarounds but I thought something as simple as that should have bean implemented long time ago? 

Shouldn't justify-self  be on the roadmap at least???!!!

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).
