### ISSUE TITLE
Add event 'onPaging' for ScrollView component

### ISSUE THREAD

**Issue by intergalactic-overlords** [react-native-community/discussions-and-proposals#30]
### Introduction

Add event 'onPaging' for ScrollView component, for executing callbacks on each 'page-scroll' event.

### The Core of It

So, when you add pagingEnabled to a ScrollView, there is (to my knowledge) no way to know 100% sure when you went to the next or previous page.
Right now I use the onMomentumScrollEnd event callback to determine my position and call an event when reaching a new page, but the problem with that is, that when a user scrolls too fast, the momentum doesn't end, and the callback isn't invoked on **each** new page. When scrolling fast, the callback is only invoked on the last page you reach.

#### So why would you need this? (example)

Imagine a bunch of data the user can swipe through, like a slideshow. Underneath is a pager with thumbnails where the user sees on which item they are. The data is not loaded all at once. Only the item you see and 9  items off-screen (so, 10 items in total). When swiping to the next item, the slideshow element detects a new 'onPaging' event and a callback is executed (can be anything, in my case, load some extra data and set the pager correct). When swiping real fast from item 2 to item 5, the callback is only executed on the last item. In this case, the pager jumps from item 2 to item 5, which is a clunky visual experience. If the callback were executed on each 'paging event', the pager could update smoothly.

The new callback could receive the same (or a very similar) event object as the onMomentumScrollEnd callback.

### Discussion points

* do we actually need this, or is it possible to do this with existing code?
* if we need this, is onPaging a good name :-) ?
* if we need this, how does the event object look like?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Your seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).
