### ISSUE TITLE
3D Touch & Force Touch | Apple Pen Support

### ISSUE THREAD

**Issue by Y0ngg4n** [react-native-community/discussions-and-proposals#301]
### Introduction
Is it possible to make Touch Pressure Detection in React Native like with [Pressure.js](https://pressurejs.com/)?
This would be really nice.

### Details

- Pressure and Force Detection
- Tilt Detection
- Pen Button Press Detection

### Discussion points
- Possibility
- Implementation
- Make available for Expo

**Comment by safaiyeh** [comment]
This would be best as a third party module.

**Comment by thymikee** [comment]
As @safaiyeh said.
