### ISSUE TITLE
GestureResponderEvent Accessing Target Component

### ISSUE THREAD

**Issue by NateAGeek** [react-native-community/discussions-and-proposals#302]
### Introduction/Details
Currently the GestureResponderEvent provides a target that is a node id, however, trying to find the referenced component and the subsequent props is not possible. There use to be the `getInstanceFromNode` from the ReactNativeComponentTree, but this was a private method and also is no longer in the source(rightfully due to Fabric). Should we update the GestureResponderEvent target to return a component reference or make component info/props easily accessible with node ids?

### Discussion points

Change GestureResponderEvent target to component reference
Make Native Tree Components more accessible via node id's

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this as a PR against the main [react native repo](https://github.com/facebook/react-native) so that the code details of such an implementation could be discussed further.
