### ISSUE TITLE
How to reduce common name and map it's attributes of fetched JSON data into picker?

### ISSUE THREAD

**Issue by sivarama5055** [react-native-community/discussions-and-proposals#303]
Hello guys!!

I'm retrieving some JSON data through Fetch API into Picker in React Native FlatList , which has more than 2 attributes for the same product as follows :

`{"products":[{ "name": "Dried Blueberry", "weight": "1000gm", "price": "200"}, {"name": "Dried Blueberry", "weight": "500gm", "price": "100"}, {"name": "Dried Blueberry", "weight": "250gm", "price": "50"}]}`

Can anyone tell me how to reduce it based on "name" and map "weight", "price" values into the picker?

**Comment by Krizzu** [comment]
Hey, this repo is mainly for discussions and proposals around React Native itself. It seems like your question is more related to JavaScript, so you can try [posting it on StackOverflow under JavaScript tag.](https://stackoverflow.com/questions/tagged/javascript)
