### ISSUE TITLE
React native android - Unsafe implementation of the HostnameVerifier interface by Google PlayStore

### ISSUE THREAD

**Issue by Sinson48** [react-native-community/discussions-and-proposals#305]
### Introduction

Unsafe implementation of the HostnameVerifier interface by Google PlayStore

### Details

I have developed a react-native app and published the google play store then received the notification from Google play store like as following. 
'We found that your app uses software that contains security vulnerabilities for users. Apps with these vulnerabilities can expose user information or damage a user’s device, and may be considered to be in violation of our Malicious Behavior policy'   'Your app(s) are using an unsafe implementation of the HostnameVerifier interface.'

This app has been in the play store since 2 years.

We need to resolve this before the deadline 1 January 2021.

Please help me sort out this issue.

### Discussion point
I haven't used any implementation about the HostnameVerifier.So it might be some of the third party SdKs.
If anyone have faced similar sort of issues please help me to find out this issue.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
