### ISSUE TITLE
React native 'use_native_module' does not allow to keep ios project at custom location

### ISSUE THREAD

**Issue by ankursharma2496** [react-native-community/discussions-and-proposals#307]
i want to keep my project structure as below

root -
        - ios directory
           ------podfile etc
        -recat-native modules

it gives error - "Invariant Violation: Native module cannot be null."

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
