### ISSUE TITLE
Provide a way to disable React-Native console.log

### ISSUE THREAD

**Issue by Andarius** [react-native-community/discussions-and-proposals#308]
### Introduction

When running in release mode, React-native will display info logs (as also mentioned in this issue: https://github.com/facebook/react-native/issues/18584 and in this PR: https://github.com/facebook/react-native/pull/30579 )

### Details

For instance, using `react-native-navigation`, the following logs are displayed (because of `Libraries/ReactNative/AppRegistry.js:186`): 

```
Running "main.Session" with {"initialProps":{"componentId":"Component1"},"rootTag":1301}
```

Causing them to appear in report logs like Bugsnag:

![Capture d’écran 2020-12-13 à 10 28 43](https://user-images.githubusercontent.com/5070712/102009248-652e6600-3d36-11eb-8f6f-60f5d9f6b981.png)

### Discussion points

Since it seems accepted that the default behavior is that React Native is logging data via `console.log` and the recommended way to deal with it is to install a third-party package, I would like to propose the idea of setting a flag to be able to disable it.

Something like `AppRegistry.disableLogs` seems like a reasonable approach.

**Comment by kelset** [comment]
Sounds like, based on the conversation here https://github.com/facebook/react-native/pull/30579, that the best way forward is for you to direct open the PR introducing the behaviour you are proposing :)

**Comment by Andarius** [comment]
Isn't better to discuss what is the best approach beforehand ? So that the PR has chances to be accepted / not closed without discussion ? (and that I don't spend time changing code that nobody wants to be changed  haha)

**Comment by matt-oakes** [comment]
This shouldn't be something that's inside React Native at all. If you want to change the behaviour of `console.log` in your app, then you always have the option of overriding the global as shown in [this StackOverflow answer](https://stackoverflow.com/a/7042634/99582).

**Comment by Andarius** [comment]
I'm not speaking about changing the `console.log` behavior. Just a "proper" way to disable it where I don't need it.
Let's say I want to do a `console.log` somewhere else that is meaningful to my app ?

My first concern is that this log appears out of nowhere, I had to `grep` my code base to find that it was RN that was doing the `console.log`.

**Comment by a-c-sreedhar-reddy** [comment]
A babel plugin can be used I guess. As mentioned here
http://reactnative.dev/docs/performance#using-consolelog-statements

**Comment by Andarius** [comment]
@a-c-sreedhar-reddy then how can I do it I want other logs to be displayed but not the RN ones ?

**Comment by skaldo** [comment]
Hi @Andarius,
if logs visible in Bugsnag is the only issue you are experiencing, what about simply disabling the `log` breadcrumb type as described [here](https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledbreadcrumbtypes)?

If you want only to suppress all logs that do not come from your code, then I'm afraid, that you will need to write custom babel plugin that removes all `console.x` calls from `node_modules` only.

**Comment by Andarius** [comment]
That's why I'm asking for a solution to remove specifically the logs from `react-native` if we want to.
Again, what if I need the logs from other libs but not the RN ones ?

**Comment by phuongwd** [comment]
@Andarius Did you try this solution https://github.com/babel/minify/issues/934 ?

<img width="1134" alt="Screen Shot 2021-07-01 at 18 12 09" src="https://user-images.githubusercontent.com/2460806/124115332-df86c380-da97-11eb-9789-801227db44cb.png">


its working 💯 

```
module.exports = api => {
  const babelEnv = api.env();
  ...
  const plugins = [];
  if (babelEnv !== 'development') {
    plugins.push('transform-remove-console');
  }
  return {
    presets: ['module:metro-react-native-babel-preset'],
    plugins,
  };
};
```

**Comment by Andarius** [comment]
@phuongwd this will disable all console.log as mentioned above

**Comment by phuongwd** [comment]
@Andarius and this will disable the RN console, this will not appear on Bugsnag

<img width="1303" alt="Screen Shot 2021-07-01 at 19 58 02" src="https://user-images.githubusercontent.com/2460806/124128104-a86bde80-daa6-11eb-89a5-efd0bbd8edea.png">

**Comment by Andarius** [comment]
@phuongwd this will remove all `console.log `or only the one from the `react-native` library ?

**Comment by phuongwd** [comment]
@Andarius this will remove all `console.log` and the log like this 

![](https://user-images.githubusercontent.com/2460806/124128104-a86bde80-daa6-11eb-89a5-efd0bbd8edea.png)

**Comment by phuongwd** [comment]
@Andarius btw I have implemented the remove `console.log` as RN [document](http://reactnative.dev/docs/performance#using-consolelog-statements), it was working.

But I saw `console.log` in [redux-persist](https://github.com/rt2zz/redux-persist/blob/master/docs/migrations.md) `migrate` method did not remove in production recently. See image, that's reason I updated as mentioned in https://github.com/react-native-community/discussions-and-proposals/issues/308#issuecomment-872153032

<img width="1011" alt="Screen Shot 2021-07-01 at 21 37 47" src="https://user-images.githubusercontent.com/2460806/124143073-03a4cd80-dab5-11eb-8a30-12906bb4ae84.png">

**Comment by Andarius** [comment]
@phuongwd  so again, what if I want to remove only the `console.log` from `react-native`?

**Comment by phuongwd** [comment]
@Andarius sorry why do you want to do that?

**Comment by Andarius** [comment]
@phuongwd I don't know, maybe displaying my own data in bugsnag let's say for the sake of the argument.

**Comment by phuongwd** [comment]
@Andarius Let install a third-party package 🎉 

Please see video, BEFORE and AFTER - all log are removed when I did as https://github.com/react-native-community/discussions-and-proposals/issues/308#issuecomment-872153032

https://user-images.githubusercontent.com/2460806/124147151-a448bc80-dab8-11eb-9be0-71f778eb8ffa.mov

**Comment by Andarius** [comment]
why add a third lib for this when I can just check my console.log ?

**Comment by phuongwd** [comment]
IMHO, that's no problem when add a third-party lib, and `babel` is owner.

**Comment by gwmccull** [comment]
You could bind `console.log` to a global variable that you control and then set the original to a null function. That would disable it for all libraries but still allow you to use it for your own uses
