### ISSUE TITLE
How useLayoutEffect behaviour is different in React native from React.js

### ISSUE THREAD

**Issue by EhsanSarshar** [react-native-community/discussions-and-proposals#310]
### Introduction

How useLayoutEffect in React native is different from React.js ?

### Details

as we know useLayoutEffect run after Dom has changed and before browser have a chance to paint.
and the code that run inside useLayoutEffect can manipulate the elements before render.

I am wondered how it behave in react native. after react render phase the changes will pass over bridge and it's rendered on the UI thread. and codes inside useLayoutEffect can't block it. so this effect seems not useful in react native.
would anyone explain me how useLayoutEffect behave in react native. :)

**Comment by AndreiCalazans** [comment]
It is somewhat the same from what I understand. 


On the web, useLayoutEffect runs after the virtual DOM has been updated, not the real DOM. 


On React Native, it behaves similarly. useLayoutEffect runs after the Shadow Tree, similar to the virtual DOM, is updated. 


The layout effects are called here: https://github.com/facebook/react-native/blob/master/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js#L18921


and this is after the tree has been updated as you can see in this comment: https://github.com/facebook/react-native/blob/master/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js#L18908

the actual "UI painting" occurs a little afterwards: https://github.com/facebook/react-native/blob/master/Libraries/Renderer/implementations/ReactNativeRenderer-dev.js#L18939

**Comment by EhsanSarshar** [comment]
@AndreiCalazans I am not much agree with you.
in web useLayoutEffect run after actual DOM updated and before browser found a chance to draw from actual dom to the screen.
in this phase you can **asynchronously** update the the actual DOM inside useLayoutEffect,
and because browser is busy running your Javascript codes inside useLayoutEffect so it wait after all the useLayoutEffect runs completed and then it will be able to draw things on the screen. 

but as of react native running javascript codes **asynchronously** in Javascript thread can't pause shadow thread or UI thread from rendering.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
