### ISSUE TITLE
Generic progress bar, for Android and iOS

### ISSUE THREAD

**Issue by maifeeulasad** [react-native-community/discussions-and-proposals#311]
### Introduction
When we want to show progress-bar on Android, we use this :
```
        <ProgressBarAndroid />
```
And to show progress-view on iOS, documentation says : 
```
        <ProgressViewIOS progress={0.6}/>
```
But the UI isn't same at all. So what about a generic progress-bar. And we also need to check OS before implementing, without checking it throws error.

### Discussion points
 - No OS checking, when coding 
 - Same type UI for all OS
 - More flexibility

**Comment by AndreiCalazans** [comment]
I think React Native already provides the core elements for you to build a universal progress bar, so it does not make sense for it to have this in its core. Plus, there are plenty of options in the open-source community: 
https://callstack.github.io/react-native-paper/progress-bar.html
https://github.com/oblador/react-native-progress
and more.

**Comment by kelset** [comment]
yupm @AndreiCalazans's reply sums up the situation pretty well. Closing.
