### ISSUE TITLE
React Native Web View Uploading File (Image, Video) while app is in an inactivated state (background app)

### ISSUE THREAD

**Issue by louis-nucleus** [react-native-community/discussions-and-proposals#313]
### Introduction

React Native Web View Uploading File (Image, Video) as background

### Details

Could anyone find out the way to upload an image or video content while the app is in an inactivated state (background app)

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
