### ISSUE TITLE
Native Android IOS activity with separate design in react native

### ISSUE THREAD

**Issue by sheshank-2903** [react-native-community/discussions-and-proposals#314]
Can I create separate independent android(java/kotlin) and IOS activity with separate design (.xml file) in react native if yes the how??

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
