### ISSUE TITLE
React Native, Nativescript or Native App. Which's the best for code maintenance?

### ISSUE THREAD

**Issue by GrEg00z** [react-native-community/discussions-and-proposals#315]
We are a small company that need your expert advices concerning the choice of technology for our next Mobile App.

For our first mobile app, 4 years ago, we choiced to use Nativescript Framework (on Angular), because our Web App was coded in Angular 2, and we was really attracked by the perfomances introduced by NS, his native approch and the time saving to developp Android and iOS app.

After 4 years using Nativescript, even if this techno is really great, **we faced several problems during ours scalable/corrective maintenances**, most of time after each NS major version release, or important releases :
- It was almost 100% sure that our app will breaked at compilation or running time, after a new NS major release
- Even by keeping our actual NS version and didn't update anything, the code breaked at some point (from NS Core or NS plugin), and forced us to update our NS Core
- Most of the Nativescript plugins don't stay compatible with next release of NS version, so you are also forced to update all NS plugins
- Sometimes, only one NS plugin breaks the code, so to fix you need to update it, and once is updated, the NS Core breaks, and you are in a infinite loop...

So from one side, you earn a lot of time to create your native Android and iOS app, but from the other side, **you lost a considering time to adapt and fix the code after each NS update.**

The worst of the worst is iOS, because undepending of Nativescript, you have to update Mac OS first, then Xcode, then iOS on devices to be able to run your app (if you have the chance that NS Core don't break the app, otherwise you are ready to become crazy during a week...)

**Now that we are aware about this, we don't want to do the sames mistakes for our next Mobile App, and we would really appreciate some answers about this :**
- Is there a way to avoid all of this "undesired" behaviour on a Nativescript App ?
- Do React Native Framework have the similar problems of scalable/corrective maintenance than Nativescript ? Concerning the Core and Plugins ?
- Is the Native App developpment is the solution to avoid us the maintenance problem ?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions about React Native itself. Yours seems a more general/opinionated conversation, so I don't think it should happen here.

Each solution has different tradeoffs and there are plenty of blogposts from different companies on how they found React Native to be.

**Comment by GrEg00z** [comment]
Hey @kelset, it's not really easy to ask a question about a technology you used for many years without your own opinion, but I understand your point concerning this repo rules.

The only thing I wanted is some advices from react native expert, I really don't want to blame a technology or anything, I'm only here to learn, and maybe bring some "idea" to make react-native better...

I can re-post a question with less personal opinion, if you think that it can be legitime to exists on this repository?
