### ISSUE TITLE
Support native lists

### ISSUE THREAD

**Issue by dylancom** [react-native-community/discussions-and-proposals#316]
Back in 2018 it was written that once changes are completed, it would be straightforward to implement native components like UICollectionView and RecyclerView (https://reactnative.dev/blog/2018/06/14/state-of-react-native-2018#architecture). Is this already the case as I haven't seen any package based on UICollectionView?
Unfortunately FlatList doesn't give the same perf / feeling as native (blank screens on fast scrolling large lists) and the lack of native features such as "index titles" (to scroll fast trough your content: https://developer.apple.com/documentation/uikit/uicollectionviewdatasource/2851455-indextitles).

**Comment by a-eid** [comment]
This is absolutely the most prominent limitation of react native. Implementing native list would be an absolute game changer.

**Comment by kelset** [comment]
The blog you are referring to talks about the "new architecture" which is still a work in progress. You can find more details here:
* https://github.com/react-native-community/discussions-and-proposals/issues/4
* https://github.com/react-native-community/discussions-and-proposals/issues/91
* https://github.com/react-native-community/discussions-and-proposals/issues/40

per each of the major parts.

In the meantime, I believe there are some workarounds you can use with standard flatlists (tweaking the configs of specific lists - see [the docs for more](https://reactnative.dev/docs/optimizing-flatlist-configuration)) or third party packages that provide more "powerful" lists implementations.
