### ISSUE TITLE
Allow `allowsBackForwardNavigationGestures` for new wkwebview

### ISSUE THREAD

**Issue by neurosnap** [react-native-community/discussions-and-proposals#32]
### Introduction

It seems like support for `allowsBackForwardNavigationGestures` is not working with `useWebKit={true}`.  Is there any plan to support this feature?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Your question seems more related to a regression, so I suggest you open a dedicated issue in the main repo.

**Comment by jamonholmgren** [comment]
Since this is webview-related, you will get the best results over there: https://github.com/react-native-community/react-native-webview
