### ISSUE TITLE
add or update keyboard events to relay if keyboard was opened from the current app

### ISSUE THREAD

**Issue by chrisdrackett** [react-native-community/discussions-and-proposals#320]
when using an iOS app on an iPad with split screen its possible that the other open app invoked the keyboard. The issue is that right now to a react native app there is no way to know if the keyboard was opened from your app or another app. Apple provides `keyboardIsLocalUserInfoKey` for determining this and there might be something similar on android.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours is a very specific feature request, so I would recommend instead opening a PR against the main [react native repo](https://github.com/facebook/react-native).

**Comment by chrisdrackett** [comment]
ok, I'll add it there, but it seems very clear on that repo that only bug reports should be posted.

**Comment by kelset** [comment]
that's why I said to submit a PR and not open an issue
