### ISSUE TITLE
Starting a task in background even if the app closed. 

### ISSUE THREAD

**Issue by sameerahmed56** [react-native-community/discussions-and-proposals#322]
### Details

 There is no such package that solves the problem in both ios and android, there are some packages that start task every 15 min but nothing more frequent that 15 min is possible.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
