### ISSUE TITLE
Cant find any worked SAMPLE APP for many days

### ISSUE THREAD

**Issue by peterweb2005** [react-native-community/discussions-and-proposals#324]
it is better worked with expo

but even with react-native-cli, there NONE sample project app worked, spent hours of days

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You seems to be complaining about sample apps (?); when creating a new app via `npx react-native init TestApp` it should work out of the box, if it doesn't I recommend reading the error messages to understand what you are doing wrong, and verify you have followed all the steps required by the [setup in the documentation](https://reactnative.dev/docs/environment-setup).

**Comment by peterweb2005** [comment]
many sample projects in 2 most stars guide, 
but NONE of them work

https://github.com/jondot/awesome-react-native#open-source-apps
https://github.com/reactnativecn/react-native-guide#%E5%BC%80%E6%BA%90app

also NONE work for example keywords in expo site

https://www.google.com/search?q=example+site%3Aexpo.io
