### ISSUE TITLE
Add official support for F#

### ISSUE THREAD

**Issue by sandeepc24** [react-native-community/discussions-and-proposals#325]
### Introduction

I would like react-native to add official support for F#(https://fsharp.org/) using Fable (https://fable.io/).

### Discussion points

1. Add support out of box for F# like there is for TypeScript, there is already this https://github.com/fable-compiler/fable-react-native .
2. Add documentation and examples.

**Comment by safaiyeh** [comment]
@sandeepc24 react-native actually does not have out of the box support for TypeScript, the community maintains the typings and basic template.

FB will maintain React Native core with their toolset and the community should maintain tools outside of that. I would recommend working closer with the fable-react-native maintainers and find ways to ease integrations like making your own templates, docs, etc.
