### ISSUE TITLE
Optimised library for Math functions.

### ISSUE THREAD

**Issue by ahtrahdis7** [react-native-community/discussions-and-proposals#333]
### Introduction
Refer to this post for more details.
https://stackoverflow.com/questions/66080638/optimised-math-functions-for-react-native

### Details

```
export function calculate_angle(v1, v0, v2){
    var x1 = v1[0] - v0[0];
    var x2 = v2[0] - v0[0];
    var y1 = v1[1] - v0[1];
    var y2 = v2[1] - v0[1];
    var dot_product = x1*x2 + y1*y2;
    var cross_product = Math.sqrt((x1*x1+ y1*y1) * (x2*x2 + y2*y2));
    return Math.acos(dot_product/cross_product);
}
```

### Discussion points
!. How to improve/optimise the time taken for such execution.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native) - which already is; I don't see why this issue should be posted here in the first place.
