### ISSUE TITLE
Xcode error: building for iOS Simulator, but linking in object file built for iOS

### ISSUE THREAD

**Issue by jocoders** [react-native-community/discussions-and-proposals#334]
### Details:
React Native app from scratch, was made a few days ago and was launching with out any troubles until today. Get the error after Xcode build:

> /Users/userName/Projects/MyApp/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a(cryptlib.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/userName/Projects/MyApp/ios/Pods/OpenSSL-Universal/ios/lib/libcrypto.a' for architecture arm64clang: error: linker command failed with exit code 1 (use -v to see invocation)
### Discussion points
I have found the cause of the error: This error indicates that OpenSSL is built containing the simulator slice (x86_64) with the iOS device slice (arm64). Combining device and simulator into a single binary file is not a supported build configuration, and never has been. With the introduction of M1 Macs, where the simulator is also arm64 now, Xcode is looking for a arm64 slice intended for the simulator, but finding one only valid for use on a device, and letting you know of this issue.

The solution is to rebuild OpenSSL. If you intend to use it as a a pre-built binary, rather than compiling from source during your app's build, it needs to be inside of an XCFramework. XCFrameworks are purposefully designed to separate device and simulator builds into separate files and avoid this class of error.
### Guys can you tell me please why OpenSSL is built containing the simulator slice (x86_64) in React Native? And how to rebuild OpenSSL? And how do you solve it in your project?

**Comment by hsavit1** [comment]
related https://github.com/facebook/react-native/issues/31006

**Comment by thymikee** [comment]
Let's continue this under https://github.com/facebook/react-native/issues/31006 as @hsavit1 mentioned. This repo is for discussing ideas and implementations, not reporting bugs :)
