### ISSUE TITLE
I was facing run issue in ios simulator

### ISSUE THREAD

**Issue by KaranVakharia789** [react-native-community/discussions-and-proposals#338]
I created new react native project and after run in ios simulator then i have facing below error :
<img width="1058" alt="Screenshot 2021-03-02 at 4 33 57 PM" src="https://user-images.githubusercontent.com/48456265/109639491-3ecdd900-7b75-11eb-800d-6fda9175a705.png">

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
