### ISSUE TITLE
Turbo ModuleRegistry. 

### ISSUE THREAD

**Issue by itechsuite** [react-native-community/discussions-and-proposals#339]
I am new to react native, things are going fine for me till i came across a tutorial that required me to use react-native-reanimated. i have installed using npm but i still get this error " Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'NativeReanimated' could not be found. Verify that a module by this name is registered in the native binary". I have search  several articles and none have showed me properly install. please where am i getting it wrong

**Comment by ahmetbicer** [comment]
Hi, there is additional installation instructions for react-native-reanimated. You need to edit some files and add a babel plugin in order to use reanimated. You can look from [here](https://docs.swmansion.com/react-native-reanimated/docs/installation/)

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
