### ISSUE TITLE
[FlatList] Pass into renderItem() function an extraData prop

### ISSUE THREAD

**Issue by retyui** [react-native-community/discussions-and-proposals#342]
### Introduction

Pass [`extraData`](https://reactnative.dev/docs/flatlist#extradata) to [`renderItem`](https://reactnative.dev/docs/flatlist#required-renderitem) function for SectionList \ FlatList components 

```diff
<FlatList 
+  renderItem={({item, index, separators, extraData}) => { ... }} 
-  renderItem={({item, index, separators}) => { ... }} 
/>;
```

### Details

In function components to reduce a render count of List we have to memorize a `renderItem` function (because on each render in a new function), but if our a `renderItem` function depends on an `extraData` ("selected item" for example) we have to pass it as dependencies to `useCallback` hook

```tsx
const renderItem = useCallback(({ item }) => {...}, [selectedUserId]);
const renderItem = useCallback(({ item, extraData: selectedUserId }) => {...}, []);
```

So, if we will have the ability to get to `extraData` we can write more effective code (from my POV)

Real use-case:

```tsx
function MyUserList({ userIds }) {
  const [selectedId, setSelectedId] = useState(null);

  const renderItem = useCallback(
    ({ item: userId, extraData: selectedUserId }) => (
      <MyUserItem
        onSelect={setSelectedId}
        isSelected={selectedUserId === userId}
        userId={userId}
      />
    ),
    []
  );

  return (
    <FlatList
      // Pure component will re-rendered when `selectedId` or `users` was changed
      extraData={selectedId}
      data={userIds}
      // Never update because was memoized via useCallback with empty dependencies `useCallback(fn, [])`
      renderItem={renderItem}
    />
  );
}
```

### Discussion points

- Is it proposal affect current functionality (breaking changes)?
- Need to update FlatList and SectionList?
- TS and Flow declare `extraData` as `any`. Do we need to handle this case?

**Comment by kelset** [comment]
👋 there - I think you should be posting this as a PR against the main [react native repo](https://github.com/facebook/react-native) so that the code details of such an implementation could be discussed further.

That's the most likely way it can be discussed & reviewed with the FB team.

**Comment by eadogan** [comment]
const renderItem = (selectedUserId, userId) => {(
            <MyUserItem
                onSelect={setSelectedId}
                isSelected={selectedUserId === userId}
                userId={userId}
            />
        );
    }
  
    return (
      <FlatList
        keyExtractor={item => item.toString()}
        data={userIds}
        renderItem={renderItem.bind(this, userIds.id)}
      />
    );

**Comment by retyui** [comment]
RN PR: https://github.com/facebook/react-native/pull/32195
