### ISSUE TITLE
Proposal: adding/expanding file sharing to/in the Share API

### ISSUE THREAD

**Issue by taeh98** [react-native-community/discussions-and-proposals#344]
### Introduction

Hello, I am writing to propose adding/expanding file sharing to/in [the existing Share API](https://reactnative.dev/docs/share).

### Details

File sharing is obviously a common function used by a massive number of mobile apps, so it makes sense to provide a cross-platform way to do it as a core part of React Native. After all, providing accessible cross-platform commonality is the whole point of React Native. I think it makes sense, therefore, to implement a common method by which to do this as part of React Native. You can strictly already implement file sharing with Share.share() on iOS, but the functionality is limited. For example, you cannot include a message with a file. Even that aside, this functionality is still only provided to iOS devices.

### Discussion points

There are existing third-party libraries that allow users to share files, but they are not always usable nor always implement all the functionality one may desire. For example, expo-sharing can be used by Expo users but does not allow you to send a message with a file, such as a caption for a photograph providing its context or extra information. I think that this is an important requirement. The library react-native-share does let you do this, but it is not compatible with Expo.

As a core piece of common functionality used by many apps, I think it makes sense for file sharing to make up part of React Native's own APIs. I think it could be implemented by renaming the existing share() method to shareText() and making a new shareFile() method that implements file sharing. This would distinguish the two and allow relatively easy and intuitive changes to existing code to adjust for the change in the API.

The shareFile() function could have the following signature:
`shareFile(url: string, title?: string, message?: string, options?: ShareOptions): Promise<ShareAction>`

Alternatively, you could integrate the message parameter as a new field into the existing option with url and title in the ShareContent type. This type already allows for the url property on iOS and would allow for immediate integration with the existing share() method. This would have better backwards compatibility.

Going forward, however, I think it would be more intuitive to have the functions of sharing text messages and files separated into different methods so it is immediately clear what type of content you are sharing in a piece of code. Also note that the existing url property is still currently also usable on iOS, and does not allow users to send text messages along with files, as previously discussed.

With the above shareFile() signature, shareText() would have the following signature:
`shareText(message: string, title?: string, options?: ShareOptions): Promise<ShareAction>`

This is essentially a simplified version of the existing share() method so doesn't warrant any in-depth explanation.

Thank you for your time and consideration!

**Comment by TheSavior** [comment]
> There are existing third-party libraries that allow users to share files, but they are not always usable nor always implement all the functionality one may desire. For example, expo-sharing can be used by Expo users but does not allow you to send a message with a file, such as a caption for a photograph providing its context or extra information. I think that this is an important requirement. The library react-native-share does let you do this, but it is not compatible with Expo.

> As a core piece of common functionality used by many apps, I think it makes sense for file sharing to make up part of React Native's own APIs. I think it could be implemented by renaming the existing share() method to shareText() and making a new shareFile() method that implements file sharing. This would distinguish the two and allow relatively easy and intuitive changes to existing code to adjust for the change in the API.

As part of our lean-core effort, we've been trying to keep the core of React Native as small as possible. There are many experiences that are a common part of React Native applications, and many of those were included in React Native. However, development of those was slow going as Facebook didn't use and thus couldn't support that functionality. I'd highly recommend working to improve 3rd party modules (or forking them to improve what you need).
