### ISSUE TITLE
Whiteboard Share on Video call

### ISSUE THREAD

**Issue by dalbeer22g** [react-native-community/discussions-and-proposals#345]
Is there any possibility for sharing Whiteboard on Video Call. I want to make an app, where Teacher or Student can share whiteboard durning video call

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
