### ISSUE TITLE
Using React-Native code for Web

### ISSUE THREAD

**Issue by userException** [react-native-community/discussions-and-proposals#352]
### Introduction
Running and deploying my react native app on web

### Details
I have built an app for iOS and Android using react native. Now its time to see its compatibility with the web. As far as the write once use everywhere motto is concerned, I was expecting an official documentation to just add some packages which were web-dependent and simply run my code on web.

Worst case scenario which I had in my mind was that there could be some packages which were not available for web, so I would have to write platform-specific code with file naming convention (login.web.js, login.ios.js, login.android.js) and use some checks with the Platform module (Platform.OS === 'ios').

I am not able to find any official documentation for how to go about and use my react native code to run and deploy on web.

**Comment by a-c-sreedhar-reddy** [comment]
Hi Would https://github.com/necolas/react-native-web this help?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
