### ISSUE TITLE
ScrollView Extension

### ISSUE THREAD

**Issue by reberthkss** [react-native-community/discussions-and-proposals#361]
### Introduction

I want to use the `extension` functionality in typescript to add a method to `ScrollView`.

### Details
I had to try this behavior using this article as reference: https://medium.com/my-coding-life/extension-method-in-typescript-66d801488589 . And got this:
```
import {NativeScrollEvent, ScrollView} from "react-native";

declare module 'react-native' {
    export interface ScrollView {
        isCloseToBottom(nativeScrollEvent: NativeScrollEvent): boolean
    }
}


ScrollView.prototype.isCloseToBottom = function ({layoutMeasurement, contentOffset, contentSize}: NativeScrollEvent): boolean {
    const paddingToBottom = 1000;
    return layoutMeasurement.height + contentOffset.y >=
        contentSize.height - paddingToBottom;
}

```

### Discussion points

Everything about typescript is ok, but when I try to use the `isCloseToBottom` method, I got the following error:

```
TypeError: undefined is not an object (evaluating '_reactNative.ScrollView.prototype')
```

**Comment by TheSavior** [comment]
I wouldn't recommend modifying core components in this way. If you build up a library this way, if we make changes in core that conflict then your library will be broken.

Consider having your library take a ref to a ScrollView instead.
