### ISSUE TITLE
Integrating react-native-web to an Existing React-Project without using expo-cli

### ISSUE THREAD

**Issue by nairsajjal** [react-native-community/discussions-and-proposals#386]
Introduction
My team and I are trying to re-use existing code from React-Native Projects for React (Web) projects, the documentation we used to follow this particular line-of-action was https://necolas.github.io/react-native-web/docs/installation/
This is the documentation for the package React-Native-Web, However, you might observe that while installing the react-native-web package the default CLI used in the installation steps is Expo-CLI, this is a tool we are trying to prevent using. Expo-CLI has several limitations which we want to avoid at this phase of our development process!
Limitations of EXPO-CLI - https://docs.expo.io/introduction/why-not-expo/

DETAILS -
To install react-native-web package in an existing project -
In the repo. of the existing project, we execute the following commands -
npm install react-dom react-native-web
npx expo-cli start

Now this works fine, but my team has decided not to use the expo-cli, expo-cli has a lot of limitations, which we are trying to avoid in production, and we are leaning towards using bare react-native cli only. 
One resource that I had suggested was this https://medium.com/@aureliomerenda/create-a-native-web-app-with-react-native-web-419acac86b82

However this is not official documentation, and my team was looking for an official(community-supported) way of doing the exact same thing that has been done in the above blog!

Conclusion
In the official documentation, The only methodology available is that of using expo-cli, an alternative way to do the same, i.e integrating react-native-web in an existing react-native project in production will be appreciated!
We had also raised an issue here - https://github.com/react-native-community/discussions-and-proposals/issues/352
But it was shunned away, quite quickly, I hope the community understands our concerns first fully and then closes this issue!

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions on React Native. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

This is not a support forum to ask questions, I hope you can understand that :)
