### ISSUE TITLE
Last 30 days react native vs flutter. [ PR 20 Merged 0 vs PR 559 Merged 473 ]

### ISSUE THREAD

**Issue by gaodeng** [react-native-community/discussions-and-proposals#395]
More and more developers are moving to the flutter platform. I really hope the new architecture of RN will be released soon to change the current situation. Even if it can't be released anytime soon, please give us some information about how it is going.

### PR 20 Merged 0
![flutter](https://user-images.githubusercontent.com/1118249/124344717-87ba9a80-dc06-11eb-883c-6d8496815913.png)

### PR 559 Merged 473
![flutter](https://user-images.githubusercontent.com/1118249/124344719-8be6b800-dc06-11eb-99eb-e047db3565d7.png)

**Comment by hyochan** [comment]
I was on Flutter but back to react-native again because I missed awesome tools like `relay`, `fbt` which are also from `Facebook`.

I hope RN gets more attention.

**Comment by TheSavior** [comment]
I don't think that statistic is correct for React Native. Because of the way our tooling works, PRs don't show up as "merged". They get closed with a linked commit on main. See this PR for an example. https://github.com/facebook/react-native/pull/31741

We do hope to share more soon as we are hard at work on all of our architecture work. You can see that progress by seeing the number of commits the team has been landing. Keep an eye on the other discussions for any updates.

**Comment by hyochan** [comment]
Definitely, I was very surprised but now it makes sense! Always thanks for the hard work :+1:

**Comment by gaodeng** [comment]
But there is still a relatively large difference in the number of commits per day

![commit-rn](https://user-images.githubusercontent.com/1118249/124347404-32d35000-dc17-11eb-8b2e-9e8c931089bd.png)
![commit-flutter](https://user-images.githubusercontent.com/1118249/124347408-3666d700-dc17-11eb-8694-ae2ce207f7ef.png)

**Comment by hyochan** [comment]
> But there is still a relatively large difference in the number of commits per day
> 
> ![commit-rn](https://user-images.githubusercontent.com/1118249/124347404-32d35000-dc17-11eb-8b2e-9e8c931089bd.png)
> ![commit-flutter](https://user-images.githubusercontent.com/1118249/124347408-3666d700-dc17-11eb-8694-ae2ce207f7ef.png)

Comparing commits is not that meaningful as long as it is taken care and moving on the right track.

However I think there could be a good strategy to brought up to gain more contributors and not just the users. I think this can happen soon tough when new architecture is landed.

**Comment by matt-oakes** [comment]
Remember as well that there was a big effort with “Lean Core” to move a lot of code out from the repo you’re referencing into separate repos.

Flutter meanwhile seems to contain most of its code in the repo you referenced and the plugins one. 

For a clearer view of activity you should also take a look at the React Native CLI, Metro, core React, and the Yoga repos. All of those parts make up the core of React Native and it’s dev tools. The equivalents for Flutter are mostly in one repo from what I can tell.

I do agree about needing to encourage outside contributions though. I’ve had a PR in limbo on the React Native repo for months now.

**Comment by gaodeng** [comment]
> Remember as well that there was a big effort with “Lean Core” to move a lot of code out from the repo you’re referencing into separate repos.
> 
> Flutter meanwhile seems to contain most of its code in the repo you referenced and the plugins one.
> 
> For a clearer view of activity you should also take a look at the React Native CLI, Metro, core React, and the Yoga repos. All of those parts make up the core of React Native and it’s dev tools. The equivalents for Flutter are mostly in one repo from what I can tell.
> 
> I do agree about needing to encourage outside contributions though. I’ve had a PR in limbo on the React Native repo for months now.

It looks like you know a lot about react native, but your statement that flutter put everything in one big code repository is definitely wrong, just check out flutter's github account page.

It doesn't really matter which platform is more active, what people really want is more transparency and an approximate timeline for the new architecture. If I remember correctly, the original plan was to release in 2020, maybe covid-19 affected the development progress, but it's been a year, at least release a new revised schedule, rather than just let everyone wait endlessly!
