### ISSUE TITLE
RCTTextView Should Use UITextView

### ISSUE THREAD

**Issue by netshade** [react-native-community/discussions-and-proposals#408]
### Introduction

I want to understand the motivations behind `RCTTextView` inheriting from `UIView` rather than inheriting / composing its functionality with [`UITextView`](https://developer.apple.com/documentation/uikit/uitextview). This issue is to start a discussion to understand and enumerate the benefits of iOS text being displayed through `UITextView`
### Details

Text in React Native is displayed through the `<Text />` component. On Android, this is rendered via [`ReactTextView.java`](https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTextView.java), a subclass of [`AppCompatTextView`](https://developer.android.com/reference/androidx/appcompat/widget/AppCompatTextView) which uses the platform appropriate way of displaying text on the screen. On iOS the method of rendering `<Text />` nodes uses [`RCTTextView.m`](https://github.com/facebook/react-native/blob/main/Libraries/Text/Text/RCTTextView.m), which [renders with `TextKit`](https://github.com/facebook/react-native/blob/main/Libraries/Text/Text/RCTTextView.m#L97-L164) but *does not* use `UITextView`. This is unfortunate because many of the system services that are helpful for text ( "Translate" added in iOS 15, "Look Up", "Share", text selection, platform accessibility helpers ) must either be recreated or not supported.

It would be ideal if the implementation of `RCTTextView` instead used a platform appropriate text view to display the desired text to take advantage of built in text services.

 ### Discussion points

* **How did it get this way?** The [implementation](https://github.com/facebook/react-native/tree/main/Libraries/Text/Text) of `RCTTextView` is complex enough that I suspect there is an *extremely good reason* this approach was not originally done. This implementation is long lived within the codebase, and it's hard to understand *why this approach was taken* based on the commit history. Any help in understanding *why* the implementation avoids `UITextView` would be useful in determining if changing the approach is feasible.
* **Is changing `RCTTextView` implementation even possible?** It is a fundamental component, and I don't know how enmeshed it has become with the rest of the codebase.
* **Is this desirable?** While I think that changing the implementation to integrate more cleanly with the platform tools is desirable, the current implementation has taken the opposite position by virtue of adding an "emulation" of the platform tools with the `selectable` implementation on iOS ( using the [`UIMenuController` approach](https://github.com/facebook/react-native/blob/main/Libraries/Text/Text/RCTTextView.m#L227-L244) ). It may be that it's not worth it to have access to those platform tools.

I should note that I'm not well versed in the `react-native` codebase, so any corrections to my knowledge would be helpful and appreciated.

**Comment by shergin** [comment]
Historically, using UITextView was just somewhat between impractical and unfeasible. In reality, it does not give many benefits compared to other still idiomatic but more low-level APIs RN uses. This boils down to these aspects:

### Features
Most (probably all) of the features that UITextView provides out of the box are quite easy to implement manually and often require customization that UITextView does not allow. This certainly includes accessibility features, decoration features, text layout customizations, and so on. I mean all this out-of-the-box accessibility features will not work as it might be specified in component props.

React Native has a ton of features related to components' composability and layout. It's not obvious, but as any web-like renderer, it does have at least two layout systems: flex-box and inline. Inline one is as full-featured as flex-box one. You can put any arbitrary component inside the text and this will work. It's probably possible to implement with UITextView but it will not be as (relatively) straightforward as with lower-level APIs.

### Performance
This probably changed over the years, but in older versions of iOS, UITextView has some performance drawbacks. Being a "big package" component, it does not work best in conditions where it needs to render a huge chunk of text or when we need to render hundreds of small text elements.

### Predictability
React Native has an off-main-thread (any thread, to be precise) layout system. This requires the system to be able to measure text fragments on any thread. And these measurements must be 100% accurate, missing even a small fraction of a point will mess up all the layout. And, with UITextView being a "black box" package, we cannot predict all the text layout behaviors, so we cannot make the measuring to be precise.

---
Rendering the text on the UI thread is just a few hundred lines of code. The rest is off-main-thread complexity that cannot be solved by UITextView.

Enabling all the features that were added in later iOS versions really should not be tricky. It's a bummer that we need to do some manual work every year but that's the reality of building a highly customizable UI framework.

**Comment by netshade** [comment]
Thanks for this great response! There's one particular part that would be helpful for me to understand, your statement:

> Rendering the text on the UI thread is just a few hundred lines of code. The rest is off-main-thread complexity that cannot be solved by UITextView.

Would it be right for me to interpret this as:  at a coarse level, a `UITextView` combines a level of text layout and flow with rendering that is split across several components in the `react-native` codebase.  `RCTTextView` is merely the tip of the text iceberg, so to speak?

And, I feel like I should note here, your comment: 

> Enabling all the features that were added in later iOS versions really should not be tricky. It's a bummer that we need to do some manual work every year but that's the reality of building a highly customizable UI framework.

I think it bears worth noting here that, at least as far as I can tell, this is "barely" true. My current understanding is that many of the features I allude to here ( text selection and system translation, notably ) lack public APIs and remain "captured" within `UITextView`. 

In any case, thanks again for taking the time to describe the trade-offs here, it's very appreciated. Closing this issue.
