### ISSUE TITLE
Will there be a PermissionsAndroid for MANAGE_EXTERNAL_STORAGE in the future release?

### ISSUE THREAD

**Issue by unit-002** [react-native-community/discussions-and-proposals#432]
### Will there be a PermissionsAndroid for MANAGE_EXTERNAL_STORAGE in the future release?

For the new  permission for Android API 30 and above which requires MANAGE_EXTERNAL_STORAGE permission to access and manage all files in the storage, React Native still does not have the support for this.

Will it be implemented in the future release?

**Comment by gwmccull** [comment]
I'm surprised that `PermissionsAndroid` hasn't been removed from React Native as most of the packages like that have been migrated to the community. I've been using `react-native-permissions` for permissions but according to this issue, `MANAGE_EXTERNAL_STORAGE` can't be requested, it must be declared in the Android Manifest

https://github.com/zoontek/react-native-permissions/pull/587

**Comment by unit-002** [comment]
I see thanks for the info
