### ISSUE TITLE
Implement `useIsKeyboardVisible` hook

### ISSUE THREAD

**Issue by xegulon** [react-native-community/discussions-and-proposals#455]
### Introduction

It could be great to have a hook telling us is the keyboard is visible or not. I think it can be implemented with no big effort using the code presented here: https://stackoverflow.com/a/51606247/11348232

This code is based only on: https://reactnative.dev/docs/keyboard

### Details

It would be used that way: 

```js
const isKeyboardVisible = useIsKeyboardVisible()
```

**Comment by xegulon** [comment]
Yeah it could be good to do a PR. Are there guidelines for that?

**Comment by liamjones** [comment]
@xegulon Yep: https://github.com/facebook/react-native/blob/main/CONTRIBUTING.md#contributing-code

**Comment by xegulon** [comment]
do you think it would be difficult to call the hook like that @gwmccull :
```js
const { isVisible, keyboardHeight, dismiss } = useKeyboard()
```
I mean is implementing the `keyboardHeight` difficult?

**Comment by gwmccull** [comment]
sorry, I'm not sure how difficult it is to do the keyboard height. I feel like I may have seen that in other libs though so you may be able to find an example

**Comment by xegulon** [comment]
It seems this hook already exists: 

https://stackoverflow.com/a/63407895/11348232

https://github.com/react-native-community/hooks#usekeyboard
