### ISSUE TITLE
React Native CLI APK Building Process

### ISSUE THREAD

**Issue by manshaaazar** [react-native-community/discussions-and-proposals#459]
During the APK building process in react native CLI. I am getting below error even I also provided the apikey

*******************************************************************
 Task :app:processBugsnagE2eFossReleaseManifest FAILED
[stderr] * What went wrong:
[stderr] Execution failed for task ':app:processBugsnagE2eFossReleaseManifest'.
[stderr] > Bugsnag: Your AndroidManifest.xml is missing one or more of
[stderr]   apiKey/versionCode/buildUuid/versionName/package, which are required to upload to bugsnag.
[stderr]   apiKey=null
[stderr]   versionCode=999999999
[stderr]   buildUUID=357ba303-7f9a-48cd-a4b2-57ec880f9a9b
[stderr]   versionName=4.24.0
[stderr]   applicationId=botx7.Chat

**Comment by cortinico** [comment]
> You are missing some steps from bugsnag setup, this is not a React Native issue.

The answer provided by @radko93 is correct. Please open an issue on BugSnag repo 👍

**Comment by manshaaazar** [comment]
Thank you @radko93
