### ISSUE TITLE
word-spacing prop of Text component

### ISSUE THREAD

**Issue by hackerart** [react-native-community/discussions-and-proposals#470]
### Introduction

I need somehow detect word-spacing param of loaded Font in my React Native app. Or another way to solve my problem is to define word-spacing for Text component on my own. Is there any way to do so?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
