### ISSUE TITLE
I need help (Swipeable compoenet does not work)

### ISSUE THREAD

**Issue by Yasir12598** [react-native-community/discussions-and-proposals#471]
I am new to React-Native, using the swipeable componet (renderRightAction) to render the new "View" for delete purpose. after swiping right it does not work. I mean it remains same after using swipeable component. May be I am missing some trick.
It gives WARN, which below I have mentioned.

```
import React from 'react';

import { 
  View,
  Text,
  StyleSheet,
  
 } from 'react-native';

 import Swipeable from 'react-native-gesture-handler/Swipeable';

function App(props) {
  return (
    <Swipeable renderRightActions={()=> (
      <View style={{backgroundColor:'red', width:70}}>

      </View>
    )}>
    <View style={styles.container}>
      <Text style={styles.text}> Swipe right to Delete</Text>
    </View>
    </Swipeable>
  );
}


const styles = StyleSheet.create({
  container:{
    flexDirection:"row",
    backgroundColor:'lightgray',
    width: "100%",
    height:70,
    justifyContent:'center',
    alignItems:'center',
  },
  text:{
    fontWeight:'bold',
    fontSize:18,
  }
})
export default App;

```

WARN [react-native-gesture-handler] Seems like you're using an old API with gesture components, check out new Gestures system!
PanGestureHandler@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.swipeabletest&modulesOnly=false&runModule=true:110702:38
Swipeable@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.swipeabletest&modulesOnly=false&runModule=true:110053:36
App
RCTView
View
RCTView
View
AppContainer@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.swipeabletest&modulesOnly=false&runModule=true:77006:36
swipeableTest(RootComponent)@http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.swipeabletest&modulesOnly=false&runModule=true:83408:28

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
