### ISSUE TITLE
Support building react-native apps with BUCK

### ISSUE THREAD

**Issue by dehlen** [react-native-community/discussions-and-proposals#474]
### Introduction

My understanding is that Facebook uses Buck internally, it would be great if external developers had an example Buck configuration for React Native. I currently work on a hybrid mobile application. We have multiple native screens written in Swift/Kotlin and a lot of JS/TS code for shared react-native components. Since we have several native features/screens in our app the native part changes frequently which causes rebuilding all the native dependencies (also RN). This ultimately leads to 2 main problems:

1. We experience pretty long build times due to the fact that we have to rebuild the whole project pretty much every time, on CI, when changing branches, etc.
2. All developers need to manage a native build setup locally. This does not only include working on a Mac and downloading Xcode but also to familiarize themselves with Ruby, Cocoapods, Bundler, iOS and Android Native tooling. This results in broken builds, increased support requests, broken builds and a bad developer experience especially for newcomers to the project or people working very infrequent on the project.

### Details

My understanding is that 
1. Facebook already uses BUCK internally f.e to build the RNTester app on CI
2. BUCK, being a hermetic build system with options to remotely cache build artifacts could definitely help in speeding up the build as well as replacing a lot of the toolchain with a single buck build command.

As I see in the current GitHub repo a lot of the used BUCK rules are Facebook internal-only and are currently implemented with a simple "pass" command.

### Discussion points

I would like to discuss whether it is possible for BUCK to be supported for third party developers and if not why this is the case and if there are solutions to our problems apart from this.

**Comment by leotm** [comment]
Exactly Buck's used internally for testing our Android app on Ubuntu 20.04 (x86_64) along with Gradle during these parts of our CircleCI workflow:

- _test_android_
  - `mkdir -p ./reports/{buck,build,junit,outputs}`
  - _Restoring Buck cache_
    - otherwise `git clone https://github.com/uber/okbuck.git ~/okbuck --depth=1`
  - _Saving Buck cache_, _Validating Buck cache_
  - [Downloading deps](https://github.com/facebook/react-native/blob/main/scripts/circleci/buck_fetch.sh)
  - Building our Android app
     - `buck build ReactAndroid/src/main/java/com/facebook/react`
     - `buck build ReactAndroid/src/main/java/com/facebook/react`
   - Then compiling native libs for unit and integration tests
     - `./gradlew :ReactAndroid:packageReactNdkLibsForBuck`
         - ... `> Task :ReactAndroid:packageReactNdkDebugLibsForBuck`, `> Task :ReactAndroid:packageReactNdkLibsForBuck`
    - Running unit tests
      - `buck test ReactAndroid/src/test/... --xml ./reports/buck/all-results-raw.xml`
    - Running instrumentation tests
    - Collecting test results
- _test_android_rntester_
  - `./gradlew :packages:rn-tester:android:app:assembleDebug`
    - ... `> Task :ReactAndroid:packageReactNdkDebugLibsForBuck` ...

AFAIK officially supporting more build tools on top of Gradle is more internal dev effort than Facebook are currently prepared for

I'd love the option too, so went ahead and voted for it: [Add Buck as a build option](https://react-native.canny.io/feature-requests/p/add-buck-as-a-build-option)

We're in the same situation with FastLane
- https://github.com/fastlane/fastlane/issues/7990

So I'm considering  building a Buck plugin there for us too

**Comment by dehlen** [comment]
Exactly I saw these issues/posts as well but wanted to discuss this further since it has been several years since then. I think the community would greatly benefits from the feature set BUCK offers as well as having an alternative to the currently maintained tooling. Of course I understand that this comes with more maintenance and support requests. I found https://github.com/rockwotj/prebuilt-rn on GitHub which builds an xcframework to use react-native in a Bazel build. This might be a good starting point (at least for the iOS build).

**Comment by cortinico** [comment]
@dehlen Thanks for raising this.

> Officially supporting more build tools on top of Gradle is more bandwidth than Facebook are still currently prepared for

That's essentially the point of the whole discussion.

You're right in saying that we're currently using BUCK internally to build RN apps. However, we're not actively supporting building with BUCK in the OSS space. We strive to provide a setup that is as close as possible to the tools that are familiar to each ecosystem (Gradle for Android, Cocoapods for iOS, etc).

What I mean by this is that we're testing on CI and during our release process only the Gradle/CocoaPods setup. You can use BUCK and the BUCK files we publish alongside, but we don't offer any support on those.

Moreover, using BUCK for Android in OSS is getting harder as you'll need a binary which is compatible with Java 11 (as it's now a requirement for Android) while the published versions of BUCK are not. This would force our users to compile BUCK from source, which is something we'd like to avoid (but we have to do on our CI https://github.com/react-native-community/docker-android/blob/616d29a069c02fce2084f9d0855757e5c0a6ad14/Dockerfile#L1-L16).

Hope this clarifies.

> We experience pretty long build times due to the fact that we have to rebuild the whole project pretty much every time, on CI, when changing branches, etc.

This is something we're aware of. Please take a look at this guide that addresses those problems specifically https://reactnative.dev/docs/build-speed

> All developers need to manage a native build setup locally. This does not only include working on a Mac and downloading Xcode but also to familiarize themselves with Ruby, Cocoapods, Bundler, iOS and Android Native tooling.

We're working on making the build layer as thin as possible so you won't have to handle Gradle/Cocoapods code at all. 

> BUCK, being a hermetic build system with options to remotely cache build artifacts could definitely help in speeding up the build

At least for Android, you can use the Remote Build cache for Gradle as well.
https://docs.gradle.org/current/userguide/build_cache.html

**Comment by cortinico** [comment]
Closing as we don't foresee using Buck (now Buck2) for OSS projects in the immediate future. We will revisit should things change.

**Comment by leotm** [comment]
> Moreover, using BUCK for Android in OSS is getting harder as you'll need a binary which is compatible with Java 11 (as it's now a requirement for Android) while the published versions of BUCK are not. This would force our users to compile BUCK from source, which is something we'd like to avoid (but we have to do on our CI https://github.com/react-native-community/docker-android/blob/616d29a069c02fce2084f9d0855757e5c0a6ad14/Dockerfile#L1-L16).

afaik Buck2 solves both problems being rewritten in Rust no longer reliant upon Java and with bi-monthly pre-built binaries avoiding compiling Buck2 from source

**Comment by leotm** [comment]
> We're working on making the build layer as thin as possible so you won't have to handle Gradle/Cocoapods code at all.

i suppose expo continuous native generation solves this now

**Comment by cortinico** [comment]
> afaik Buck2 solves both problems being rewritten in Rust no longer reliant upon Java and with bi-monthly pre-built binaries avoiding compiling Buck2 from source

Yup those are fair points. The original discussion was related to Buck1. With Buck2 being released and maturing quickly, we're constantly exploring if/how/when that would make sense to be integrated in our toolchain
