### ISSUE TITLE
Ternary + comma-delimited blocks

### ISSUE THREAD

**Issue by philihp** [react-native-community/discussions-and-proposals#476]
```js
  didChange
    ? ((workInProgress = processChildContext(
        workInProgress,
        type,
        previousContext
      )),
      (instance.__reactInternalMemoizedMergedChildContext = workInProgress),
      pop(didPerformWorkStackCursor),
      pop(contextStackCursor),
      push(contextStackCursor, workInProgress))
    : pop(didPerformWorkStackCursor);
  push(didPerformWorkStackCursor, didChange);
```
https://github.com/facebook/react-native/blob/41cbccd98dd6c98d1f662674164cf455105a1359/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js#L2110-L2121

For the life of me, I can't understand what would lead the author of this block to write this code this way. It seems to be something squashed from [bac9e6959367ca3420f2318c1970758f5618d960](https://github.com/facebook/react-native/commit/bac9e6959367ca3420f2318c1970758f5618d960), so unclear what discussions there were behind it when it was committed.

I want to assume that there is a good reason for it. Are there performance optimizations from doing it this way? Is someone practicing their golf game?

**Comment by cortinico** [comment]
The code you see is coming from a generated file, coming from a bundling of react-reconciler.  The corresponding code is here: https://github.com/facebook/react/blob/a724a3b578dce77d427bef313102a4d0e978d9b4/packages/react-reconciler/src/ReactFiberContext.old.js#L267-L289

So please open an issue against facebook/react if the code is still unclear 👍
