### ISSUE TITLE
small increment of value: run `npx react-native-codegen` to generate stub implementations based on the spec

### ISSUE THREAD

**Issue by andrestone** [react-native-community/discussions-and-proposals#479]
### Introduction

TurboModules are great, but why don't we improve DX a bit by autogenerating boilerplate code?
### Details

When creating a new TurboModule, aside from writing the spec we have to write the implementation code. Why not let `react-native-codegen` generate stub implementations for the interfaces defined in the spec? Looking at the codebase, seems pretty straight-forward. Writing boilerplate code is never pleasant and having those stubs there would help ensuring consistency.

What am I missing?

**Comment by kelset** [comment]
sorry for being "that guy"; I think this question would be better suited for this discussion section: https://github.com/reactwg/react-native-new-architecture/discussions

**Comment by cortinico** [comment]
> TurboModules are great, but why don't we improve DX a bit by autogenerating boilerplate code?

As @kelset mentioned, this is a topic for the New Architecture working group. You should have access to post a question there.

To shortly answer to your question: this idea was already shared in the past and is tracked on our end. Happy to share more insights about it in the WG. Closing here
