### ISSUE TITLE
Importing outside of the source directory is not allowed

### ISSUE THREAD

**Issue by quantuminformation** [react-native-community/discussions-and-proposals#483]
### Introduction

Importing outside of the source directory is not allowed. I'm surprised this is still an issue from my first discovery of it around seven years ago.

### Details

React Native projects are unable to access files above the src root. I can't from the src dir go to import some module from ../../SharedBusinessLogic

I need to do this as the React Native template is in a repository with multiple projects needing to share the same non-framework specific business logic.

ie

repository:
```
/

    /SolidjsProject
    /CloudProject
    /ExpoProject
    /SharedBusinessLogic  (no package.json)
```

### Discussion points

Many other frameworks (ie vite) allow you to import outside the source folder, I don't understand why I am stuck here.
I also don't want to use a monorepo to share this code as it is overkill.

Here is my shared code example:

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/216566/170257968-a5b53500-f2a3-410a-9b3a-e6a1c1c9b46c.png">

Originally I posted on StackOverflow: https://stackoverflow.com/questions/72247564/react-native-expo-unable-to-access-files-above-the-root?noredirect=1#comment127870869_72247564

**Comment by 3GOMESz** [comment]
Basically this can be solved just by making some changes in the metro configuration file

**Comment by 3GOMESz** [comment]
Here's an example I created that also solves the problem of duplicate React/RN imports...
Feel free to use, I think this will save you a few hours of research 😀 👍 

**metro.config.js**
```
const path = require('path');
const exclusionList = require('metro-config/src/defaults/exclusionList');

const moduleRoot = path.resolve(__dirname, '../..');

module.exports = {
  watchFolders: [moduleRoot],
  resolver: {
    extraNodeModules: {
      react: path.resolve(__dirname, 'node_modules/react'),
      'react-native': path.resolve(__dirname, 'node_modules/react-native'),
    },
    blockList: exclusionList([
      new RegExp(`${moduleRoot}/node_modules/react/.*`),
      new RegExp(`${moduleRoot}/node_modules/react-native/.*`),
    ]),
  },
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};

```

**Comment by 3GOMESz** [comment]
If you're interested, I also recommend that you search for [Yarn Workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/)

**Comment by 3GOMESz** [comment]
Many people experience something similar in React Web, the difference is that in this case you reconfigure webpack/babel. I believe this is all done for security reasons.

**Comment by quantuminformation** [comment]
Many thanks, I just had time today to look at this

I changed `const moduleRoot = path.resolve(__dirname, '../');` as I just need one level higher, but I still get

<img width="442" alt="image" src="https://user-images.githubusercontent.com/216566/174260394-3e771464-1be3-4f43-ac21-daa65baf2165.png">

<img width="1772" alt="image" src="https://user-images.githubusercontent.com/216566/174260583-f80cf6ab-4ba8-4227-9ea7-f9152454c4eb.png">

**Comment by quantuminformation** [comment]
Edit, nvm, it works now just by renaming the file to .ts and not using your metro config, looks like it wasn't an issue then?

**Comment by 3GOMESz** [comment]
> Edit, nvm, it works now just by renaming the file to .ts and not using your metro config, looks like it wasn't an issue then?

No, it was never a problem, both React and React Native have always allowed this, it just doesn't come as default behavior when you use tools to create a new project...

**Comment by quantuminformation** [comment]
how do you un-default it though?

**Comment by 3GOMESz** [comment]
> how do you un-default it though?

Creating your own tool that generates configuration files and folder structure like `create-react-app` or `create-react-native-app`, just like `expo-cli` does...

**Comment by 3GOMESz** [comment]
By default, `create-react-native-app` gives you a default configuration designed for security and that works for the vast majority of projects. As I said, it's up to you to change the settings on each project individually or create a tool that generates the files as your need

**Comment by quantuminformation** [comment]
so by default expo allows your to import outside folders?

**Comment by 3GOMESz** [comment]
> so by default expo allows your to import outside folders?

I just exemplify saying that `expo-cli` generates different files compared to `create-react-native-app`, if your intention is every time you create a project you can import outside the root directory by default, you need to create your own tool that generates the pre-configured base files the way you want, otherwise use a ready-made tool (like CRNA) and change the `metro.config.js` as I showed above whenever you start a new project. 

Again, your issue is not a React Native problem, project initialization tools create base files and you are free to configure them.

**Comment by 3GOMESz** [comment]
> Here's an example I created that also solves the problem of duplicate React/RN imports... Feel free to use, I think this will save you a few hours of research 😀 👍
> 
> **metro.config.js**
> 
> ```
> const path = require('path');
> const exclusionList = require('metro-config/src/defaults/exclusionList');
> 
> const moduleRoot = path.resolve(__dirname, '../..');
> 
> module.exports = {
>   watchFolders: [moduleRoot],
>   resolver: {
>     extraNodeModules: {
>       react: path.resolve(__dirname, 'node_modules/react'),
>       'react-native': path.resolve(__dirname, 'node_modules/react-native'),
>     },
>     blockList: exclusionList([
>       new RegExp(`${moduleRoot}/node_modules/react/.*`),
>       new RegExp(`${moduleRoot}/node_modules/react-native/.*`),
>     ]),
>   },
>   transformer: {
>     getTransformOptions: async () => ({
>       transform: {
>         experimentalImportSupport: false,
>         inlineRequires: true,
>       },
>     }),
>   },
> };
> ```
> 
> ⚠️ `exclusionList` is only needed if you have multiple `node_modules` folders at different directories, this configuration is more geared towards React Native libraries that have an example folder, and that example folder wants to use code from `../..`

It seems that on Windows this config falls into the "multiple react found" error. Here's another one tested on Mac and Win

**babel.config.js**
```
module.exports = {
  presets: [
    'module:metro-react-native-babel-preset',
    ['@babel/preset-typescript', {allowDeclareFields: true}],
  ],
  plugins: [
    [
      'module-resolver',
      {
        alias: {
          'react': './node_modules/react',
          'react-native': './node_modules/react-native',
        },
      },
    ],
  ],
};
```

**metro.config.js**
```
/**
 * Metro configuration for React Native
 * https://github.com/facebook/react-native
 *
 * @format
 */

const path = require('path');

const moduleRoot = path.resolve(__dirname, '../..');

module.exports = {
  watchFolders: [moduleRoot],
  transformer: {
    getTransformOptions: async () => ({
      transform: {
        experimentalImportSupport: false,
        inlineRequires: true,
      },
    }),
  },
};
```
