### ISSUE TITLE
When is the lifecycle method "componentDidMount" called when my react-native component renders on the app (andorid/ ios). 

### ISSUE THREAD

**Issue by smisra3** [react-native-community/discussions-and-proposals#485]
When is the lifecycle method "componentDidMount" called when my react-native component renders on the app (andorid/ ios). 

As per my understanding the render pipeline has 3 major phases:

1- render
2- commit
3- mount

Now  my query here is :
Where are my component's life-cycle methods called, in render phase or in mount phase?
If they are called in render phase, then how do i determine when my component is has been rendered on the screen via mount phase.

Thanks in advance.

**Comment by liamjones** [comment]
@smisra3 this isn't really the right place to ask this question but this diagram will probably help your understanding: https://projects.wojtekmaj.pl/react-lifecycle-methods-diagram/

**Comment by smisra3** [comment]
Thanks @liamjones. Closing this issue.
