### ISSUE TITLE
Add polyfills for new methods of Promise (ES2020+)

### ISSUE THREAD

**Issue by retyui** [react-native-community/discussions-and-proposals#491]
### Introduction

Add polyfills for:
- `Promise.allSettled`
- `Promise.any`

### Details

Latest Hermes engine already implement `es2020`, `es2021` methods, `react-native-v8` also, `JCS` too:

```tsx
Promise.allSettled() // es2020, TypeError: undefined is not a function
str.matchAll(/regex/g) // es2020
Symbol.matchAll // es2020
String.prototype.replaceAll // es2021
Promise.any() // es2020, TypeError: undefined is not a function
```

but React Native use [`then/promise`](https://github.com/then/promise) module to polyfill `Promise` and new methods of `Promise` not available  

never mind what engine and how fresh is it (`react-native-v8`, `JSC (iOS 15+)`, `hermes-engine`), 
new `Promise` methods will be always `undefined` (RN uses a 2 years old [`then/promise`](https://github.com/then/promise) module) 

See tabel: https://retyui.github.io/react-native-compat-table/

### Discussion points

1. Is it still required at 2022 to use [`then/promise`](https://github.com/then/promise) 
2. How then we can polyfill new methods? (I tried to contribute to that repo https://github.com/then/promise/pull/171 but seems it won't be merged in nearest future)

**Comment by jahglow** [comment]
Thumbs up for it, because I also stumble upon these inconsistencies and they are pain! Serious topic that's been ignored for a year, that's weird!

**Comment by retyui** [comment]
**UPD:** `Promise.allSettled` PR was merged 

- https://github.com/then/promise/pull/171#issuecomment-1232851241
- https://github.com/facebook/react-native/pull/34544
