### ISSUE TITLE
onMouseEnter/onMouseLeave for genereric Views 📱🖱️ 

### ISSUE THREAD

**Issue by runtothedoor** [react-native-community/discussions-and-proposals#492]
### Introduction

You can connect mouse to mobile devices via USB or Bluetooth but while working with generic view, hover events for that are not exposed.

<h5>Example of discord app's usage for hover events:</h5>
<img width="200px" src="https://user-images.githubusercontent.com/28831375/169609266-b0f70094-5209-48a4-a037-7eebdc8a20c5.gif"/>

### Reference
Android OnHoverListener:
https://developer.android.com/reference/android/view/View.OnHoverListener

IOS UIHoverGestureRecognizer:
https://developer.apple.com/documentation/uikit/uihovergesturerecognizer

**Comment by AlanSl** [comment]
+1 and it's not just a mouse this would be useful for; many Android devices have pens with some form of "air hover" feature, e.g. the Samsung Galaxy s-pen is very widely used, and I believe there are others too (e.g. high-end tablets marketed at digital artists?). I believe the Apple Pencil does something similar on iOS?

Many pure-native apps support hover events perfectly for these, but I believe it's impossible in React Native currently. 

It'd be great for `Pressable` to give `hover` state alongside `pressed` state.

**Comment by runtothedoor** [comment]
> +1 and it's not just a mouse this would be useful for:
> 
> * Many Android devices have pens with some form of "air hover" feature, e.g. the Samsung Galaxy s-pen is very widely used, and I believe there are others too (e.g. high-end tablets marketed at digital artists?).
> * I believe the Apple Pencil (and connected mouse) does something similar on iOS?  iOS has [UIHoverGestureRecognizer ](https://developer.apple.com/documentation/uikit/uihovergesturerecognizer) like Android's [View.OnHoverListener](https://developer.android.com/reference/android/view/View.OnHoverListener) you mentioned in the issue.
> 
> I believe these all trigger the same hover events as a connected mouse. Many pure-native apps support hover events perfectly for these.

Excellent point. Thanks for adding to the discussion!

**Comment by runtothedoor** [comment]
Looking at the react-native code I found that this kind of pointer event seems to be under development and we will get there soon.

https://github.com/facebook/react-native/commit/8be49e87460aa131e8f344a7e15f77efca754b83

**Comment by runtothedoor** [comment]
Btw, seems @lunaleaps is actively working on it...

![image](https://user-images.githubusercontent.com/28831375/184944033-6d232212-6013-4ee8-b0a0-0b709980ae31.png)

https://github.com/facebook/react-native/commits?author=lunaleaps

**Comment by lunaleaps** [comment]
@vincentriemer and I are working on implementing the PointerEvent spec and have some coarse implementation of it. You can opt into it using [ReactFeatureFlag `dispatchPointerEvents`](https://github.com/facebook/react-native/blob/23429330a64ef9c05f67f12231039351a72f43ea/ReactAndroid/src/main/java/com/facebook/react/config/ReactFeatureFlags.java) on Android, there's an equivalent flag in iOS.

**Comment by runtothedoor** [comment]
https://reactnative.dev/blog/2022/12/13/pointer-events-in-react-native

**Comment by lunaleaps** [comment]
@runtothedoor Let us know if you end up trying it and have any thoughts: https://github.com/react-native-community/discussions-and-proposals/discussions/557
