### ISSUE TITLE
DrawerLayoutAndroid for IOS

### ISSUE THREAD

**Issue by Quintis1212** [react-native-community/discussions-and-proposals#504]
Hello every one ) Does somebody want to implement DrawerLayoutAndroid for ios ? I dont know IOS native development but I can help what I can )

**Comment by radko93** [comment]
There's no native drawer component on iOS that's why React Native does not have a component like this. Your best luck is to use https://docs.swmansion.com/react-native-gesture-handler/docs/api/components/drawer-layout
