### ISSUE TITLE
How to change native context menu of TextInput?

### ISSUE THREAD

**Issue by arasrezaei** [react-native-community/discussions-and-proposals#506]
As title says,
currently, there is no way to change context menu items.
when you select a word in TextInput, there are only default options (cut, copy, paste ...).
it will be really great if we can change context menu items (remove, add, icon set for item, ...)
its a really use full feature.

I saw this package did a great job.
https://github.com/AlenToma/react-native-selectable-text
but is incomplete.
I think this should not be a package and should be implemented in core.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
