### ISSUE TITLE
Provide an options to build project with Swift or Objective c

### ISSUE THREAD

**Issue by elmcapp** [react-native-community/discussions-and-proposals#511]
Currently when we run ```npx react-native init MyApp``` We get a react native project that is build with objective c. It would be nice if we had an option to select if we want to build the project with objective-c or swift. 

This can be useful for us that do not write objective-c but a great option for us that know swift

**Comment by kelset** [comment]
please refer to https://github.com/react-native-community/discussions-and-proposals/issues/253
