### ISSUE TITLE
$500 Bounty - Official SwipeRefreshLayout for Android (PTR for iOS already solved)

### ISSUE THREAD

**Issue by dave-d-h** [react-native-community/discussions-and-proposals#516]
Hi folks!

I work at a tech company and we'd like to have the below feature in 1265 (already supported for iOS) to also be "officially" supported for Android as well (in react-native-webview)

https://github.com/react-native-webview/react-native-webview/pull/1265 (this is the iOS feature)
https://github.com/react-native-webview/react-native-webview/issues/2468 (this is the issue we want to solve to also support this for Android)

Technically, someone got 2468 "working-ish" - but it's some random forked code, and we'd prefer a version that could be merged back into the main open source project / codebase 👍

$500 in it for the person who can solve and merge into main project!

**Comment by cortinico** [comment]
> (in react-native-webview)

Please open your proposal inside React Native WebView and not here. This is the repo for discussions around the React Native core.
