### ISSUE TITLE
Support for `inset` shorthand for `top/bottom/left/right` when absolute positioning

### ISSUE THREAD

**Issue by Slapbox** [react-native-community/discussions-and-proposals#517]
### Introduction

This would go a ways towards reducing style clutter

### Discussion points

Why doesn't React Native already support the `inset` style property?

**Comment by thymikee** [comment]
Inset has already been requested as a part of https://github.com/react-native-community/discussions-and-proposals/pull/496#issuecomment-1234083585. Please voice your concerns there :)
