### ISSUE TITLE
300 length array data process every second

### ISSUE THREAD

**Issue by aqdas-ilyas** [react-native-community/discussions-and-proposals#520]
I received data from MQTT server. almost 250 row in each second now i have to check each of the row and store that in redux. now the problem is that the app is getting slow when i process the data and store in redux. I already applied multiple process but nothing help

`var timestamp = []
var result = true

const onMessageArrived = async (theMessage, dispatch) => {
    const split = theMessage.payloadString.split(';')

    if (timestamp.length > 0) {
        result = JSON.stringify(split) != JSON.stringify(timestamp)
    }

    if (result) {
        if (split[0] == 'bms100') {
            'worklet';
            BMS100(split, dispatch)
            dispatch({
                type: CHANGE_BMS100, payload: true
            })
        }
        else if (split[0] == 'bms24') {
            'worklet';
            BMS24(split, dispatch)
            dispatch({
                type: CHANGE_BMS24, payload: true
            })
        }
        else if (split[0] == 'n2k') {
            'worklet';
            N2K(split, dispatch)
            dispatch({
                type: CHANGE_N2K, payload: true
            })
        }
        else if (split[0] == 'motor') {
            'worklet';
            Motor(split, dispatch)
            dispatch({
                type: CHANGE_MOTOR, payload: true
            })
        }
        else if (split[0] == 'modbus') {
            'worklet';
            Modus(split, dispatch)
            dispatch({
                type: CHANGE_MODBUS, payload: true
            })
        } else {
            dispatch({
                type: FALSE_HEART_BEAT, payload: true
            })
        }
    }
    timestamp = split
}`

The above is my main function when every the for example i received "modus" from MQTT if called Modus() function and pass the data and there is 2 to 3 condition and store in REDUX 

i hope you will help me. i appreciate your help
Thank you

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
