### ISSUE TITLE
React Native version

### ISSUE THREAD

**Issue by samarthjain10** [react-native-community/discussions-and-proposals#531]
### Introduction

I need to get the current react-native version from my package.json 

### Details

I need to get the current react-native version from my package.json for which i have to require package.json file and give the path inside it which is not always the same. 

### Discussion points

I need something similar to React where I can access the version just by adding React.version
It should give the the react-native version present in my package.json

**Comment by radko93** [comment]
You can simply import your `package.json` and then read it's contents.
`const version = require('./package.json')`

**Comment by cortinico** [comment]
`Libraries/Core/ReactNativeVersion.js` does exactly that 👍

**Comment by samarthjain10** [comment]
> `Libraries/Core/ReactNativeVersion.js` does exactly that 👍

how do i use it in my tsx file?

**Comment by cortinico** [comment]
Something like this:

```tsx
const ReactNativeVersion = require('react-native/Libraries/Core/ReactNativeVersion');

console.info(ReactNativeVersion.version.major)
```

**Comment by samarthjain10** [comment]
> Something like this:
> 
> ```tsx
> const ReactNativeVersion = require('react-native/Libraries/Core/ReactNativeVersion');
> 
> console.info(ReactNativeVersion.version.major)
> ```

const ReactNativeVersion = require('react-native/Libraries/Core/ReactNativeVersion');
    console.info(
      ReactNativeVersion.version.major +
        '.' +
        ReactNativeVersion.version.minor +
        '.' +
        ReactNativeVersion.version.patch
    );
    this worked thanks
    but still it would be great if it ReactNative.version could directly provide this similar to React.version
    and if this is documented somewhere in ReactNative docs

**Comment by cortinico** [comment]
It's documented here: https://reactnative.dev/docs/next/platform#constants
You could use also `Platform.constants` to access the same `reactNativeVersion` object.
