### ISSUE TITLE
Getting an installDebug error on  running 'npx react-native run-android' comand

### ISSUE THREAD

**Issue by siddiquesheikh30** [react-native-community/discussions-and-proposals#553]
I have been working on this project for two months and everything was working perfectly fine but for the last 2 to 3 days when I try to run the app with command 'npx react-native run-android' initially it started giving me an error after executing 75% like this:
`* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'lib/arm64-v8a/libfbjni.so'. If you are using jniLibs and CMake IMPORTED targets, see https://developer.android.com/studio/preview/features#automatic_packaging_of_prebuilt_dependencies_used_by_cmake`

so I solved this problem by the solution of `https://github.com/facebook/react-native/issues/35210` But now I am getting an error on executing the app till 99%  as:

`* What went wrong:
Execution failed for task ':app:installDebug'.
> java.util.concurrent.ExecutionException: com.android.builder.testing.api.DeviceException: com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl789453764.tmp/base.apk (at Binary XML file line #158): androidx.media.session.MediaButtonReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present`

so I dont know how to solve this issue? please help.

**Comment by cortinico** [comment]
This is not the repo to report build failures for react-native. You should report them on:
http://github.com/facebook/react-native
