### ISSUE TITLE
Testing the Security Provider (MSTG-NETWORK-6)

### ISSUE THREAD

**Issue by Kaushals1** [react-native-community/discussions-and-proposals#554]
Current react version - "18.1.0"
Current react-native version - "0.70.2"
Node version - "18.12.1"

CLARIFICATION : 
Do we need to explicitly handle updating the security provider for android as mentioned in the below given link.
[](https://github.com/OWASP/owasp-mastg/blob/master/Document/0x05g-Testing-Network-Communication.md#testing-the-security-provider-mstg-network-6)

We tried adding the dependency is app/build.gradle file as shown in the image
![image](https://user-images.githubusercontent.com/47268004/205255827-60fd7477-2d2b-467e-aeda-dbd784e6a614.png)

We are facing the following error:
![image](https://user-images.githubusercontent.com/47268004/205256330-9b1c5a0c-fc46-439a-9151-0a0d1c660cad.png)

Could you please guide us exactly how to achieve this if not handled already?
We need to address this immediately as we're behind our schedule to upload our application on the play store.

**Comment by cortinico** [comment]
This is not the correct repo to post those kind of issues. This repo is only for discussions and proposals related to react-native
