### ISSUE TITLE
Let React Native  support  new  OS architeture OpenHarmony

### ISSUE THREAD

**Issue by luorixiangyang** [react-native-community/discussions-and-proposals#564]
### Introduction

Let React Native  support  new  OS architeture -- openharmony

### Details
openharmony as a new architeture os, we found the power abilities  to be stronger than before on [gitee](https://gitee.com/openharmony) ;  Let React Native support openharmony make double wins , i have a group want to start adaption of openharmony in  react native community. But I am concerned if this idea is also in the interest of React Native community. If true，we can start detail discussion soon.

### Discussion points
1.Support native implementation of openharmony like android.
2. We can connect ArkEngine like hermes; 
3. We can make communication adaptions from JSI and openHarmony native;
4. commit some attachment of openharmony special tools .
5. ......

**Comment by luorixiangyang** [comment]
no  guys interesting in this topic？

**Comment by TheSavior** [comment]
People are welcome to build a platform implementation of React Native for OpenHarmony as React Native is open source.

**Comment by luori-mvp77** [comment]
> People are welcome to build a platform implementation of React Native for OpenHarmony as React Native is open source.
Thanks for you reply，i got it. I will start work for this job and submit the first basic implentmention of React Native for OpenHarmony soon.

**Comment by luori-mvp77** [comment]
> People are welcome to build a platform implementation of React Native for OpenHarmony as React Native is open source.

Thanks for you reply，i got it. I will start work for this job and submit the first basic implentmention of React Native for OpenHarmony soon.
