### ISSUE TITLE
allow multiple destructiveButtonIndex of ActionSheetIOS

### ISSUE THREAD

**Issue by vreality64** [react-native-community/discussions-and-proposals#57]
### Introduction

I have some **needs for multiples red buttons in ActionSheet**. for example, "report", "delete", "withdrawal", etc. everything could be destructive (or dangerous) by needs.

### The Core of It

[Apple Developer's Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/) says like below. You can see word "buttons", "actions". This means it could be multiple item, right?
> **Make destructive choices prominent**. Use red for buttons that perform destructive or dangerous actions, and display these buttons at the top of an action sheet.

However, React Native's ActionSheetIOS only [allow one item](http://facebook.github.io/react-native/docs/actionsheetios.html#showactionsheetwithoptions) with `destructiveButtonIndex` option. It was implemented like [this](https://github.com/facebook/react-native/blob/master/Libraries/ActionSheetIOS/RCTActionSheetManager.m#L93).

### Discussion points

How about you change the option so that it receives multiple indexes?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

**Comment by vreality64** [comment]
Oh. Thank you for letting me know 😃
