### ISSUE TITLE
React Native - the nature of the 'Core team'

### ISSUE THREAD

**Issue by kelset** [react-native-community/discussions-and-proposals#59]
### Introduction

This discussion is related to the main "sustainability and community involvement" conversation going on in #58.

This issue wants to focus on the 'Core team' aspect, since there are opinions on its importance & role & nature; how to make it more inclusive and diverse is the core question.

### The Core of It

My understanding is that, in the early days of React Native, a Slack group was created to help the FB team and the most active non-FB maintainers communicate. Over time, more people were invited to said Slack, which ended up acting as the hub to coordinate the tasks and efforts of the more involved members of the community.

Recently, since the community at large as become more 'central' to the Open Source side of React Native, this and the releases repos were created to create a more neutral and transparent place for these communication to happen.

But a portion of the conversations still happen over in the real-time world of Slack, and this may generate the perception that the Core is an exclusive club without clear rules or boundaries over what gets decided, or who can be included in it.

### Discussion points

1. How can we make more members of the community more involved, hence part of the core?
1. Is there a natural limit of people after which said group would be too big to manage/coordinate?
1. Should we have a sign-up form of some sort? Should we keep inviting people directly?
1. What's a good rule of thumb about what makes a core contributor?\*
1. Given that the community at large is scattered across [many different platforms](https://facebook.github.io/react-native/help), how can we better communicate with all of them?

---

\* *I find [this video](https://www.youtube.com/watch?v=376dz1oIr3g) from Gatbsy a good source of inspiration for it*

**Comment by cpojer** [comment]
Closing as there hasn't been any activity here. We recently published a document outlining the ecosystem, including a brief description of responsibilities of core contributors, see https://github.com/facebook/react-native/blob/master/ECOSYSTEM.md. We are currently iterating on a document to further flesh out the definition and "lifecycle" of core contributors.
