### ISSUE TITLE
How to fix ios app crash reports in react native?

### ISSUE THREAD

**Issue by stack-guru** [react-native-community/discussions-and-proposals#598]
Hello everyone

I've made ios app with react native and uploaded app in test flight.
There are many crash reports in test flight.
It is very hard to catch crash case and I am not sure how to fix them with react native.
Please Help me.
Thanks.

![image](https://user-images.githubusercontent.com/51454234/217705689-058f36f1-dff5-4879-9f2c-ac654a04df4e.png)

**Comment by cortinico** [comment]
> It is very hard to catch crash case and I am not sure how to fix them with react native.

In general, you should look at each crash and stacktrace to see if you find the culprit of the crash. 

I would suggest to check in our issue tracker https://github.com/facebook/react-native/issues
if you find anything similar which might help you debug

**Comment by stack-guru** [comment]
Do I need to analyze each crash files?
It is very hard to understand.
![image](https://user-images.githubusercontent.com/51454234/217886209-b3241897-ea71-4e65-aad9-79cb9574b283.png)

**Comment by stack-guru** [comment]
@cortinico Please help me
