### ISSUE TITLE
Button Fit to text layout

### ISSUE THREAD

**Issue by Mojo90** [react-native-community/discussions-and-proposals#61]
### Introduction & The Core of It

In the Button docs [here](https://facebook.github.io/react-native/docs/button) it shows an image which says: `Fit to text layout`. That is what I am searching for because my button always has full width. But neither in the docs nor in the button code [here](https://github.com/facebook/react-native/blob/master/Libraries/Components/Button.js) I can find something related to that. Can you please support? I have found nothing also here in the issues.

### Discussion points

Is it easily possible to fit the width of the button with the title text as stated in the docs or not?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

**Comment by jamonholmgren** [comment]
Perhaps we should add something to the react-bot to say "If you need help resolving an issue, try <link>".
