### ISSUE TITLE
PermissionsAndroid.check() should return a PermissionsAndroid.RESULTS value instead of a boolean

### ISSUE THREAD

**Issue by KarandikarMihir** [react-native-community/discussions-and-proposals#62]
### Introduction
Android has 3 types of actions that user can choose to perform while granting the permission - Grant, Deny, Never show again. Developers would want to know exactly which action user has performed. The prompt for permission keeps showing up unless and until the user chooses "Never ask again". 

Currently, `PermissionsAndroid.check()` returns a boolean and it's not clear whether the user has denied access just once or permanently disabled the prompt.

### The Core of It
The intro says it all. 

### Discussion points
- Should `PermissionsAndroid.check()` return a `PermissionsAndroid.RESULTS` value?
- Is it even possible to do this?

[See docs](https://facebook.github.io/react-native/docs/permissionsandroid)

**Comment by satya164** [comment]
Android doesn't give this information, so it's not possible o implement it.

https://developer.android.com/reference/android/support/v4/content/ContextCompat#checkSelfPermission(android.content.Context,%20java.lang.String)
