### ISSUE TITLE
react-native-webview not open external browser in iOS

### ISSUE THREAD

**Issue by oniangel12933** [react-native-community/discussions-and-proposals#626]
I used react-native-webview(version 11.23.0) for Plaid OAuth.
The webview page show Plaid OAuth page. When I tap a bank from the list, it will redirect to sign in page of the bank.
On Android, it opens external browser, but iOS doesn't open an external browser.
How can I fix this issue on iOS?
Please help me.
My email is oniangel129@gmail.com.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
