### ISSUE TITLE
Pickup apps network activity in chrome dev tools when using Hermes

### ISSUE THREAD

**Issue by matthewmturner** [react-native-community/discussions-and-proposals#630]
### Introduction

I recently upgraded our RN version (to .71) and added Hermes support.  Previously, I used React Native Debugger when debugging as it aggregated logs / network activity / react dev tools.  Now on hermes I use a mix of tools (Chrome dev tools and reactotron or a proxy for monitoring network activity).  It would be really nice if when using hermes network activity could be picked up directly in chrome dev tools. I think this would allow me to do a large amount of the debugging I do just in chrome dev tools.

Originally raised [here](https://github.com/facebook/hermes/issues/959)

### Details

I would like to see my apps network activity in the network tab of chrome dev tools.

### Discussion points

Is this in the scope of React Native core? If so, is there interest in adding this functionality?  If not, what would be the appropriate place to raise this request?

**Comment by danbim** [comment]
Hi @matthewmturner! Why did you close the issue? I'd love to have this being supported :)

**Comment by matthewmturner** [comment]
@danbim expo is adding this! https://twitter.com/cedric_dev/status/1657069589178482711?s=20

**Comment by danbim** [comment]
@matthewmturner Whoohoo! :)

**Comment by byCedric** [comment]
Oh man, I got so excited when we worked on this! Glad to see others getting excited too ❤️

**Comment by arnab-xd** [comment]
> Oh man, I got so excited when we worked on this! Glad to see others getting excited too ❤️
is this available for expo users only or it can be used for cli apps as well ?

**Comment by daniel-anh-nguyen-hipages** [comment]
@matthewmturner Interested in re-opening this for CLI apps?
