### ISSUE TITLE
App getting crashed when installed in any device but working fine in debug mode

### ISSUE THREAD

**Issue by vaibhav71** [react-native-community/discussions-and-proposals#649]
I am having one app which I am able to run perfectly in the debug mode, but as soon as I am creating apk and trying to install the apk, app is directly getting crash and I am getting error in the android studio.

 Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x4 in tid 17862 (.expeditesocial), pid 17862 (.expeditesocial)
 => This is the error which I am getting in android studio when I am opening the app which I installed after creating apk.
 
 Here is the package.json file
 **"dependencies": {
    "@react-native-async-storage/async-storage": "^1.17.12",
    "@react-native-community/netinfo": "^9.3.7",
    "@react-native-google-signin/google-signin": "^9.0.2",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.3.2",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.71.4",
    "react-native-actions-sheet": "^0.8.29",
    "react-native-calendars": "^1.1294.0",
    "react-native-date-picker": "^4.2.11",
    "react-native-eject": "^0.2.0",
    "react-native-element-dropdown": "^2.9.0",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-image-picker": "^5.3.1",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.2.0",
    "react-native-paper": "^5.5.1",
    "react-native-reanimated": "^3.0.2",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-scrollable-tab-view": "^1.0.0",
    "react-native-svg": "^13.8.0",
    "react-native-svg-transformer": "^1.0.0",
    "react-native-switch-toggle": "^2.2.1",
    "react-native-tab-view": "^3.5.1",
    "react-native-toast-message": "^2.1.6",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-webview": "^11.26.1"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.8",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }**
  
  Really need help
  Thanks

**Comment by cortinico** [comment]
Hi @vaibhav71. Sadly, this is not the right repo to report this. Please report it on
github.com/facebook/react-native/issues **and** also provide a reproducer for this cash
