### ISSUE TITLE
Standardise code style within the organisation

### ISSUE THREAD

**Issue by grabbou** [react-native-community/discussions-and-proposals#65]
I am about to set up "Prettier" in my project along "ESLint" to keep it consistent across some open-source work that I do and easier for contributors to work without worrying about internal patterns.

I've noticed that we don't have a general "community" preset. There is "eslint-config-fb" that is used by React Native. Unfortunately, it's a part of a project that [is not meant to be consumed](https://github.com/react-native-community/discussions-and-proposals/issues/65#issuecomment-445209440) by 3rd parties.

We also do have "eslint-config-callstack", which is the one that I was planning to use for the CLI. It has Prettier integrated as a ESLint rule and makes it really easy to fix all the issues within your codebase by just running eslint --fix.

However, I am afraid of several inconsistencies that this may cause across community project. For instance, there are projects that don't use Prettier or ESLint at all. There might be some that use a different preset.

Do we care enough to enforce a "standard" ESLint/Prettier config as a part of RNCommunity to make it consistent to contribute? Say, we have "react-native-community/eslint-config-react-native", which also becomes a "recommended" preset for React Native?

Or we don't care and every project is allowed to go on its own?

PS. If we do care, I am happy to do it. We can fork our "callstack" preset as it's already set up for being consumed from "npm" and just adjust the rules.

**Comment by kelset** [comment]
Uhm can't we use simply enforce the one FB uses for the main repo?

@TheSavior what do you think?

**Comment by grabbou** [comment]
We can use that one too. 

Keep in mind it might be unlikely we can modify it w/o checking with Facebook. I think that having our own would be a bit better as far as decoupling.

**Comment by grabbou** [comment]
Edit: `eslint-config-fb` is part of this repository: https://github.com/facebook/fbjs#readme that clearly states:

> Note: If you are consuming the code here and you are not also a Facebook project, be prepared for a bad time. APIs may appear or disappear and we may not follow semver strictly, though we will do our best to. This library is being published with our use cases in mind and is not necessarily meant to be consumed by the broader public. In order for us to move fast and ship projects like React and Relay, we've made the decision to not support everybody. We probably won't take your feature requests unless they align with our needs. There will be overlap in functionality here and in other open source projects.

Don't want to run into problems if someone internally changes the configuration :)

**Comment by grabbou** [comment]
Right. I got confused because it’s actually a dev dependency!

**Comment by mmazzarolo** [comment]
I would suggest using the default prettier preset + the create-react-app eslint config (using [`eslint-config-react-app`](https://www.npmjs.com/package/eslint-config-react-app) or [`eslint-plugin-react-app`](https://github.com/mmazzarolo/eslint-plugin-react-app)) but I'm not sure if enforcing them (or any other ruleset, like a TSLint config) would be a good approach.

**Comment by cpojer** [comment]
I strongly believe the community org should directly follow the React Native main repo. Having a common set of standards shared with the main repo will make it less confusing for everyone and easier to collaborate, as well as move code from one repository to others. The react-native-cli repo for example uses bracket spacing and doesn't use trailing commas. I think it would be best to invert those settings and align with RN.

**Comment by cpojer** [comment]
To start, I would recommend unifying the prettier config, and worrying about the eslint stuff later.

**Comment by grabbou** [comment]
Do you want me to create a new repository then?

**Comment by cpojer** [comment]
Yeah, go for it. I guess if you can publish a react-native-community eslint + prettier config based on RN that all downstream projects use, that would be ideal. Even better if we could adopt that in RN too.

**Comment by michalchudziak** [comment]
I can migrate [eslint-config-fbjs](https://github.com/facebook/fbjs/tree/master/packages/eslint-config-fbjs) to `react-native-community/eslint-config-react-native-community` if you still need an additional pair of hands to help.

**Comment by grabbou** [comment]
Please do it Mike! Thank you!

**Comment by TheSavior** [comment]
I don't think we want eslint-config-fbjs. I think we want this file from the react-native repo: https://github.com/facebook/react-native/blob/master/.eslintrc

**Comment by cpojer** [comment]
I’m planning to look at this soon. I’d like this config to stay in the RN repo and be shared on npm separately.


________________________________

**Comment by grabbou** [comment]
Makes sense to use that file. @cpojer, anything in particular against React
Native Community as a location? It makes sense to me to have it here as a
community preset that is recommended to be adopted.

**Comment by cpojer** [comment]
Ideally we’ll keep it in the RN repo and reuse it in the community repos. I need to move some things around to make that happen.


________________________________

**Comment by kelset** [comment]
> Ideally we’ll keep it in the RN repo and reuse it in the community repos.

single source of truth FTW 👍

**Comment by cpojer** [comment]
@michalchudziak React Native will use the same settings and it's the source of truth. We use those internally at FB as well. Basically I want to extract what we use in RN into a separate package that is then used within RN and in the community packages.

**Comment by SimenB** [comment]
Sorta, kinda, in a weird way, related: could that hypothetical package take over for `eslint-config-fb-strict` which lives in the Jest monorepo? https://github.com/facebook/jest/tree/master/packages/eslint-config-fb-strict

**Comment by cpojer** [comment]
I think that package is stricter than what React Native uses, no?

**Comment by SimenB** [comment]
IDK, I haven't looked at the rules. But makes sense to me to converge on some strict config and not have yet another version? Maybe not

**Comment by cpojer** [comment]
We now have an eslint plugin that is shared across some projects. Let's make sure all projects adopt it.

**Comment by kelset** [comment]
Closing this in favour of the issue section of https://github.com/react-native-community/.github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc where we are tackling this in more details
