### ISSUE TITLE
Android API level requirement upgrade

### ISSUE THREAD

**Issue by mljlynch** [react-native-community/discussions-and-proposals#650]
### Introduction

After August 2023, Android will require API Level 33 or higher, which means that RN 0.71+ will be the only supported versions. Are their plans to deprecate the older in support versions or back port the target upgrades

### Details

https://developer.android.com/google/play/requirements/target-sdk#:~:text=Starting%20in%20August%202023%3A,which%20must%20target%20Android%2011

> Starting in August 2023:
> 
> New apps must target Android 13 (API level 33) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target Android 11 (API level 30).
> 
> App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; except for Wear OS apps, which must target Android 11.

### Discussion points

* Which versions will continue to be suppported past August?

**Comment by kelset** [comment]
given the [release support window](https://github.com/reactwg/react-native-releases#which-versions-are-currently-supported) and the current pace of 1 release each quarter, in August the current/latest should be 0.73, which means 73-72-71 will be supported, so "within the requirements" of Android's policy.

**Comment by mljlynch** [comment]
That makes sense - where is the best place to stay up to date with these version upgrades? It's not immediately obvious to me that an Android API version change will cause backwards compatibility issues with React-Native.

**Comment by cortinico** [comment]
> where is the best place to stay up to date with these version upgrades?

The best practice is to update to the latest React Native version whenever possible. We're working on making updates as streamlined as possible, but it's crucial that you keep up to date.

Android API changes can introduce breaking changes, if so we'll communicate this accordingly in the release notes.
