### ISSUE TITLE
[react-native init] Add a flag to exclude Flipper installation

### ISSUE THREAD

**Issue by o-alexandrov** [react-native-community/discussions-and-proposals#655]
## Related issues

- [Question: How do i remove Flipper from React Native?](https://github.com/facebook/flipper/issues/1326)
- [Provide an easy way to install CocoaPods excluding Flipper (for release/CI)](https://github.com/react-native-community/discussions-and-proposals/issues/312)

## Current problem

On iOS, there's a way to not install Flipper conditionally with `NO_FLIPPER` env variable, whereas on Android it's always installed as part of the `debug` release.
On Android, the only way to completely get rid of Flipper is to manually remove it from code.

## Proposal

Projects that do not need Flipper would be cleaner (thus, simpler to understand/maintain), if users would have an option `--no-flipper` (to not have Flipper in their codebase).

`$ npx react-native init APP_NAME --no-flipper`

**Comment by thymikee** [comment]
@o-alexandrov please see this RFC: https://github.com/react-native-community/discussions-and-proposals/pull/641 and comment there if you see anything missing. Thanks!
