### ISSUE TITLE
How to run a function after scrollTo animation has finished in React Native?

### ISSUE THREAD

**Issue by bloggerklik** [react-native-community/discussions-and-proposals#667]
I am using scrollTo along with animation. I want run a function after the animation is finished. How can I do that?

`ref.current.scrollToOffset({ animated: true, offset: 0 })`

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
