### ISSUE TITLE
The full dependency tree for React Native is very large

### ISSUE THREAD

**Issue by jmrossy** [react-native-community/discussions-and-proposals#67]
### Introduction

React Native currently has 52 direct package dependencies which when traversed recursively include 589 packages! This nice little graphing tool show's the extent of the graph: http://npm.anvaka.com/#/view/2d/react-native

### The Core of It

The [recent compromise of the popular event-stream library](https://github.com/dominictarr/event-stream/issues/116) brings to light the need for better auditing of the packages we developers rely on. 
Given the popularity of React Native and the trust developers place in it, the dependency graph needs to be audited and significantly reduced.

### Discussion points

1. Are there already efforts underway to improve this?
2. Is the community open to pulling more code into the library in order to kill dependencies?
3. Have dependencies been audited in the past?

**Comment by kelset** [comment]
Hey there - while I agree with the general sentiment, would you mind editing it and toning it down a bit? It's neither terrifying nor shocking, heck we are not talking about 🧟‍♂️ nor 🧛‍♂️ nor 👻 no? ;)

That said, even if those numbers are not as big when compared to other projects:

> Are there already efforts underway to improve this?

Yes, have you checked out the [Lean Core issue](https://github.com/react-native-community/discussions-and-proposals/issues/6)?

> Is the community open to pulling more code into the library in order to kill dependencies?

I think it's a case-by-case scenario: for the main `react-native` repo there is the side constraint of the changes involving the deps needing auditing from FB internal system.

> Have dependencies been audited in the past?

As hinted in the previous point, the main repo is fully audited by FB - which is a strong safety net. Aside from that, given that some other big players also rely on React Native (ex. Microsoft), there are other audit in place.

All of this is topped by the CI, that has an auditing step IIRC.

**Comment by yungsters** [comment]
I expect the [Lean Core](https://github.com/react-native-community/discussions-and-proposals/issues/6) effort to enable us to reduce some of the dependencies.

While the current set of dependencies were audited, I am also all for eliminating extraneous dependencies. One thing that I am not sure anyone has done so far is audit the set of dependencies for which ones we might be able to avoid (or which ones can leverage maybe smaller or more reliable packages, or modern language features).

The extent to which the Core team has done this is attempting to remove `fbjs` as a dependency. But this is less related to security and more to do with management of dependencies (and just general code hygiene).

**Comment by cpojer** [comment]
This is part of the Lean Core effort. Please send us Pull Requests to remove dependencies, both runtime and dev time if you'd like to help :)
