### ISSUE TITLE
Responsive in React Native

### ISSUE THREAD

**Issue by PurpleMonkey729** [react-native-community/discussions-and-proposals#679]
Hi, devs!
Now I am developing a react native app.
It should be satisfied of responsive in iPhone and iPad.
So I used the code like following:

```
import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const guidelineBaseWidth = 320;
const guidelineBaseHeight = 568;

export const resw = (size) => (width / guidelineBaseWidth) * size; // Responsive Width Function
export const resh = (size) => (height / guidelineBaseHeight) * size; // Responsive Height Function
export const resm = (size, factor = 0.5) => size + (resw(size) - size) * factor; // Repsonsive Font Size Function
```
This code was written by Mr Kavin Mehta.
https://medium.com/simform-engineering/create-responsive-design-in-react-native-f84522a44365

I am thinking to use these functions.
I can't define certainly that each function uses in which cases.
So I need the help of the excellent devs in GitHub.
Please help me.
Thanks.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
