### ISSUE TITLE
Transparent sectionListHeader is overlaped by renderItem

### ISSUE THREAD

**Issue by SaldanhaPrtt** [react-native-community/discussions-and-proposals#686]
### Introduction
When creating a SectionList component, if prop stickySectionHeadersEnabled=true, and it has no background, the child renderItem overlaps the header.

### Details
There seems to be no prop or logic that can resolve this problem, all the examples or problems in SoF don't cover this issue fully.
So unfortunately, I must open this issue(or improvement)

## Here is a video displaying the problem
[untitled.webm](https://github.com/react-native-community/discussions-and-proposals/assets/51801745/531d1e48-fed2-40ad-8c2b-bbd8e1531abb)

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).
