### ISSUE TITLE
Rendered fewer hooks than expected

### ISSUE THREAD

**Issue by dawooduser** [react-native-community/discussions-and-proposals#693]
Hello community,

need to discussion on Redux => dispatch method when every time i called the dispatch({type: abc}) the react native app crashed and says "Rendered fewer hooks than expected This may be caused by an accidental early return statement"

dispatch equal from useDispatch with import from react-redux

Thank you

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
