### ISSUE TITLE
ENOENT : no such file or directory uv_cwd(null) 

### ISSUE THREAD

**Issue by onusvishal** [react-native-community/discussions-and-proposals#70]
RN: 56.0.0
Xcode 10

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/45001798/49798923-89cb5e00-fd69-11e8-9442-d226f508915c.gif)

**Comment by kelset** [comment]
This repo is not for issues. Please open one following the template in the main repo

**Comment by onusvishal** [comment]
@kelset which template ?

**Comment by alexdor** [comment]
@onusvishal I think he means this one https://github.com/facebook/react-native/issues/new/choose
