### ISSUE TITLE
 Using gif as splash screen

### ISSUE THREAD

**Issue by hu-hassan** [react-native-community/discussions-and-proposals#703]
### Introduction
I am not able to use a gif as my splash screen using expo splashscreen
Hi, I want to use a gif as my splash screen but I am not able to use it I tried using expo splash screen but IDK what should I do to edit in order to replace my current splash screen with gif

**Comment by cortinico** [comment]
Hi,
Please open this issue against: 
https://github.com/expo/expo/issues

As this is not the right repo for it.
