### ISSUE TITLE
Iframe isn't loading when source is html - iOS only

### ISSUE THREAD

**Issue by SergiOnGit** [react-native-community/discussions-and-proposals#715]
This is my code, what can I do to make it work? As I noticed this happens after I upgraded to RN 0.72 but I'm not sure if RN version is the problem.

"react-native": "0.72.5",
"react-native-webview": "^13.6.0"

<WebView
                    ref={webViewRef}
                    source={{
                        html: `
                            <!DOCTYPE html>
                            <html>
                                <body>
                                  // Youtube or other iframe which isn't loading and show blank space
                                </body>
                           </html>
                        `,
                        baseUrl: Platform.OS == 'ios' ? null : '',
                        automaticallyAdjustContentInsets={true}
                        allowsInlineMediaPlayback={true}
                        mediaPlaybackRequiresUserAction={false}
                        useWebKit={true}
                        allowsFullscreenVideo={true}
                        scalesPageToFit={true}
                        scrollEnabled={false}
                        javaScriptEnabled={true}
                        domStorageEnabled={true}
                        startInLoadingState={true}
                        mixedContentMode='always'
                        originWhitelist={["*"]}
                        showsVerticalScrollIndicator={false}
                    }}
/>

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
