### ISSUE TITLE
React Native Not Showing Last Record Entered

### ISSUE THREAD

**Issue by Wkalo** [react-native-community/discussions-and-proposals#723]
I am Building a Sales App Where an Item Is Chosen And Recorded To Database to show it in Cart,  I Call A Function To Retrieve Records of A Specific invoice SOMETIMES It Does Not Show The Last Record entered the Following Is My Code import React, { useState, useEffect } from "react";
const getCartDetails = () => {
  const [data, setData] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);
  const {cartdetails } = useSelector(state=>state.totalReducer);
  const dispatch = useDispatch()
  
  const fetchData = async () => {
    try {
      setIsLoading(true);
      const user = await AsyncStorage.getItem("curCust");
      const parsed = JSON.parse(user);
      const MyNumber = parsed.cartID;
      
      //console.log("My Number", MyNumber);

      const endpoint = `myPhpUrl/cartOrderList.php`;
      const data = { cartID: MyNumber };
      const response = await axios.post(endpoint, data);

      if (response.status === 200) {
       
        if (response.data.result === "ok") {
          const cartData = await response.data.myresult;
         
          dispatch(setCartDetails(cartData));
          setData(cartData);
          setIsLoading(false);
        } else {
          
          console.log("Error Retrieving Data For " + MyNumber);
        }
      }
    } catch (error) {
      setError(error);
      console.log("failed to get cart Order List: " + error.message);
    } finally {
      setIsLoading(false);
    }
  };

 const refreshData = () => {
    // Call fetchData to refresh the data
    fetchData();
  };
  useEffect(() => {
    fetchData();
  }, []);
  return { data, isLoading, error, refreshData };
};

export default getCartDetails;
When I Notice That A Record Is Missing I Use The Refresh Option and Then All records Are Displayed If I Call The Same PHP File By Postman all record are retrieved , If Any Can Suggest an Idea Or If Anyone Faced The Same Problem Pls Advice , Thx In Advance

**Comment by cortinico** [comment]
Closing as this repo is not for Issue Reports but only for long standing discussions
