### ISSUE TITLE
React Native Health Check CLI

### ISSUE THREAD

**Issue by deadcoder0904** [react-native-community/discussions-and-proposals#73]
### Introduction

A way to verify react-native installation is complete and working?

### The Core of It

I was just checking out Flutter & I see there is a thing there called `flutter doctor` which ensures that installation is complete & working. I think it makes sense for React Native to have something like `react-native doctor` or `react-native health` or something else.

### Discussion points

Might be beneficial for beginners who have a lot of trouble installing Android Studio if they are on anything else than a Mac

PS - I was gonna open this on RN repo but it sent me here so sorry if its not the right place to discuss. Happy to hear your thoughts?

**Comment by kelset** [comment]
There is currently a solution viable using https://github.com/infinitered/solidarity

**Comment by deadcoder0904** [comment]
From what I see -

> Solidarity is an environment checker for project dependencies across multiple machines.

Not sure if it's the same. Flutter doctor also shows Android & iOS installation, etc...

Plus it has some steps to follow rather than just doing `react-native health`. 

Also preferably it can be built-in with `react-native-cli` :)

**Comment by kelset** [comment]
Absolutely, I want to have a `doctor` command in the CLI too.

I was just pointing out what is currently available for a RN dev.

And yeah tbh this is more of a Feature Request for the new [CLI repo](https://github.com/react-native-community/react-native-cli)

**Comment by matt-oakes** [comment]
Solidarity could be a good base for it though. It has rules to check that commands exist (can be used to check Xcode and command line tools are installed) and that environment variables are set (For ANDROID_HOME).

As solidarity is an npm module, the react-native CLI could depend on it and call it using a solidarity settings file that it ships. That way the heavy lifting is done by the solidarity module but users get the convenience of not needing to set it up.

**Comment by deadcoder0904** [comment]
@kelset Cool, should I open it there instead?

@matt-oakes good idea :)

**Comment by kelset** [comment]
yeah probably it would be better.
Maybe open it, then close this with a comment linking to it :)


Btw if you want other examples of CLIs with sanity checks, `brew` has one (along with some other cool cleanup commands).

**Comment by deadcoder0904** [comment]
Moved to https://github.com/react-native-community/react-native-cli/issues/51
