### ISSUE TITLE
Draggable grid like WhatsApp DP cropper

### ISSUE THREAD

**Issue by ThabrezAhmed** [react-native-community/discussions-and-proposals#74]
I need a react native component which allows to crop the image with grid layout like whatapp DP crop.

###Note: We don't need to crop the image. That grid will be overlayed on a view not image and it will output the coordinates of the grid.

Functionality:
1. The user should be able to drag the grid on the View(not on image).
2. The lines inside should be customizable ( the number of lines and position of the line should be input for the component.
3. At the end we should be able to get the coordinate values of the grid.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).
