### ISSUE TITLE
WeakRef support

### ISSUE THREAD

**Issue by phryneas** [react-native-community/discussions-and-proposals#741]
### Introduction

Hermes has support for `WeakRefs`, but it seems it's not enabled for React Native. 

### Details

From https://github.com/facebook/hermes/issues/658 and https://github.com/facebook/hermes/issues/1195, it seems that this requires action on the React Native side (enabling the `microtask-queue` flag for Hermes and then routinely calling `drainMicrotasks`).

### Discussion points

Is there a reason why `microtask-queue` is not enabled, and could it be enabled?

**Comment by cortinico** [comment]
Thanks for flagging this. Let's keep the conversation on:
- https://github.com/facebook/hermes/issues/1195

The Hermes team is aware of this + we'll have to do some integration work on the React Native side. This is currently under our radar but we don't have an ETA

**Comment by Yonom** [comment]
@cortinico The linked issue has been closed:

> Closing, because there is nothing more to be done about this in Hermes.

I couldn't find any open issues regarding RN support of WeakRefs.
Perhaps it makes sense to reopen this one to track react native support?

**Comment by pilotniq** [comment]
@cortinico Yes, please re-open this issue!

**Comment by CptKicks** [comment]
+1 - Please re-open the issue

**Comment by cortinico** [comment]
I've opened this one to keep the conversation going:
- https://github.com/facebook/react-native/issues/42742
