### ISSUE TITLE
is there a way to specify "Debug server host & port for device" in the command line at startup.

### ISSUE THREAD

**Issue by alainib** [react-native-community/discussions-and-proposals#765]
each time i run my app in local with `runandroid` or `runios`  
i have to shake device or open `Dev menu` and manually set "change Bundle location" for ios / android or metro doesn't connect and i don't have live reload.

my alias in zhrc

`alias runandroid= yarn run android:envdev-debugbuild --active-arch-only`  
`alias runios= yarn run ios:envdev-debugbuild`  

### Discussion points

is there a way to set them on startup ( path param with `localhost:8081/index `) ? 

thanks

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

**Comment by alainib** [comment]
ok thanks
