### ISSUE TITLE
Navigation between native to react-native Android

### ISSUE THREAD

**Issue by RutvinBhanderi** [react-native-community/discussions-and-proposals#772]
### Introduction
Navigate to React native screen from Native Activity

### Details
I have created one activity which in kotlin. i want to navigate to a screen which is in react native and want to pass data.

### Discussion points
Native to React native

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
