### ISSUE TITLE
react-navigation@4 support in react-native@0.73.2

### ISSUE THREAD

**Issue by gkasireddy202** [react-native-community/discussions-and-proposals#781]
### Introduction

react-navigation@4 support in react-native@0.73.2

### Discussion points

Hi,

We have been using react-navigation@4 in my project for the last 5 years.
is this react-navigation@4 support in react-native:0.73.2?
My project has a react-native version:0.68.7.
Please look at the documentation screenshot of react-navigation.

Do you have any suggestions?

<img width="1001" alt="Screenshot 2024-04-19 at 7 06 12 PM" src="https://github.com/react-native-community/discussions-and-proposals/assets/90603484/51c0585a-c2bf-4f92-b514-67933528851c">

**Comment by cortinico** [comment]
Please open this same issue against react-navigation:
https://github.com/react-navigation/react-navigation
