### ISSUE TITLE
EPG(electronic program guide ) in react native tv app

### ISSUE THREAD

**Issue by saadlatif75** [react-native-community/discussions-and-proposals#800]
Has anyone work with Tv app in react native.i need to EPG(electronic program guide )  please suggest me any package or if anyone already done this share source code with me
<img width="368" alt="Screenshot 2024-07-12 183252" src="https://github.com/user-attachments/assets/52721612-b88c-4601-b270-216f61a8824c">

**Comment by cortinico** [comment]
You should ask this question on the tvos repo:
https://github.com/react-native-tvos/react-native-tvos
