### ISSUE TITLE
Hard coding of unknown IP addresses（1.2.3.4 and 18.244.0.188）

### ISSUE THREAD

**Issue by yubin9** [react-native-community/discussions-and-proposals#807]
### Introduction

Hard coding of unknown IP addresses（1.2.3.4 and 18.244.0.188）

### Details

18.244.0.188 - related code, for example
![image](https://github.com/user-attachments/assets/40c6db4f-f7f6-4324-840b-33bb4ffd50ba)

1.2.3.4 - related code, for example
![image](https://github.com/user-attachments/assets/78f22b85-da28-4551-87d0-d3e27f461c86)

### Discussion points

What is the purpose of these two IP addresses? Whether data is uploaded to the preceding servers？

**Comment by cortinico** [comment]
Please ask the issue on the libevent and boost repo instead as the code comes from them:
https://github.com/libevent/libevent/blob/7f23b5b5aa61f5496627c2651fd6d8185f34ffde/evutil.c#L934-L943
