### ISSUE TITLE
Replace `mkdirp` with `fs.mkdirSync(path, { recursive: true })`

### ISSUE THREAD

**Issue by trivikr** [react-native-community/discussions-and-proposals#815]
### Introduction

Replace `mkdirp` with `fs.mkdirSync(path, { recursive: true })`

### Details

The `mkdirp` utility is used at multiple places in react-native https://github.com/search?q=repo%3Afacebook%2Freact-native%20mkdirp&type=code

It can be replaced with Node.js native fs.mkdirSync added `recursive` option in Node.js [v10.12.0](https://github.com/nodejs/node/releases/tag/v10.12.0) published on Oct 10, 2018.

### Discussion points

The `mkdirp` currently uses these native APIs:
* https://github.com/isaacs/node-mkdirp/blob/fdf6005432c2506ce31f8cae237039dda2f8479d/src/opts-arg.ts#L4-L8
* https://github.com/isaacs/node-mkdirp/blob/fdf6005432c2506ce31f8cae237039dda2f8479d/src/mkdirp-native.ts#L13-L19

**Comment by cortinico** [comment]
> It can be replaced with Node.js native fs.mkdirSync added `recursive` option in Node.js [v10.12.0](https://github.com/nodejs/node/releases/tag/v10.12.0) published on Oct 10, 2018.

Feel free to send us a PR for that 👍

**Comment by anirudhdream11** [comment]
I have replaced mkdirp with the native fs.mkdirSync(path, { recursive: true }).
@cortinico Here's the PR for your review: https://github.com/facebook/react-native/pull/46388

Looking forward to your thoughts and let me know if you'd like to make any adjustments.

**Comment by trivikr** [comment]
Fixed in https://github.com/facebook/react-native/pull/46388
