### ISSUE TITLE
expo rn 使用metro.config配置文件就会报错，删除就正常能跑

### ISSUE THREAD

**Issue by QinXianwu** [react-native-community/discussions-and-proposals#818]
Call Stack
  <unknown> (node_modules/@expo/metro-runtime/assets/close.png:0)

Metro error: Unable to resolve module missing-asset-registry-path from E:\development\react\applet\demo-applet\node_modules\@expo\metro-runtime\assets\close.png: missing-asset-registry-path could not be found within the project or in these directories:        
  node_modules
> 1 | �PNG
  2 | 
  3 |
  4 | IHDR��IDATxڝՅ

  1 | �PNG
  2 | 
  3 |

Call Stack

metro.config.js
> const { getDefaultConfig } = require('metro-config');
> 
> module.exports = (async () => {
>   const defaultConfig = await getDefaultConfig(__dirname);
> 
>   return {
>     ...defaultConfig,
>     server: {
>       // 自定义端口
>       port: 8088,
>     },
>   };
> })();
>

**Comment by cortinico** [comment]
Hi,
In this issue tracker we accept only issues that are in English.
I'm closing this for now, please consider translating it to English and reopening it.
Thanks.
