### ISSUE TITLE
Is there any plans to add WebCrypto API to React-Native?

### ISSUE THREAD

**Issue by pedrouid** [react-native-community/discussions-and-proposals#83]
A lot of quick hacks and libraries try to either polyfill or build their own solutions for crypto but browsers already have a good library that is super performant for cryptography.

Is there any plans to add WebCrypto API to the React-Native environment?

**Comment by pedrouid** [comment]
The most used and supported library currently is `react-native-crypto` but it requires `rn-nodeify` which is not an ideal solution and it feels like it should be built-in into react-native.

However if it was I think the API shouldn't use the NodeJS Crypto module API but the WebCrypto API which is supported by all major browsers. In my view, the `react-native` environment should aim to match the `browser` environment as much as possible and I think this would be a great addition

**Comment by kelset** [comment]
Relevant conversation -> 
https://github.com/facebook/react-native/pull/20686

cc @linusU @thesavior

**Comment by LinusU** [comment]
I personally would like having WebCrypto added, even though I can see the benefit of having it in a separate module as well...

Deno is also in the process of adding it, and I really like the idea of many JavaScript runtimes that are compatible with each other.

I started working on [react-native-webcrypto](https://github.com/LinusU/react-native-webcrypto) but it only supports Android currently...

**Comment by cpojer** [comment]
I agree with @TheSavior and @axemclion that our current focus is to reduce the surface area instead of adding to it. @LinusU I would recommend you to build out your third-party dependency as you are doing now. Maybe eventually we could move it to `react-native-community`, and officially recommend it in the documentation for people who would like to use this feature.
