### ISSUE TITLE
[0.76] Does React Native support ARM32? I didn't find it on the official blog.

### ISSUE THREAD

**Issue by sai819** [react-native-community/discussions-and-proposals#840]
### Discussed in https://github.com/react-native-community/discussions-and-proposals/discussions/839

<div type='discussions-op-text'>

<sup>Originally posted by **sai819** December  4, 2024</sup>
I can't find a description in the following documents.
https://reactnative.dev/blog/2024/10/23/release-0.76-new-architecture</div>

**Comment by cortinico** [comment]
Yes React Native supports the 4 default Android ABIs:

https://github.com/facebook/react-native/blob/0217d7e19cf10b6b2261ccd8e78f6bf02a55fed4/gradle.properties#L7-L10
