### ISSUE TITLE
Link React Native and React versions & warn when the link is not adhered to

### ISSUE THREAD

**Issue by nathggns** [react-native-community/discussions-and-proposals#88]
### Introduction

Upgrading React without also upgrading React Native can lead to subtle and hard to notice bugs. It may be worth considering linking React Native to specific React versions and warning if this link isn't adhered to. 

### The Core of It

React Native `v0.55.4` is incompatible with the `16.3.x` branch of React in at least one subtle and hard to notice way, and this burnt me recently when I upgraded React without upgrading React Native.

The issue I noticed is that `Context.Consumer`s placed inside `FlatList`s do not re-render when their `Provider` value changes when the `Provider` is placed outside of the `FlatList`. Myself & a colleague spent two days each tracking down this bug and figuring out it was caused by incompatibilities between React & React Native. 

I believe that there may be an opportunity to prevent subtle bugs like this that become very difficult to track down by linking React Native to specific React versions and warning if this link isn't adhered to. 

The following code should be enough to demonstrate this issue:

```js
import * as React from 'react';
import { Text, View, FlatList } from 'react-native';

const { Provider, Consumer } = React.createContext(0);

class RandomProvider extends React.PureComponent {
  constructor() {
    super();
    this.state = { random: 0 };
  }

  componentDidMount() {
    setInterval(() => this.setState({
      random: Math.floor(Math.random() * 100),
    }), 1000);
  }

  render() {
    return <Provider value={this.state.random}>{this.props.children}</Provider>;
  }
}

function Number({ value }) {
  return (
    <Text style={{ fontSize: 60, fontWeight: 'bold', textAlign: 'center' }}>
      {value}
    </Text>
  );
}

export default function App() {
  return (
    <View>
      <RandomProvider>
        <FlatList
          data={[{}, {}, {}]}
          renderItem={() => <Consumer>{random => <Number value={random} />}</Consumer>}
          style={{ marginVertical: 60 }}
        />
      </RandomProvider>
    </View>
  );
}
```

On compatible versions of React Native and React, you should see three random numbers updating every second. On React Native `v0.55.4` and React `16.6.3`, you will simply see three zeroes. 

It would have saved our team a lot of time if React Native warned us that the version of React Native we were using does not support the version of React we were using. 

### Discussion points

It may well be that I've missed some documentation that already suggests which versions of React & React Native are compatible or not. It also may well be that npm already warns if incompatible versions are used (though I'm not sure if this is the case). But I know that the React team have had great success warning developers when they break best practices, and I think this may be an opportunity for React Native to do the same.

**Comment by matt-oakes** [comment]
When you do an `npm install` or `yarn install` with the incorrect react version, you should get a warning like this in the output:

`warning " > react-native@0.55.4" has incorrect peer dependency "react@16.3.1".`

This is because each React Native version defines an exact React version that it supports as `peerDependency` [here](https://github.com/facebook/react-native/blob/5ebe84c704671f8134e5b2851f40c421dd1b33c8/package.json#L156-L158).

To be fair, this is a pretty small warning and an argument could be made that a yellow box warning (or similar) should be shown in the app. That's much harder to miss and if you really did mean to mismatch the versions (maybe to get hooks support) you could ignore it.

**Comment by nathggns** [comment]
> When you do an npm install or yarn install with the incorrect react version, you should get a warning like this in the output:

I appreciate this point, though I don't think I would be in a unique position working on projects were these kinds of warnings are plentiful and often unresolvable, and do not cause issues. This can make it easy to miss warnings where they are consequential. This isn't React's fault, but it may be worthwhile, knowing that this npm issue may well be missed by many, to warn through the yellow box area.

**Comment by kelset** [comment]
👋

It seems that this is related to upgrading React Native, would you mind converting your original comment into a comment in this issue https://github.com/react-native-community/discussions-and-proposals/issues/68 ?

It's not really a discussion worth having on the side I feel.

**Comment by nathggns** [comment]
This is not connected to upgrading React Native. In fact, it is explicitly not upgrading React Native that was the cause of the issue here. It's more a problem of how React & React Native handle version mismatches between each other.

**Comment by kelset** [comment]
You literally started by talking about upgrading

> Upgrading React without also upgrading React Native can lead to subtle and hard to notice bugs.

I feel that you should still raise it there - it's about the upgrade experience overall. That said, I also have sort of an hard time understanding why you may want to do one without the other since RN versions are usually tightly couple to their React counterparts.

**Comment by nathggns** [comment]
> You literally started by talking about upgrading

The issue was caused by upgrading React, not upgrading React Native. But it's not even about upgrading, it's just about issues caused by version mismatches. 

>  I also have sort of an hard time understanding why you may want to do one without the other since RN versions are usually tightly couple to their React counterparts.

This is entirely the point. If they're tightly coupled (which I didn't know, and nobody on my team knew, and none of us are novices), it's probably worth introducing a warning when that link isn't adhered to. 

As I said before, React has had great success introducing warnings for common mistakes (as have other libraries that came before, Angular comes to mind). It would be great if React Native would do the same. 

I'm not going to raise this issue on a ticket discussing upgrading React Native because it isn't really caused by upgrading React Native, that is just one of the times you might run into this issue. It can occur in plenty of other circumstances, such as the scenario I outlined above, **which has nothing to do with upgrading React Native**. I hope you can appreciate that these are separate issues.
