### ISSUE TITLE
CSS Grid Layout support

### ISSUE THREAD

**Issue by damianobarbati** [react-native-community/discussions-and-proposals#90]
I've been developing web application for years and nothing is more powerful yet simple than CSS Grid Layout to create simple or complex grids, no matter if they are 1 or 2 dimensions: less DOM to manage, strong gutters and gap control without hacks, the powerful minmax function and so on.

I was considering moving to native application but what I see React Native is lacking the most is the Grid Layout system.

**Is there any real plan/interest/intent in porting the CSS Grid Layout system to React native?**

I didn't find much about this feature in React Native but this dead issue nobody ever answered: https://github.com/facebook/react-native/issues/17150

**Comment by ericvicenti** [comment]
A layout feature like this would be implemented in Yoga, which is independent of the Fabric project afaik.

See also: https://github.com/facebook/yoga/issues/47

**Comment by satya164** [comment]
Unfortunately, seems that issue was closed back in 2015. Maybe worth revisiting it now and opening it for discussion?

**Comment by damianobarbati** [comment]
@satya164 definitely I'd say.

**Comment by polarathene** [comment]
I've opened a new issue [in the yoga repo](https://github.com/facebook/yoga/issues/867) for anyone who wants to follow. Hopefully an active dev for `yoga` will chime in there :)

**Comment by cpojer** [comment]
Moved to Yoga.

**Comment by EhsanSarshar** [comment]
I think this is must be a request in yoga other than react native. and If it implemented in yoga it will benefit other platforms beside react native
