### ISSUE TITLE
Share code between React and React Native

### ISSUE THREAD

**Issue by MaximeSauvage1** [react-native-community/discussions-and-proposals#93]
Hello everyone, french student here, I've spend some time to find an answer for my problem but I find too much... Would like a concrete answer...

### Introduction

As a developper, we all keep trying to reduce code dupplication. Redux store might be shared between React Website and React Native App.

### The Core of It

For a project I need to have a Website and a mobile App that both will consume my API. I used to work with React for Website so I've checked a lot about React-Native for the mobile App part. 

As I may understand, this require to create 2 distincts projects and it seems more efficient to do so (furthermore if these 2 projects don't share the same client). The problem is that both seems to use the same store... I don't want to dupplicate my store neither update both of them each time I update my API... The only difference I see between my React Website and my React Native App is the way they render. They will both have same functionalities. Can we go further by hypothesis that they will also share the same containers?

With some time, I've found a lot of solutions as :
 - .ios.js , .android.js , .web.js files on the same project
 - packaging the store to include it in both projects (don't know how for now...)
But any official advice in documentation...

### Note

I might not be the only one to have this problem and find informations on this subject has been very long. It might be a good idea to had a point on the official documentation about this question to clarify it...

Anyway, you've done a wonderful work here guys! Thanks you all.

**Comment by cpojer** [comment]
Hello,

thank you for creating this issue. Please not that this repository is for discussions about the development of React Native itself only, and is not used for user questions. I recommend you to ask your question on StackOverflow or reddit.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions about the technology side of RN. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

There have been many different strategies about code-sharing, but they are opinionated and not something that can have a "one-solution-fit-all"; I suggest you maybe discuss the approaches in the communities. You can look find a list of different communities here -> https://facebook.github.io/react-native/help

**Comment by cpojer** [comment]
I win!

**Comment by MaximeSauvage1** [comment]
@cpojer @kelset Thanks for you answers! I'm sorry, I'm kind of new in participating in other projects even if I'm register since a while now... I will ask my question somewhere else so...

**Comment by kelset** [comment]
Btw feel free to reach out to me over on twitter, my DMs are open - I can maybe link you some example projects!

**Comment by MaximeSauvage1** [comment]
@kelset Thanks it will help someone that have a twitter account ;)
