### ISSUE TITLE
targetContentOffset on Android

### ISSUE THREAD

**Issue by Bardiamist** [react-native-community/discussions-and-proposals#94]
### Introduction

`onScrollEndDrag` of `ScrollView` do not have `targetContentOffset` on Android.

### The Core of It

It possible to implment on Android?
Any body can do it?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests). Or try asaking on [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).
