### ISSUE TITLE
Import Aliases

### ISSUE THREAD

**Issue by Bardiamist** [react-native-community/discussions-and-proposals#95]
### Introduction

I want to understand how to works import aliases of react-native.

### The Core of It

Anybody can to explain me why `import type {SyntheticEvent} from 'CoreEventTypes';` works? 
Why flow understand `CoreEventTypes` alias?

Because `module.system.haste.paths.whitelist=<PROJECT_ROOT>/Libraries/.*` in `.flowconfig`?
But `.flowconfig` of react native project containts `module.system.haste.paths.whitelist=<PROJECT_ROOT>/node_modules/react-native/Libraries/.*` and I can't using alias `CoreEventTypes`. Why?

In `package.json` we have [entering point `react-native-implementation.js`](https://github.com/facebook/react-native/blob/master/package.json#L105)
But in `react-native-implementation.js` we have `require('View')`.
How it works?

### Discussion points

Probably, `metro` helps for `babel`.
But I'm more interested how `flow` to understands where to get props for `View` when we using `View` in jsx.

**Comment by satya164** [comment]
It's the `haste` module system used internally at Facebook. Personally, I'd recommend against it in your own projects. Use something like https://github.com/tleunen/babel-plugin-module-resolver to alias your stuff. it's more explicit.

**Comment by Bardiamist** [comment]
Hi @satya164
I know about `babel-plugin-module-resolver` and using it.
So, I can't use `import type {SyntheticEvent} from 'CoreEventTypes';` in my projects?

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a question for [StackOverflow instead](https://stackoverflow.com/questions/tagged/react-native).

(feel free to continue the conversation here anyway)
