### ISSUE TITLE
Unify devtools shortcut key combination across Android and iOS (in macOS)

### ISSUE THREAD

**Issue by JofBigHealth** [react-native-community/discussions-and-proposals#98]
### Introduction

`cmd-d` on the iOS simulator in macOS opens the dev tools.
`cmd-m` on the Android simulator in macOS opens the dev tools.
`cmd-m` on the _iOS_ simulator in macOS minimises it to the macOS dock.

### The Core of It

Any muscle memory for the Android simulator environment causes one to accidentally minimise the iOS simulator as oppose to loading the menu as expected. I've observed other developers having this issue multiple times a day so I suspect a large number of other RN users share the same problem.

### Discussion points

Proposal: either unify to `cmd-d` or something new?
Proposal: also change `cmd-r` to refresh in both environments? (I quite like `rr` though)

(Note: due to the way GitHub's search works I wasn't able to confirm if this issue had already been raised so apologies for the almost certain duplication of this issue. If anyone knows how to do a proper verbatim search of `⌘D` or `cmd-D` I'd love to know)

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).
